package org.apache.commons.math3.util;

import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RegressionTest7 {

    public static boolean debug = false;

    public void assertBooleanArrayEquals(boolean[] expectedArray, boolean[] actualArray) {
        if (expectedArray.length != actualArray.length) {
            throw new AssertionError("Array lengths differ: " + expectedArray.length + " != " + actualArray.length);
        }
        for (int i = 0; i < expectedArray.length; i++) {
            if (expectedArray[i] != actualArray[i]) {
                throw new AssertionError("Arrays differ at index " + i + ": " + expectedArray[i] + " != " + actualArray[i]);
            }
        }
    }

    @Test
    public void test3501() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest7.test3501");
        double[] doubleArray1 = new double[] { '#' };
        double[] doubleArray2 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray1);
        double[] doubleArray4 = new double[] { '#' };
        double[] doubleArray5 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray4);
        double[] doubleArray6 = org.apache.commons.math3.util.MathArrays.ebeAdd(doubleArray1, doubleArray4);
        double[] doubleArray8 = new double[] { '#' };
        double[] doubleArray9 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray8);
        double double10 = org.apache.commons.math3.util.MathArrays.distanceInf(doubleArray4, doubleArray8);
        double[] doubleArray12 = new double[] { '#' };
        double[] doubleArray13 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray12);
        double[] doubleArray15 = new double[] { '#' };
        double[] doubleArray16 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray15);
        double[] doubleArray17 = org.apache.commons.math3.util.MathArrays.ebeAdd(doubleArray12, doubleArray15);
        double[] doubleArray18 = org.apache.commons.math3.util.MathArrays.ebeAdd(doubleArray4, doubleArray12);
        double double19 = org.apache.commons.math3.util.MathArrays.safeNorm(doubleArray12);
        double[] doubleArray21 = new double[] { '#' };
        double[] doubleArray22 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray21);
        double[] doubleArray24 = new double[] { '#' };
        double[] doubleArray25 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray24);
        double[] doubleArray26 = org.apache.commons.math3.util.MathArrays.ebeAdd(doubleArray21, doubleArray24);
        double[] doubleArray28 = new double[] { '#' };
        double[] doubleArray29 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray28);
        double[] doubleArray30 = org.apache.commons.math3.util.MathArrays.ebeMultiply(doubleArray21, doubleArray28);
        double[] doubleArray32 = new double[] { '#' };
        double[] doubleArray33 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray32);
        double[] doubleArray35 = new double[] { '#' };
        double[] doubleArray36 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray35);
        double[] doubleArray37 = org.apache.commons.math3.util.MathArrays.ebeAdd(doubleArray32, doubleArray35);
        double[] doubleArray39 = new double[] { '#' };
        double[] doubleArray40 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray39);
        double[] doubleArray41 = org.apache.commons.math3.util.MathArrays.ebeMultiply(doubleArray32, doubleArray39);
        org.apache.commons.math3.util.MathArrays.checkPositive(doubleArray39);
        org.apache.commons.math3.util.MathArrays.checkPositive(doubleArray39);
        double[] doubleArray44 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray39);
        double[] doubleArray46 = new double[] { '#' };
        double[] doubleArray47 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray46);
        double[] doubleArray49 = new double[] { '#' };
        double[] doubleArray50 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray49);
        double[] doubleArray51 = org.apache.commons.math3.util.MathArrays.ebeAdd(doubleArray46, doubleArray49);
        double[] doubleArray53 = new double[] { '#' };
        double[] doubleArray54 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray53);
        boolean boolean55 = org.apache.commons.math3.util.MathArrays.equalsIncludingNaN(doubleArray49, doubleArray53);
        double[] doubleArray56 = org.apache.commons.math3.util.MathArrays.ebeDivide(doubleArray44, doubleArray49);
        double[] doubleArray57 = org.apache.commons.math3.util.MathArrays.ebeDivide(doubleArray28, doubleArray44);
        double[] doubleArray58 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray57);
        double[] doubleArray60 = new double[] { '#' };
        double[] doubleArray61 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray60);
        double[] doubleArray63 = new double[] { '#' };
        double[] doubleArray64 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray63);
        double[] doubleArray65 = org.apache.commons.math3.util.MathArrays.ebeAdd(doubleArray60, doubleArray63);
        org.apache.commons.math3.util.MathArrays.OrderDirection orderDirection66 = org.apache.commons.math3.util.MathArrays.OrderDirection.INCREASING;
        boolean boolean68 = org.apache.commons.math3.util.MathArrays.isMonotonic(doubleArray63, orderDirection66, false);
        boolean boolean70 = org.apache.commons.math3.util.MathArrays.isMonotonic(doubleArray57, orderDirection66, false);
        double[] doubleArray72 = new double[] { '#' };
        double[] doubleArray73 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray72);
        org.apache.commons.math3.util.MathArrays.OrderDirection orderDirection74 = org.apache.commons.math3.util.MathArrays.OrderDirection.INCREASING;
        boolean boolean76 = org.apache.commons.math3.util.MathArrays.isMonotonic(doubleArray73, orderDirection74, true);
        org.apache.commons.math3.util.MathArrays.checkOrder(doubleArray57, orderDirection74, false);
        org.apache.commons.math3.util.MathArrays.checkOrder(doubleArray57);
        double[] doubleArray81 = new double[] { '#' };
        double[] doubleArray82 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray81);
        double[] doubleArray84 = new double[] { '#' };
        double[] doubleArray85 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray84);
        double[] doubleArray86 = org.apache.commons.math3.util.MathArrays.ebeAdd(doubleArray81, doubleArray84);
        double[] doubleArray88 = new double[] { '#' };
        double[] doubleArray89 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray88);
        double[] doubleArray90 = org.apache.commons.math3.util.MathArrays.ebeMultiply(doubleArray81, doubleArray88);
        org.apache.commons.math3.util.MathArrays.checkPositive(doubleArray88);
        org.apache.commons.math3.util.MathArrays.checkPositive(doubleArray88);
        double[] doubleArray93 = org.apache.commons.math3.util.MathArrays.ebeMultiply(doubleArray57, doubleArray88);
        double[] doubleArray94 = org.apache.commons.math3.util.MathArrays.ebeMultiply(doubleArray12, doubleArray93);
        org.junit.Assert.assertNotNull(doubleArray1);
        org.junit.Assert.assertArrayEquals(doubleArray1, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray2);
        org.junit.Assert.assertArrayEquals(doubleArray2, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray4);
        org.junit.Assert.assertArrayEquals(doubleArray4, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray5);
        org.junit.Assert.assertArrayEquals(doubleArray5, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray6);
        org.junit.Assert.assertArrayEquals(doubleArray6, new double[] { 70.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray8);
        org.junit.Assert.assertArrayEquals(doubleArray8, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray9);
        org.junit.Assert.assertArrayEquals(doubleArray9, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertTrue("'" + double10 + "' != '" + 0.0d + "'", double10 == 0.0d);
        org.junit.Assert.assertNotNull(doubleArray12);
        org.junit.Assert.assertArrayEquals(doubleArray12, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray13);
        org.junit.Assert.assertArrayEquals(doubleArray13, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray15);
        org.junit.Assert.assertArrayEquals(doubleArray15, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray16);
        org.junit.Assert.assertArrayEquals(doubleArray16, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray17);
        org.junit.Assert.assertArrayEquals(doubleArray17, new double[] { 70.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray18);
        org.junit.Assert.assertArrayEquals(doubleArray18, new double[] { 70.0d }, 1.0E-15);
        org.junit.Assert.assertTrue("'" + double19 + "' != '" + 35.0d + "'", double19 == 35.0d);
        org.junit.Assert.assertNotNull(doubleArray21);
        org.junit.Assert.assertArrayEquals(doubleArray21, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray22);
        org.junit.Assert.assertArrayEquals(doubleArray22, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray24);
        org.junit.Assert.assertArrayEquals(doubleArray24, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray25);
        org.junit.Assert.assertArrayEquals(doubleArray25, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray26);
        org.junit.Assert.assertArrayEquals(doubleArray26, new double[] { 70.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray28);
        org.junit.Assert.assertArrayEquals(doubleArray28, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray29);
        org.junit.Assert.assertArrayEquals(doubleArray29, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray30);
        org.junit.Assert.assertArrayEquals(doubleArray30, new double[] { 1225.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray32);
        org.junit.Assert.assertArrayEquals(doubleArray32, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray33);
        org.junit.Assert.assertArrayEquals(doubleArray33, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray35);
        org.junit.Assert.assertArrayEquals(doubleArray35, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray36);
        org.junit.Assert.assertArrayEquals(doubleArray36, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray37);
        org.junit.Assert.assertArrayEquals(doubleArray37, new double[] { 70.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray39);
        org.junit.Assert.assertArrayEquals(doubleArray39, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray40);
        org.junit.Assert.assertArrayEquals(doubleArray40, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray41);
        org.junit.Assert.assertArrayEquals(doubleArray41, new double[] { 1225.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray44);
        org.junit.Assert.assertArrayEquals(doubleArray44, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray46);
        org.junit.Assert.assertArrayEquals(doubleArray46, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray47);
        org.junit.Assert.assertArrayEquals(doubleArray47, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray49);
        org.junit.Assert.assertArrayEquals(doubleArray49, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray50);
        org.junit.Assert.assertArrayEquals(doubleArray50, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray51);
        org.junit.Assert.assertArrayEquals(doubleArray51, new double[] { 70.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray53);
        org.junit.Assert.assertArrayEquals(doubleArray53, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray54);
        org.junit.Assert.assertArrayEquals(doubleArray54, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertTrue("'" + boolean55 + "' != '" + true + "'", boolean55 == true);
        org.junit.Assert.assertNotNull(doubleArray56);
        org.junit.Assert.assertArrayEquals(doubleArray56, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray57);
        org.junit.Assert.assertArrayEquals(doubleArray57, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray58);
        org.junit.Assert.assertArrayEquals(doubleArray58, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray60);
        org.junit.Assert.assertArrayEquals(doubleArray60, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray61);
        org.junit.Assert.assertArrayEquals(doubleArray61, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray63);
        org.junit.Assert.assertArrayEquals(doubleArray63, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray64);
        org.junit.Assert.assertArrayEquals(doubleArray64, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray65);
        org.junit.Assert.assertArrayEquals(doubleArray65, new double[] { 70.0d }, 1.0E-15);
        org.junit.Assert.assertTrue("'" + orderDirection66 + "' != '" + org.apache.commons.math3.util.MathArrays.OrderDirection.INCREASING + "'", orderDirection66.equals(org.apache.commons.math3.util.MathArrays.OrderDirection.INCREASING));
        org.junit.Assert.assertTrue("'" + boolean68 + "' != '" + true + "'", boolean68 == true);
        org.junit.Assert.assertTrue("'" + boolean70 + "' != '" + true + "'", boolean70 == true);
        org.junit.Assert.assertNotNull(doubleArray72);
        org.junit.Assert.assertArrayEquals(doubleArray72, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray73);
        org.junit.Assert.assertArrayEquals(doubleArray73, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertTrue("'" + orderDirection74 + "' != '" + org.apache.commons.math3.util.MathArrays.OrderDirection.INCREASING + "'", orderDirection74.equals(org.apache.commons.math3.util.MathArrays.OrderDirection.INCREASING));
        org.junit.Assert.assertTrue("'" + boolean76 + "' != '" + true + "'", boolean76 == true);
        org.junit.Assert.assertNotNull(doubleArray81);
        org.junit.Assert.assertArrayEquals(doubleArray81, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray82);
        org.junit.Assert.assertArrayEquals(doubleArray82, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray84);
        org.junit.Assert.assertArrayEquals(doubleArray84, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray85);
        org.junit.Assert.assertArrayEquals(doubleArray85, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray86);
        org.junit.Assert.assertArrayEquals(doubleArray86, new double[] { 70.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray88);
        org.junit.Assert.assertArrayEquals(doubleArray88, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray89);
        org.junit.Assert.assertArrayEquals(doubleArray89, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray90);
        org.junit.Assert.assertArrayEquals(doubleArray90, new double[] { 1225.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray93);
        org.junit.Assert.assertArrayEquals(doubleArray93, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray94);
        org.junit.Assert.assertArrayEquals(doubleArray94, new double[] { 1225.0d }, 1.0E-15);
    }

    @Test
    public void test3502() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest7.test3502");
        double double8 = org.apache.commons.math3.util.MathArrays.linearCombination(1.0189090172701963E260d, 2.02593011256236E55d, 7.39312254719539E216d, 8.113090125E9d, 68900.0d, 7.918034248046261E220d, (-2.091777440186928E225d), (-2.064028834475282E257d));
        org.junit.Assert.assertTrue("'" + double8 + "' != '" + Double.POSITIVE_INFINITY + "'", double8 == Double.POSITIVE_INFINITY);
    }

    @Test
    public void test3503() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest7.test3503");
        long[][] longArray0 = new long[][] {};
        org.apache.commons.math3.util.MathArrays.checkRectangular(longArray0);
        org.apache.commons.math3.util.MathArrays.checkNonNegative(longArray0);
        org.apache.commons.math3.util.MathArrays.checkRectangular(longArray0);
        org.apache.commons.math3.util.MathArrays.checkRectangular(longArray0);
        org.apache.commons.math3.util.MathArrays.checkNonNegative(longArray0);
        org.apache.commons.math3.util.MathArrays.checkNonNegative(longArray0);
        org.apache.commons.math3.util.MathArrays.checkNonNegative(longArray0);
        org.apache.commons.math3.util.MathArrays.checkNonNegative(longArray0);
        org.apache.commons.math3.util.MathArrays.checkRectangular(longArray0);
        org.junit.Assert.assertNotNull(longArray0);
        org.junit.Assert.assertArrayEquals(longArray0, new long[][] {});
    }

    @Test
    public void test3504() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest7.test3504");
        double[] doubleArray1 = new double[] { '#' };
        double[] doubleArray2 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray1);
        double[] doubleArray4 = new double[] { '#' };
        double[] doubleArray5 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray4);
        double[] doubleArray6 = org.apache.commons.math3.util.MathArrays.ebeAdd(doubleArray1, doubleArray4);
        double[] doubleArray8 = new double[] { '#' };
        double[] doubleArray9 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray8);
        double[] doubleArray10 = org.apache.commons.math3.util.MathArrays.ebeMultiply(doubleArray1, doubleArray8);
        org.apache.commons.math3.util.MathArrays.checkPositive(doubleArray8);
        org.apache.commons.math3.util.MathArrays.checkPositive(doubleArray8);
        double[] doubleArray14 = new double[] { '#' };
        double[] doubleArray15 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray14);
        double[] doubleArray17 = new double[] { '#' };
        double[] doubleArray18 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray17);
        double[] doubleArray19 = org.apache.commons.math3.util.MathArrays.ebeAdd(doubleArray14, doubleArray17);
        double[] doubleArray21 = new double[] { '#' };
        double[] doubleArray22 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray21);
        double[] doubleArray23 = org.apache.commons.math3.util.MathArrays.ebeMultiply(doubleArray14, doubleArray21);
        org.apache.commons.math3.util.MathArrays.OrderDirection orderDirection24 = org.apache.commons.math3.util.MathArrays.OrderDirection.INCREASING;
        boolean boolean26 = org.apache.commons.math3.util.MathArrays.isMonotonic(doubleArray14, orderDirection24, false);
        double[] doubleArray27 = org.apache.commons.math3.util.MathArrays.ebeDivide(doubleArray8, doubleArray14);
        double[] doubleArray29 = new double[] { '#' };
        double[] doubleArray30 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray29);
        double[] doubleArray32 = new double[] { '#' };
        double[] doubleArray33 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray32);
        double[] doubleArray34 = org.apache.commons.math3.util.MathArrays.ebeAdd(doubleArray29, doubleArray32);
        double[] doubleArray35 = org.apache.commons.math3.util.MathArrays.ebeDivide(doubleArray14, doubleArray29);
        double[] doubleArray37 = new double[] { (byte) 10 };
        double[][] doubleArray38 = new double[][] { doubleArray37 };
        org.apache.commons.math3.util.MathArrays.sortInPlace(doubleArray35, doubleArray38);
        double[] doubleArray40 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray35);
        double[] doubleArray44 = new double[] { '#' };
        double[] doubleArray45 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray44);
        double[] doubleArray47 = new double[] { '#' };
        double[] doubleArray48 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray47);
        double[] doubleArray49 = org.apache.commons.math3.util.MathArrays.ebeAdd(doubleArray44, doubleArray47);
        double[] doubleArray51 = new double[] { '#' };
        double[] doubleArray52 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray51);
        double double53 = org.apache.commons.math3.util.MathArrays.distanceInf(doubleArray47, doubleArray51);
        double[] doubleArray55 = new double[] { '#' };
        double[] doubleArray56 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray55);
        double[] doubleArray58 = new double[] { '#' };
        double[] doubleArray59 = org.apache.commons.math3.util.MathArrays.copyOf(doubleArray58);
        double[] doubleArray60 = org.apache.commons.math3.util.MathArrays.ebeAdd(doubleArray55, doubleArray58);
        double[] doubleArray61 = org.apache.commons.math3.util.MathArrays.ebeAdd(doubleArray47, doubleArray55);
        org.apache.commons.math3.util.MathArrays.scaleInPlace((double) 'a', doubleArray55);
        double[] doubleArray63 = org.apache.commons.math3.util.MathArrays.scale(1.3270113046915585E68d, doubleArray55);
        org.apache.commons.math3.util.MathArrays.checkOrder(doubleArray63);
        double[] doubleArray65 = org.apache.commons.math3.util.MathArrays.ebeMultiply(doubleArray35, doubleArray63);
        java.lang.Class<?> wildcardClass66 = doubleArray63.getClass();
        org.junit.Assert.assertNotNull(doubleArray1);
        org.junit.Assert.assertArrayEquals(doubleArray1, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray2);
        org.junit.Assert.assertArrayEquals(doubleArray2, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray4);
        org.junit.Assert.assertArrayEquals(doubleArray4, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray5);
        org.junit.Assert.assertArrayEquals(doubleArray5, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray6);
        org.junit.Assert.assertArrayEquals(doubleArray6, new double[] { 70.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray8);
        org.junit.Assert.assertArrayEquals(doubleArray8, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray9);
        org.junit.Assert.assertArrayEquals(doubleArray9, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray10);
        org.junit.Assert.assertArrayEquals(doubleArray10, new double[] { 1225.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray14);
        org.junit.Assert.assertArrayEquals(doubleArray14, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray15);
        org.junit.Assert.assertArrayEquals(doubleArray15, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray17);
        org.junit.Assert.assertArrayEquals(doubleArray17, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray18);
        org.junit.Assert.assertArrayEquals(doubleArray18, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray19);
        org.junit.Assert.assertArrayEquals(doubleArray19, new double[] { 70.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray21);
        org.junit.Assert.assertArrayEquals(doubleArray21, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray22);
        org.junit.Assert.assertArrayEquals(doubleArray22, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray23);
        org.junit.Assert.assertArrayEquals(doubleArray23, new double[] { 1225.0d }, 1.0E-15);
        org.junit.Assert.assertTrue("'" + orderDirection24 + "' != '" + org.apache.commons.math3.util.MathArrays.OrderDirection.INCREASING + "'", orderDirection24.equals(org.apache.commons.math3.util.MathArrays.OrderDirection.INCREASING));
        org.junit.Assert.assertTrue("'" + boolean26 + "' != '" + true + "'", boolean26 == true);
        org.junit.Assert.assertNotNull(doubleArray27);
        org.junit.Assert.assertArrayEquals(doubleArray27, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray29);
        org.junit.Assert.assertArrayEquals(doubleArray29, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray30);
        org.junit.Assert.assertArrayEquals(doubleArray30, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray32);
        org.junit.Assert.assertArrayEquals(doubleArray32, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray33);
        org.junit.Assert.assertArrayEquals(doubleArray33, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray34);
        org.junit.Assert.assertArrayEquals(doubleArray34, new double[] { 70.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray35);
        org.junit.Assert.assertArrayEquals(doubleArray35, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray37);
        org.junit.Assert.assertArrayEquals(doubleArray37, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray38);
        org.junit.Assert.assertNotNull(doubleArray40);
        org.junit.Assert.assertArrayEquals(doubleArray40, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray44);
        org.junit.Assert.assertArrayEquals(doubleArray44, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray45);
        org.junit.Assert.assertArrayEquals(doubleArray45, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray47);
        org.junit.Assert.assertArrayEquals(doubleArray47, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray48);
        org.junit.Assert.assertArrayEquals(doubleArray48, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray49);
        org.junit.Assert.assertArrayEquals(doubleArray49, new double[] { 70.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray51);
        org.junit.Assert.assertArrayEquals(doubleArray51, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray52);
        org.junit.Assert.assertArrayEquals(doubleArray52, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertTrue("'" + double53 + "' != '" + 0.0d + "'", double53 == 0.0d);
        org.junit.Assert.assertNotNull(doubleArray55);
        org.junit.Assert.assertArrayEquals(doubleArray55, new double[] { 3395.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray56);
        org.junit.Assert.assertArrayEquals(doubleArray56, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray58);
        org.junit.Assert.assertArrayEquals(doubleArray58, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray59);
        org.junit.Assert.assertArrayEquals(doubleArray59, new double[] { 35.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray60);
        org.junit.Assert.assertArrayEquals(doubleArray60, new double[] { 70.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray61);
        org.junit.Assert.assertArrayEquals(doubleArray61, new double[] { 70.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray63);
        org.junit.Assert.assertArrayEquals(doubleArray63, new double[] { 4.505203379427841E71d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray65);
        org.junit.Assert.assertArrayEquals(doubleArray65, new double[] { 4.505203379427841E71d }, 1.0E-15);
        org.junit.Assert.assertNotNull(wildcardClass66);
    }
}

