package com.fasterxml.jackson.databind.util;

import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class ErrorTest0 {

    public static boolean debug = false;

    public void assertBooleanArrayEquals(boolean[] expectedArray, boolean[] actualArray) {
        if (expectedArray.length != actualArray.length) {
            throw new AssertionError("Array lengths differ: " + expectedArray.length + " != " + actualArray.length);
        }
        for (int i = 0; i < expectedArray.length; i++) {
            if (expectedArray[i] != actualArray[i]) {
                throw new AssertionError("Arrays differ at index " + i + ": " + expectedArray[i] + " != " + actualArray[i]);
            }
        }
    }

    @Test
    public void test1() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test1");
        java.util.TimeZone timeZone0 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale1 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat3 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone0, locale1, (java.lang.Boolean) false);
        java.util.TimeZone timeZone4 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale5 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat7 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone4, locale5, (java.lang.Boolean) false);
        java.util.Locale locale8 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat10 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone4, locale8, (java.lang.Boolean) true);
        boolean boolean11 = stdDateFormat3.equals((java.lang.Object) locale8);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat12 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat14 = stdDateFormat12.withColonInTimeZone(false);
        boolean boolean16 = stdDateFormat12.looksLikeISO8601("hi!");
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat17 = stdDateFormat12.clone();
        java.util.TimeZone timeZone18 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat19 = stdDateFormat12.withTimeZone(timeZone18);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat20 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat22 = stdDateFormat20.withColonInTimeZone(false);
        java.lang.Boolean boolean23 = stdDateFormat20._lenient;
        stdDateFormat20.setLenient(true);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat26 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat28 = stdDateFormat26.withColonInTimeZone(false);
        boolean boolean30 = stdDateFormat26.looksLikeISO8601("hi!");
        java.util.TimeZone timeZone31 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        stdDateFormat26.setTimeZone(timeZone31);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat33 = stdDateFormat20.withTimeZone(timeZone31);
        java.util.Calendar calendar34 = stdDateFormat12._getCalendar(timeZone31);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat35 = stdDateFormat3.withTimeZone(timeZone31);
        java.lang.String str36 = stdDateFormat3.toString();
        java.util.TimeZone timeZone37 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.TimeZone timeZone38 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale39 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat41 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone38, locale39, (java.lang.Boolean) false);
        java.util.Locale locale42 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat44 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone38, locale42, (java.lang.Boolean) true);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat45 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat47 = stdDateFormat45.withColonInTimeZone(false);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat49 = stdDateFormat47.withColonInTimeZone(true);
        java.util.Locale locale50 = stdDateFormat49._locale;
        java.text.DateFormat dateFormat51 = com.fasterxml.jackson.databind.util.StdDateFormat.getRFC1123Format(timeZone38, locale50);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat52 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone37, locale50);
        java.util.TimeZone timeZone53 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.TimeZone timeZone54 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale55 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat57 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone54, locale55, (java.lang.Boolean) false);
        java.util.Locale locale58 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat60 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone54, locale58, (java.lang.Boolean) true);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat61 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat63 = stdDateFormat61.withColonInTimeZone(false);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat65 = stdDateFormat63.withColonInTimeZone(true);
        java.util.Locale locale66 = stdDateFormat65._locale;
        java.text.DateFormat dateFormat67 = com.fasterxml.jackson.databind.util.StdDateFormat.getRFC1123Format(timeZone54, locale66);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat68 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone53, locale66);
        java.util.TimeZone timeZone70 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale71 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat73 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone70, locale71, (java.lang.Boolean) false);
        java.util.Locale locale74 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat76 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone70, locale74, (java.lang.Boolean) true);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat77 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat79 = stdDateFormat77.withColonInTimeZone(false);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat81 = stdDateFormat79.withColonInTimeZone(true);
        java.util.Locale locale82 = stdDateFormat81._locale;
        java.text.DateFormat dateFormat83 = com.fasterxml.jackson.databind.util.StdDateFormat.getRFC1123Format(timeZone70, locale82);
        java.text.DateFormat dateFormat84 = java.text.DateFormat.getTimeInstance(0, locale82);
        java.text.DateFormat dateFormat85 = com.fasterxml.jackson.databind.util.StdDateFormat.getISO8601Format(timeZone53, locale82);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat86 = stdDateFormat52.withTimeZone(timeZone53);
        java.util.TimeZone timeZone87 = stdDateFormat86.getTimeZone();
        java.util.Calendar calendar88 = stdDateFormat3._getCalendar(timeZone87);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat89 = stdDateFormat3.clone();
        org.junit.Assert.assertTrue("Contract failed: compareTo-equals on calendar34 and calendar88", (calendar34.compareTo(calendar88) == 0) == calendar34.equals(calendar88));
    }

    @Test
    public void test2() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test2");
        java.util.TimeZone timeZone0 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale1 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat3 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone0, locale1, (java.lang.Boolean) false);
        java.util.TimeZone timeZone4 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale5 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat7 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone4, locale5, (java.lang.Boolean) false);
        java.util.Locale locale8 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat10 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone4, locale8, (java.lang.Boolean) true);
        boolean boolean11 = stdDateFormat3.equals((java.lang.Object) locale8);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat12 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat14 = stdDateFormat12.withColonInTimeZone(false);
        boolean boolean16 = stdDateFormat12.looksLikeISO8601("hi!");
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat17 = stdDateFormat12.clone();
        java.util.TimeZone timeZone18 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat19 = stdDateFormat12.withTimeZone(timeZone18);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat20 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat22 = stdDateFormat20.withColonInTimeZone(false);
        java.lang.Boolean boolean23 = stdDateFormat20._lenient;
        stdDateFormat20.setLenient(true);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat26 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat28 = stdDateFormat26.withColonInTimeZone(false);
        boolean boolean30 = stdDateFormat26.looksLikeISO8601("hi!");
        java.util.TimeZone timeZone31 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        stdDateFormat26.setTimeZone(timeZone31);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat33 = stdDateFormat20.withTimeZone(timeZone31);
        java.util.Calendar calendar34 = stdDateFormat12._getCalendar(timeZone31);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat35 = stdDateFormat3.withTimeZone(timeZone31);
        java.lang.String str36 = stdDateFormat3.toString();
        java.util.TimeZone timeZone37 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.TimeZone timeZone38 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale39 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat41 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone38, locale39, (java.lang.Boolean) false);
        java.util.Locale locale42 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat44 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone38, locale42, (java.lang.Boolean) true);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat45 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat47 = stdDateFormat45.withColonInTimeZone(false);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat49 = stdDateFormat47.withColonInTimeZone(true);
        java.util.Locale locale50 = stdDateFormat49._locale;
        java.text.DateFormat dateFormat51 = com.fasterxml.jackson.databind.util.StdDateFormat.getRFC1123Format(timeZone38, locale50);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat52 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone37, locale50);
        java.util.TimeZone timeZone53 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.TimeZone timeZone54 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale55 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat57 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone54, locale55, (java.lang.Boolean) false);
        java.util.Locale locale58 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat60 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone54, locale58, (java.lang.Boolean) true);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat61 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat63 = stdDateFormat61.withColonInTimeZone(false);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat65 = stdDateFormat63.withColonInTimeZone(true);
        java.util.Locale locale66 = stdDateFormat65._locale;
        java.text.DateFormat dateFormat67 = com.fasterxml.jackson.databind.util.StdDateFormat.getRFC1123Format(timeZone54, locale66);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat68 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone53, locale66);
        java.util.TimeZone timeZone70 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale71 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat73 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone70, locale71, (java.lang.Boolean) false);
        java.util.Locale locale74 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat76 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone70, locale74, (java.lang.Boolean) true);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat77 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat79 = stdDateFormat77.withColonInTimeZone(false);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat81 = stdDateFormat79.withColonInTimeZone(true);
        java.util.Locale locale82 = stdDateFormat81._locale;
        java.text.DateFormat dateFormat83 = com.fasterxml.jackson.databind.util.StdDateFormat.getRFC1123Format(timeZone70, locale82);
        java.text.DateFormat dateFormat84 = java.text.DateFormat.getTimeInstance(0, locale82);
        java.text.DateFormat dateFormat85 = com.fasterxml.jackson.databind.util.StdDateFormat.getISO8601Format(timeZone53, locale82);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat86 = stdDateFormat52.withTimeZone(timeZone53);
        java.util.TimeZone timeZone87 = stdDateFormat86.getTimeZone();
        java.util.Calendar calendar88 = stdDateFormat3._getCalendar(timeZone87);
        stdDateFormat3._lenient = false;
        org.junit.Assert.assertTrue("Contract failed: compareTo-equals on calendar34 and calendar88", (calendar34.compareTo(calendar88) == 0) == calendar34.equals(calendar88));
    }

    @Test
    public void test3() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test3");
        java.util.TimeZone timeZone0 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale1 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat3 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone0, locale1, (java.lang.Boolean) false);
        java.util.TimeZone timeZone4 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale5 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat7 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone4, locale5, (java.lang.Boolean) false);
        java.util.Locale locale8 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat10 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone4, locale8, (java.lang.Boolean) true);
        boolean boolean11 = stdDateFormat3.equals((java.lang.Object) locale8);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat12 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat14 = stdDateFormat12.withColonInTimeZone(false);
        boolean boolean16 = stdDateFormat12.looksLikeISO8601("hi!");
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat17 = stdDateFormat12.clone();
        java.util.TimeZone timeZone18 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat19 = stdDateFormat12.withTimeZone(timeZone18);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat20 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat22 = stdDateFormat20.withColonInTimeZone(false);
        java.lang.Boolean boolean23 = stdDateFormat20._lenient;
        stdDateFormat20.setLenient(true);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat26 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat28 = stdDateFormat26.withColonInTimeZone(false);
        boolean boolean30 = stdDateFormat26.looksLikeISO8601("hi!");
        java.util.TimeZone timeZone31 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        stdDateFormat26.setTimeZone(timeZone31);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat33 = stdDateFormat20.withTimeZone(timeZone31);
        java.util.Calendar calendar34 = stdDateFormat12._getCalendar(timeZone31);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat35 = stdDateFormat3.withTimeZone(timeZone31);
        java.lang.String str36 = stdDateFormat3.toPattern();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat37 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat39 = stdDateFormat37.withColonInTimeZone(false);
        boolean boolean41 = stdDateFormat37.looksLikeISO8601("hi!");
        java.util.TimeZone timeZone42 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        stdDateFormat37.setTimeZone(timeZone42);
        java.lang.String str45 = stdDateFormat37.format((java.lang.Object) 0L);
        boolean boolean46 = stdDateFormat37.isColonIncludedInTimeZone();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat47 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat49 = stdDateFormat47.withColonInTimeZone(false);
        java.lang.Boolean boolean50 = stdDateFormat47._lenient;
        boolean boolean52 = stdDateFormat47.equals((java.lang.Object) (byte) 1);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat53 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat55 = stdDateFormat53.withColonInTimeZone(false);
        boolean boolean57 = stdDateFormat53.looksLikeISO8601("hi!");
        java.util.TimeZone timeZone58 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        stdDateFormat53.setTimeZone(timeZone58);
        stdDateFormat47.setTimeZone(timeZone58);
        stdDateFormat37._timezone = timeZone58;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat62 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat64 = stdDateFormat62.withColonInTimeZone(false);
        boolean boolean66 = stdDateFormat62.looksLikeISO8601("hi!");
        boolean boolean68 = stdDateFormat62.looksLikeISO8601("DateFormat com.fasterxml.jackson.databind.util.StdDateFormat: (timezone: null, locale: en_US, lenient: null)");
        java.util.Locale locale69 = stdDateFormat62._locale;
        java.text.DateFormat dateFormat70 = com.fasterxml.jackson.databind.util.StdDateFormat.getRFC1123Format(timeZone58, locale69);
        java.util.Calendar calendar71 = stdDateFormat3._getCalendar(timeZone58);
        java.lang.String str72 = stdDateFormat3.toPattern();
        org.junit.Assert.assertTrue("Contract failed: compareTo-equals on calendar34 and calendar71", (calendar34.compareTo(calendar71) == 0) == calendar34.equals(calendar71));
    }

    @Test
    public void test4() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test4");
        java.util.TimeZone timeZone0 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale1 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat3 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone0, locale1, (java.lang.Boolean) false);
        java.util.TimeZone timeZone4 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.TimeZone timeZone6 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale7 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat9 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone6, locale7, (java.lang.Boolean) false);
        java.util.Locale locale10 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat12 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone6, locale10, (java.lang.Boolean) true);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat13 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat15 = stdDateFormat13.withColonInTimeZone(false);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat17 = stdDateFormat15.withColonInTimeZone(true);
        java.util.Locale locale18 = stdDateFormat17._locale;
        java.text.DateFormat dateFormat19 = com.fasterxml.jackson.databind.util.StdDateFormat.getRFC1123Format(timeZone6, locale18);
        java.text.DateFormat dateFormat20 = java.text.DateFormat.getTimeInstance(0, locale18);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat22 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone4, locale18, (java.lang.Boolean) false);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat23 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat25 = stdDateFormat23.withColonInTimeZone(false);
        boolean boolean27 = stdDateFormat23.looksLikeISO8601("hi!");
        java.util.TimeZone timeZone28 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        stdDateFormat23.setTimeZone(timeZone28);
        java.util.TimeZone timeZone30 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale31 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat33 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone30, locale31, (java.lang.Boolean) false);
        java.util.Locale locale34 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat36 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone30, locale34, (java.lang.Boolean) true);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat37 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat39 = stdDateFormat37.withColonInTimeZone(false);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat41 = stdDateFormat39.withColonInTimeZone(true);
        java.util.Locale locale42 = stdDateFormat41._locale;
        java.text.DateFormat dateFormat43 = com.fasterxml.jackson.databind.util.StdDateFormat.getRFC1123Format(timeZone30, locale42);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat44 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone28, locale42);
        stdDateFormat22._timezone = timeZone28;
        boolean boolean46 = stdDateFormat3.equals((java.lang.Object) stdDateFormat22);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat47 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat49 = stdDateFormat47.withColonInTimeZone(false);
        boolean boolean51 = stdDateFormat47.looksLikeISO8601("hi!");
        boolean boolean53 = stdDateFormat47.looksLikeISO8601("DateFormat com.fasterxml.jackson.databind.util.StdDateFormat: (timezone: null, locale: en_US, lenient: null)");
        java.util.TimeZone timeZone54 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.TimeZone timeZone56 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale57 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat59 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone56, locale57, (java.lang.Boolean) false);
        java.util.Locale locale60 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat62 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone56, locale60, (java.lang.Boolean) true);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat63 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat65 = stdDateFormat63.withColonInTimeZone(false);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat67 = stdDateFormat65.withColonInTimeZone(true);
        java.util.Locale locale68 = stdDateFormat67._locale;
        java.text.DateFormat dateFormat69 = com.fasterxml.jackson.databind.util.StdDateFormat.getRFC1123Format(timeZone56, locale68);
        java.text.DateFormat dateFormat70 = java.text.DateFormat.getTimeInstance(0, locale68);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat72 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone54, locale68, (java.lang.Boolean) false);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat73 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat75 = stdDateFormat73.withColonInTimeZone(false);
        boolean boolean77 = stdDateFormat73.looksLikeISO8601("hi!");
        java.util.TimeZone timeZone78 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        stdDateFormat73.setTimeZone(timeZone78);
        java.util.TimeZone timeZone80 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale81 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat83 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone80, locale81, (java.lang.Boolean) false);
        java.util.Locale locale84 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat86 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone80, locale84, (java.lang.Boolean) true);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat87 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat89 = stdDateFormat87.withColonInTimeZone(false);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat91 = stdDateFormat89.withColonInTimeZone(true);
        java.util.Locale locale92 = stdDateFormat91._locale;
        java.text.DateFormat dateFormat93 = com.fasterxml.jackson.databind.util.StdDateFormat.getRFC1123Format(timeZone80, locale92);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat94 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone78, locale92);
        stdDateFormat72._timezone = timeZone78;
        java.util.Calendar calendar96 = stdDateFormat47._getCalendar(timeZone78);
        java.util.Calendar calendar97 = stdDateFormat22._getCalendar(timeZone78);
        java.util.Locale locale98 = stdDateFormat22._locale;
        org.junit.Assert.assertTrue("Contract failed: compareTo-equals on calendar96 and calendar97", (calendar96.compareTo(calendar97) == 0) == calendar96.equals(calendar97));
    }

    @Test
    public void test5() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test5");
        java.util.TimeZone timeZone0 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale1 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat3 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone0, locale1, (java.lang.Boolean) false);
        java.util.TimeZone timeZone4 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale5 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat7 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone4, locale5, (java.lang.Boolean) false);
        java.util.Locale locale8 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat10 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone4, locale8, (java.lang.Boolean) true);
        boolean boolean11 = stdDateFormat3.equals((java.lang.Object) locale8);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat12 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat14 = stdDateFormat12.withColonInTimeZone(false);
        boolean boolean16 = stdDateFormat12.looksLikeISO8601("hi!");
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat17 = stdDateFormat12.clone();
        java.util.TimeZone timeZone18 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat19 = stdDateFormat12.withTimeZone(timeZone18);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat20 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat22 = stdDateFormat20.withColonInTimeZone(false);
        java.lang.Boolean boolean23 = stdDateFormat20._lenient;
        stdDateFormat20.setLenient(true);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat26 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat28 = stdDateFormat26.withColonInTimeZone(false);
        boolean boolean30 = stdDateFormat26.looksLikeISO8601("hi!");
        java.util.TimeZone timeZone31 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        stdDateFormat26.setTimeZone(timeZone31);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat33 = stdDateFormat20.withTimeZone(timeZone31);
        java.util.Calendar calendar34 = stdDateFormat12._getCalendar(timeZone31);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat35 = stdDateFormat3.withTimeZone(timeZone31);
        java.lang.String str36 = stdDateFormat3.toString();
        java.util.TimeZone timeZone37 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.TimeZone timeZone38 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale39 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat41 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone38, locale39, (java.lang.Boolean) false);
        java.util.Locale locale42 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat44 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone38, locale42, (java.lang.Boolean) true);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat45 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat47 = stdDateFormat45.withColonInTimeZone(false);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat49 = stdDateFormat47.withColonInTimeZone(true);
        java.util.Locale locale50 = stdDateFormat49._locale;
        java.text.DateFormat dateFormat51 = com.fasterxml.jackson.databind.util.StdDateFormat.getRFC1123Format(timeZone38, locale50);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat52 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone37, locale50);
        java.util.TimeZone timeZone53 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.TimeZone timeZone54 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale55 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat57 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone54, locale55, (java.lang.Boolean) false);
        java.util.Locale locale58 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat60 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone54, locale58, (java.lang.Boolean) true);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat61 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat63 = stdDateFormat61.withColonInTimeZone(false);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat65 = stdDateFormat63.withColonInTimeZone(true);
        java.util.Locale locale66 = stdDateFormat65._locale;
        java.text.DateFormat dateFormat67 = com.fasterxml.jackson.databind.util.StdDateFormat.getRFC1123Format(timeZone54, locale66);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat68 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone53, locale66);
        java.util.TimeZone timeZone70 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale71 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat73 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone70, locale71, (java.lang.Boolean) false);
        java.util.Locale locale74 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat76 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone70, locale74, (java.lang.Boolean) true);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat77 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat79 = stdDateFormat77.withColonInTimeZone(false);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat81 = stdDateFormat79.withColonInTimeZone(true);
        java.util.Locale locale82 = stdDateFormat81._locale;
        java.text.DateFormat dateFormat83 = com.fasterxml.jackson.databind.util.StdDateFormat.getRFC1123Format(timeZone70, locale82);
        java.text.DateFormat dateFormat84 = java.text.DateFormat.getTimeInstance(0, locale82);
        java.text.DateFormat dateFormat85 = com.fasterxml.jackson.databind.util.StdDateFormat.getISO8601Format(timeZone53, locale82);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat86 = stdDateFormat52.withTimeZone(timeZone53);
        java.util.TimeZone timeZone87 = stdDateFormat86.getTimeZone();
        java.util.Calendar calendar88 = stdDateFormat3._getCalendar(timeZone87);
        boolean boolean90 = stdDateFormat3.looksLikeISO8601("1970-01-01T00:00:00.001+0000");
        org.junit.Assert.assertTrue("Contract failed: compareTo-equals on calendar34 and calendar88", (calendar34.compareTo(calendar88) == 0) == calendar34.equals(calendar88));
    }

    @Test
    public void test6() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test6");
        java.util.TimeZone timeZone0 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale1 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat3 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone0, locale1, (java.lang.Boolean) false);
        java.util.TimeZone timeZone4 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale5 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat7 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone4, locale5, (java.lang.Boolean) false);
        java.util.Locale locale8 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat10 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone4, locale8, (java.lang.Boolean) true);
        boolean boolean11 = stdDateFormat3.equals((java.lang.Object) locale8);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat12 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat14 = stdDateFormat12.withColonInTimeZone(false);
        boolean boolean16 = stdDateFormat12.looksLikeISO8601("hi!");
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat17 = stdDateFormat12.clone();
        java.util.TimeZone timeZone18 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat19 = stdDateFormat12.withTimeZone(timeZone18);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat20 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat22 = stdDateFormat20.withColonInTimeZone(false);
        java.lang.Boolean boolean23 = stdDateFormat20._lenient;
        stdDateFormat20.setLenient(true);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat26 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat28 = stdDateFormat26.withColonInTimeZone(false);
        boolean boolean30 = stdDateFormat26.looksLikeISO8601("hi!");
        java.util.TimeZone timeZone31 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        stdDateFormat26.setTimeZone(timeZone31);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat33 = stdDateFormat20.withTimeZone(timeZone31);
        java.util.Calendar calendar34 = stdDateFormat12._getCalendar(timeZone31);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat35 = stdDateFormat3.withTimeZone(timeZone31);
        java.lang.String str36 = stdDateFormat3.toPattern();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat37 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat39 = stdDateFormat37.withColonInTimeZone(false);
        boolean boolean41 = stdDateFormat37.looksLikeISO8601("hi!");
        java.util.TimeZone timeZone42 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        stdDateFormat37.setTimeZone(timeZone42);
        java.lang.String str45 = stdDateFormat37.format((java.lang.Object) 0L);
        boolean boolean46 = stdDateFormat37.isColonIncludedInTimeZone();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat47 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat49 = stdDateFormat47.withColonInTimeZone(false);
        java.lang.Boolean boolean50 = stdDateFormat47._lenient;
        boolean boolean52 = stdDateFormat47.equals((java.lang.Object) (byte) 1);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat53 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat55 = stdDateFormat53.withColonInTimeZone(false);
        boolean boolean57 = stdDateFormat53.looksLikeISO8601("hi!");
        java.util.TimeZone timeZone58 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        stdDateFormat53.setTimeZone(timeZone58);
        stdDateFormat47.setTimeZone(timeZone58);
        stdDateFormat37._timezone = timeZone58;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat62 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat64 = stdDateFormat62.withColonInTimeZone(false);
        boolean boolean66 = stdDateFormat62.looksLikeISO8601("hi!");
        boolean boolean68 = stdDateFormat62.looksLikeISO8601("DateFormat com.fasterxml.jackson.databind.util.StdDateFormat: (timezone: null, locale: en_US, lenient: null)");
        java.util.Locale locale69 = stdDateFormat62._locale;
        java.text.DateFormat dateFormat70 = com.fasterxml.jackson.databind.util.StdDateFormat.getRFC1123Format(timeZone58, locale69);
        java.util.Calendar calendar71 = stdDateFormat3._getCalendar(timeZone58);
        stdDateFormat3._lenient = false;
        org.junit.Assert.assertTrue("Contract failed: compareTo-equals on calendar34 and calendar71", (calendar34.compareTo(calendar71) == 0) == calendar34.equals(calendar71));
    }

    @Test
    public void test7() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test7");
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat0 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat1 = stdDateFormat0.clone();
        java.lang.Boolean boolean2 = stdDateFormat0._lenient;
        boolean boolean3 = stdDateFormat0.isColonIncludedInTimeZone();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat4 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat6 = stdDateFormat4.withColonInTimeZone(false);
        boolean boolean8 = stdDateFormat4.looksLikeISO8601("hi!");
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat9 = stdDateFormat4.clone();
        stdDateFormat4._lenient = false;
        boolean boolean12 = stdDateFormat4.isColonIncludedInTimeZone();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat14 = stdDateFormat4.withLenient((java.lang.Boolean) false);
        java.util.TimeZone timeZone15 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.TimeZone timeZone17 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale18 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat20 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone17, locale18, (java.lang.Boolean) false);
        java.util.Locale locale21 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat23 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone17, locale21, (java.lang.Boolean) true);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat24 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat26 = stdDateFormat24.withColonInTimeZone(false);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat28 = stdDateFormat26.withColonInTimeZone(true);
        java.util.Locale locale29 = stdDateFormat28._locale;
        java.text.DateFormat dateFormat30 = com.fasterxml.jackson.databind.util.StdDateFormat.getRFC1123Format(timeZone17, locale29);
        java.text.DateFormat dateFormat31 = java.text.DateFormat.getTimeInstance(0, locale29);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat33 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone15, locale29, (java.lang.Boolean) false);
        java.util.TimeZone timeZone34 = stdDateFormat33.getTimeZone();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat35 = stdDateFormat14.withTimeZone(timeZone34);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat36 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat38 = stdDateFormat36.withColonInTimeZone(false);
        boolean boolean40 = stdDateFormat36.looksLikeISO8601("hi!");
        boolean boolean42 = stdDateFormat36.equals((java.lang.Object) 'a');
        java.util.TimeZone timeZone43 = stdDateFormat36._timezone;
        boolean boolean44 = stdDateFormat36.isColonIncludedInTimeZone();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat45 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat47 = stdDateFormat45.withColonInTimeZone(false);
        boolean boolean49 = stdDateFormat45.looksLikeISO8601("hi!");
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat50 = stdDateFormat45.clone();
        java.util.TimeZone timeZone51 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat52 = stdDateFormat45.withTimeZone(timeZone51);
        stdDateFormat36.setTimeZone(timeZone51);
        boolean boolean54 = stdDateFormat36.isColonIncludedInTimeZone();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat55 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat57 = stdDateFormat55.withColonInTimeZone(false);
        boolean boolean59 = stdDateFormat55.looksLikeISO8601("hi!");
        boolean boolean61 = stdDateFormat55.equals((java.lang.Object) 'a');
        java.util.TimeZone timeZone62 = stdDateFormat55._timezone;
        boolean boolean63 = stdDateFormat55.isColonIncludedInTimeZone();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat64 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat66 = stdDateFormat64.withColonInTimeZone(false);
        boolean boolean68 = stdDateFormat64.looksLikeISO8601("hi!");
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat69 = stdDateFormat64.clone();
        java.util.TimeZone timeZone70 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat71 = stdDateFormat64.withTimeZone(timeZone70);
        stdDateFormat55.setTimeZone(timeZone70);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat73 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat75 = stdDateFormat73.withColonInTimeZone(false);
        boolean boolean77 = stdDateFormat73.looksLikeISO8601("hi!");
        boolean boolean79 = stdDateFormat73.looksLikeISO8601("DateFormat com.fasterxml.jackson.databind.util.StdDateFormat: (timezone: null, locale: en_US, lenient: null)");
        java.util.Locale locale80 = stdDateFormat73._locale;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat82 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone70, locale80, (java.lang.Boolean) true);
        java.util.Calendar calendar83 = stdDateFormat36._getCalendar(timeZone70);
        java.util.Calendar calendar84 = stdDateFormat35._getCalendar(timeZone70);
        stdDateFormat0.setCalendar(calendar84);
        org.junit.Assert.assertTrue("Contract failed: compareTo-equals on calendar83 and calendar84", (calendar83.compareTo(calendar84) == 0) == calendar83.equals(calendar84));
    }

    @Test
    public void test8() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test8");
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat0 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat2 = stdDateFormat0.withColonInTimeZone(false);
        boolean boolean4 = stdDateFormat0.looksLikeISO8601("hi!");
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat5 = stdDateFormat0.clone();
        stdDateFormat0._lenient = false;
        boolean boolean8 = stdDateFormat0.isColonIncludedInTimeZone();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat10 = stdDateFormat0.withLenient((java.lang.Boolean) false);
        java.util.TimeZone timeZone11 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.TimeZone timeZone13 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        java.util.Locale locale14 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat16 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone13, locale14, (java.lang.Boolean) false);
        java.util.Locale locale17 = null;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat19 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone13, locale17, (java.lang.Boolean) true);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat20 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat22 = stdDateFormat20.withColonInTimeZone(false);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat24 = stdDateFormat22.withColonInTimeZone(true);
        java.util.Locale locale25 = stdDateFormat24._locale;
        java.text.DateFormat dateFormat26 = com.fasterxml.jackson.databind.util.StdDateFormat.getRFC1123Format(timeZone13, locale25);
        java.text.DateFormat dateFormat27 = java.text.DateFormat.getTimeInstance(0, locale25);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat29 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone11, locale25, (java.lang.Boolean) false);
        java.util.TimeZone timeZone30 = stdDateFormat29.getTimeZone();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat31 = stdDateFormat10.withTimeZone(timeZone30);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat32 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat34 = stdDateFormat32.withColonInTimeZone(false);
        boolean boolean36 = stdDateFormat32.looksLikeISO8601("hi!");
        boolean boolean38 = stdDateFormat32.equals((java.lang.Object) 'a');
        java.util.TimeZone timeZone39 = stdDateFormat32._timezone;
        boolean boolean40 = stdDateFormat32.isColonIncludedInTimeZone();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat41 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat43 = stdDateFormat41.withColonInTimeZone(false);
        boolean boolean45 = stdDateFormat41.looksLikeISO8601("hi!");
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat46 = stdDateFormat41.clone();
        java.util.TimeZone timeZone47 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat48 = stdDateFormat41.withTimeZone(timeZone47);
        stdDateFormat32.setTimeZone(timeZone47);
        boolean boolean50 = stdDateFormat32.isColonIncludedInTimeZone();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat51 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat53 = stdDateFormat51.withColonInTimeZone(false);
        boolean boolean55 = stdDateFormat51.looksLikeISO8601("hi!");
        boolean boolean57 = stdDateFormat51.equals((java.lang.Object) 'a');
        java.util.TimeZone timeZone58 = stdDateFormat51._timezone;
        boolean boolean59 = stdDateFormat51.isColonIncludedInTimeZone();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat60 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat62 = stdDateFormat60.withColonInTimeZone(false);
        boolean boolean64 = stdDateFormat60.looksLikeISO8601("hi!");
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat65 = stdDateFormat60.clone();
        java.util.TimeZone timeZone66 = com.fasterxml.jackson.databind.util.StdDateFormat.DEFAULT_TIMEZONE;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat67 = stdDateFormat60.withTimeZone(timeZone66);
        stdDateFormat51.setTimeZone(timeZone66);
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat69 = new com.fasterxml.jackson.databind.util.StdDateFormat();
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat71 = stdDateFormat69.withColonInTimeZone(false);
        boolean boolean73 = stdDateFormat69.looksLikeISO8601("hi!");
        boolean boolean75 = stdDateFormat69.looksLikeISO8601("DateFormat com.fasterxml.jackson.databind.util.StdDateFormat: (timezone: null, locale: en_US, lenient: null)");
        java.util.Locale locale76 = stdDateFormat69._locale;
        com.fasterxml.jackson.databind.util.StdDateFormat stdDateFormat78 = new com.fasterxml.jackson.databind.util.StdDateFormat(timeZone66, locale76, (java.lang.Boolean) true);
        java.util.Calendar calendar79 = stdDateFormat32._getCalendar(timeZone66);
        java.util.Calendar calendar80 = stdDateFormat31._getCalendar(timeZone66);
        java.lang.Class<?> wildcardClass81 = calendar80.getClass();
        org.junit.Assert.assertTrue("Contract failed: compareTo-equals on calendar79 and calendar80", (calendar79.compareTo(calendar80) == 0) == calendar79.equals(calendar80));
    }
}

