/*
 * This file was automatically generated by EvoSuite
 * Wed Sep 23 16:19:34 GMT 2026
 */

package com.fasterxml.jackson.core.json;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.json.DupDetector;
import com.fasterxml.jackson.core.json.JsonWriteContext;
import java.io.IOException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class JsonWriteContext_ESTest extends JsonWriteContext_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      JsonWriteContext jsonWriteContext0 = JsonWriteContext.createRootContext();
      JsonWriteContext jsonWriteContext1 = jsonWriteContext0.createChildArrayContext();
      String string0 = jsonWriteContext1.toString();
      assertEquals("[0]", string0);
      assertEquals(0, jsonWriteContext1.getEntryCount());
      assertEquals("ROOT", jsonWriteContext0.getTypeDesc());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      JsonWriteContext jsonWriteContext0 = JsonWriteContext.createRootContext(dupDetector0);
      JsonWriteContext jsonWriteContext1 = jsonWriteContext0.createChildObjectContext();
      int int0 = jsonWriteContext1.writeFieldName("/");
      assertEquals(0, int0);
      
      String string0 = jsonWriteContext1.toString();
      assertEquals(0, jsonWriteContext1.getEntryCount());
      assertTrue(jsonWriteContext0.inRoot());
      assertEquals("{\"/\"}", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      JsonWriteContext jsonWriteContext0 = new JsonWriteContext(0, (JsonWriteContext) null, dupDetector0);
      JsonWriteContext jsonWriteContext1 = jsonWriteContext0.createChildObjectContext();
      String string0 = jsonWriteContext1.toString();
      assertFalse(jsonWriteContext0.inObject());
      assertEquals("{?}", string0);
      assertEquals(0, jsonWriteContext1.getEntryCount());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      JsonWriteContext jsonWriteContext0 = JsonWriteContext.createRootContext((DupDetector) null);
      jsonWriteContext0.writeValue();
      int int0 = jsonWriteContext0.writeValue();
      assertEquals(1, jsonWriteContext0.getCurrentIndex());
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      DupDetector dupDetector1 = dupDetector0.child();
      dupDetector1._secondName = " (from ";
      JsonWriteContext jsonWriteContext0 = JsonWriteContext.createRootContext(dupDetector1);
      jsonWriteContext0.writeFieldName("U @U?iai}BI");
      JsonWriteContext jsonWriteContext1 = new JsonWriteContext(2, jsonWriteContext0, dupDetector1);
      try { 
        jsonWriteContext1.writeFieldName(" (from ");
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Duplicate field ' (from '
         //
         verifyException("com.fasterxml.jackson.core.json.JsonWriteContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      JsonWriteContext jsonWriteContext0 = JsonWriteContext.createRootContext();
      jsonWriteContext0.writeValue();
      int int0 = jsonWriteContext0.writeFieldName("Parser of type ");
      assertEquals(1, jsonWriteContext0.getEntryCount());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      JsonWriteContext jsonWriteContext0 = JsonWriteContext.createRootContext();
      JsonWriteContext jsonWriteContext1 = jsonWriteContext0.createChildArrayContext();
      jsonWriteContext1._child = jsonWriteContext0;
      int int0 = jsonWriteContext0.writeFieldName("/");
      assertEquals(0, int0);
      
      int int1 = jsonWriteContext1._child.writeFieldName("/");
      assertEquals(0, jsonWriteContext1.getEntryCount());
      assertTrue(jsonWriteContext1.inArray());
      assertEquals(4, int1);
      assertEquals("ROOT", jsonWriteContext0.getTypeDesc());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      JsonWriteContext jsonWriteContext0 = JsonWriteContext.createRootContext(dupDetector0);
      JsonWriteContext jsonWriteContext1 = jsonWriteContext0.createChildObjectContext();
      int int0 = jsonWriteContext1.writeValue();
      assertEquals(1, jsonWriteContext1.getEntryCount());
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      JsonWriteContext jsonWriteContext0 = JsonWriteContext.createRootContext(dupDetector0);
      JsonWriteContext jsonWriteContext1 = jsonWriteContext0.createChildArrayContext();
      assertNotNull(jsonWriteContext1);
      
      int int0 = jsonWriteContext1.writeValue();
      assertEquals(1, jsonWriteContext1.getEntryCount());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      JsonWriteContext jsonWriteContext0 = JsonWriteContext.createRootContext(dupDetector0);
      JsonWriteContext jsonWriteContext1 = jsonWriteContext0.reset((-1));
      jsonWriteContext1._child = jsonWriteContext0;
      JsonWriteContext jsonWriteContext2 = jsonWriteContext0.createChildArrayContext();
      jsonWriteContext2.writeValue();
      int int0 = jsonWriteContext1.writeValue();
      assertEquals(1, jsonWriteContext1.getCurrentIndex());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      JsonWriteContext jsonWriteContext0 = JsonWriteContext.createRootContext((DupDetector) null);
      JsonWriteContext jsonWriteContext1 = jsonWriteContext0.createChildObjectContext();
      jsonWriteContext1._child = jsonWriteContext0;
      assertFalse(jsonWriteContext1._child.inArray());
      
      jsonWriteContext1.createChildArrayContext();
      assertEquals("ARRAY", jsonWriteContext0.getTypeDesc());
      assertEquals(0, jsonWriteContext1.getEntryCount());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      JsonWriteContext jsonWriteContext0 = JsonWriteContext.createRootContext((DupDetector) null);
      JsonWriteContext jsonWriteContext1 = jsonWriteContext0.withDupDetector((DupDetector) null);
      assertEquals(0, jsonWriteContext1.getEntryCount());
      assertEquals("ROOT", jsonWriteContext1.getTypeDesc());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      JsonWriteContext jsonWriteContext0 = JsonWriteContext.createRootContext(dupDetector0);
      jsonWriteContext0.getCurrentValue();
      assertEquals("ROOT", jsonWriteContext0.getTypeDesc());
      assertEquals(0, jsonWriteContext0.getEntryCount());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      JsonWriteContext jsonWriteContext0 = JsonWriteContext.createRootContext((DupDetector) null);
      JsonWriteContext jsonWriteContext1 = jsonWriteContext0.getParent();
      assertEquals(0, jsonWriteContext0.getEntryCount());
      assertTrue(jsonWriteContext0.inRoot());
      assertNull(jsonWriteContext1);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      JsonWriteContext jsonWriteContext0 = JsonWriteContext.createRootContext();
      JsonWriteContext jsonWriteContext1 = jsonWriteContext0.createChildArrayContext();
      assertTrue(jsonWriteContext1.inArray());
      assertNotNull(jsonWriteContext1);
      
      JsonWriteContext jsonWriteContext2 = jsonWriteContext0.createChildObjectContext();
      assertEquals(0, jsonWriteContext0.getEntryCount());
      assertFalse(jsonWriteContext0.inArray());
      assertSame(jsonWriteContext2, jsonWriteContext1);
      assertTrue(jsonWriteContext2.inObject());
      assertEquals(0, jsonWriteContext2.getEntryCount());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      JsonWriteContext jsonWriteContext0 = JsonWriteContext.createRootContext(dupDetector0);
      String string0 = jsonWriteContext0.toString();
      assertEquals(0, jsonWriteContext0.getEntryCount());
      assertEquals("/", string0);
      assertEquals("ROOT", jsonWriteContext0.getTypeDesc());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      JsonWriteContext jsonWriteContext0 = JsonWriteContext.createRootContext(dupDetector0);
      jsonWriteContext0.setCurrentValue((Object) null);
      assertTrue(jsonWriteContext0.inRoot());
      assertEquals(0, jsonWriteContext0.getEntryCount());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      JsonWriteContext jsonWriteContext0 = JsonWriteContext.createRootContext(dupDetector0);
      DupDetector dupDetector1 = jsonWriteContext0.getDupDetector();
      assertNotNull(dupDetector1);
      assertEquals("ROOT", jsonWriteContext0.getTypeDesc());
      assertEquals(0, jsonWriteContext0.getEntryCount());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      DupDetector dupDetector0 = DupDetector.rootDetector((JsonGenerator) null);
      JsonWriteContext jsonWriteContext0 = JsonWriteContext.createRootContext(dupDetector0);
      jsonWriteContext0.getCurrentName();
      assertTrue(jsonWriteContext0.inRoot());
      assertEquals(0, jsonWriteContext0.getEntryCount());
  }
}
