/*
 * This file was automatically generated by EvoSuite
 * Sun Sep 20 18:07:51 GMT 2026
 */

package org.jfree.data.statistics;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Stack;
import java.util.Vector;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jfree.data.Range;
import org.jfree.data.statistics.BoxAndWhiskerItem;
import org.jfree.data.statistics.DefaultBoxAndWhiskerCategoryDataset;
import org.jfree.data.time.FixedMillisecond;
import org.jfree.data.time.Hour;
import org.jfree.data.time.Minute;
import org.jfree.data.time.Month;
import org.jfree.data.time.RegularTimePeriod;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DefaultBoxAndWhiskerCategoryDataset_ESTest extends DefaultBoxAndWhiskerCategoryDataset_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      FixedMillisecond fixedMillisecond0 = new FixedMillisecond();
      // Undeclared exception!
      try { 
        defaultBoxAndWhiskerCategoryDataset0.getQ1Value((Comparable) fixedMillisecond0, (Comparable) fixedMillisecond0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Row key (Fri Feb 14 20:21:21 GMT 2014) not recognised.
         //
         verifyException("org.jfree.data.KeyedObjects2D", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      // Undeclared exception!
      try { 
        defaultBoxAndWhiskerCategoryDataset0.getOutliers(3952, 3952);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      boolean boolean0 = defaultBoxAndWhiskerCategoryDataset0.equals(defaultBoxAndWhiskerCategoryDataset0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      Object object0 = new Object();
      boolean boolean0 = defaultBoxAndWhiskerCategoryDataset0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) hour0, (Comparable) hour0);
      List list0 = defaultBoxAndWhiskerCategoryDataset0.getOutliers((Comparable) hour0, (Comparable) hour0);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      Minute minute0 = new Minute(0, hour0);
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) hour0, (Comparable) hour0);
      defaultBoxAndWhiskerCategoryDataset0.add((List) arrayList0, (Comparable) minute0, (Comparable) hour0);
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getMaxOutlier((Comparable) minute0, (Comparable) hour0);
      assertEquals(Double.NEGATIVE_INFINITY, number0);
      assertNotNull(number0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) hour0, (Comparable) hour0);
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getMaxOutlier(0, 0);
      assertEquals(23, number0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      RegularTimePeriod regularTimePeriod0 = hour0.previous();
      Minute minute0 = new Minute(0, hour0);
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) regularTimePeriod0, (Comparable) regularTimePeriod0);
      defaultBoxAndWhiskerCategoryDataset0.add((List) arrayList0, (Comparable) minute0, (Comparable) hour0);
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getMaxOutlier(1, 0);
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      Minute minute0 = new Minute(0, hour0);
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) hour0, (Comparable) hour0);
      defaultBoxAndWhiskerCategoryDataset0.add((List) arrayList0, (Comparable) minute0, (Comparable) hour0);
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getMinOutlier(1, 0);
      assertEquals(Double.POSITIVE_INFINITY, number0);
      assertNotNull(number0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Month month0 = new Month();
      Stack<BoxAndWhiskerItem> stack0 = new Stack<BoxAndWhiskerItem>();
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((-2492.695077899272), 1261.55917, (double) (-604), (double) 1600, 1261.55917, (double) (-405), 58.72882846812588, 59.0, (List) stack0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) month0, (Comparable) month0);
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getMaxRegularValue((Comparable) month0, (Comparable) month0);
      assertEquals((-405.0), number0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      Minute minute0 = new Minute(0, hour0);
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) hour0, (Comparable) hour0);
      defaultBoxAndWhiskerCategoryDataset0.add((List) arrayList0, (Comparable) minute0, (Comparable) "Fri Feb 14 20:21:21 GMT 2014");
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getMaxRegularValue(1, 1);
      assertEquals(Double.NEGATIVE_INFINITY, number0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      Minute minute0 = new Minute(0, hour0);
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) hour0, (Comparable) hour0);
      defaultBoxAndWhiskerCategoryDataset0.add((List) arrayList0, (Comparable) hour0, (Comparable) "Fri Feb 14 20:21:21 GMT 2014");
      defaultBoxAndWhiskerCategoryDataset0.add((List) arrayList0, (Comparable) minute0, (Comparable) hour0);
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getMaxRegularValue(1, 1);
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Month month0 = new Month();
      Stack<BoxAndWhiskerItem> stack0 = new Stack<BoxAndWhiskerItem>();
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((-2492.695077899272), 1261.55917, (double) (-604), (double) 1600, 1261.55917, (double) (-405), 58.72882846812588, 59.0, (List) stack0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) month0, (Comparable) month0);
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getMinRegularValue((Comparable) month0, (Comparable) month0);
      assertEquals(1261.55917, number0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      Minute minute0 = new Minute(0, hour0);
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) hour0, (Comparable) hour0);
      defaultBoxAndWhiskerCategoryDataset0.add((List) arrayList0, (Comparable) minute0, (Comparable) hour0);
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getMinRegularValue(1, 0);
      assertEquals(Double.POSITIVE_INFINITY, number0);
      assertNotNull(number0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      Minute minute0 = new Minute(0, hour0);
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) hour0, (Comparable) hour0);
      defaultBoxAndWhiskerCategoryDataset0.add((List) arrayList0, (Comparable) minute0, (Comparable) hour0);
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getQ3Value((Comparable) minute0, (Comparable) hour0);
      assertEquals(Double.NaN, number0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      Minute minute0 = new Minute(0, hour0);
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) hour0, (Comparable) hour0);
      List list0 = boxAndWhiskerItem0.getOutliers();
      defaultBoxAndWhiskerCategoryDataset0.add((List) list0, (Comparable) minute0, (Comparable) minute0);
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getQ3Value((Comparable) hour0, (Comparable) minute0);
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) hour0, (Comparable) hour0);
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getQ3Value(0, 0);
      assertEquals(59, number0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      RegularTimePeriod regularTimePeriod0 = hour0.previous();
      Minute minute0 = new Minute(0, hour0);
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) regularTimePeriod0, (Comparable) regularTimePeriod0);
      defaultBoxAndWhiskerCategoryDataset0.add((List) arrayList0, (Comparable) minute0, (Comparable) hour0);
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getQ3Value(0, 1);
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) hour0, (Comparable) hour0);
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getQ1Value(0, 0);
      assertEquals(0, number0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      Minute minute0 = new Minute(0, hour0);
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) hour0, (Comparable) hour0);
      defaultBoxAndWhiskerCategoryDataset0.add((List) arrayList0, (Comparable) minute0, (Comparable) "Fri Feb 14 20:21:21 GMT 2014");
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getQ1Value(0, 1);
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      Minute minute0 = new Minute(0, hour0);
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) hour0, (Comparable) hour0);
      defaultBoxAndWhiskerCategoryDataset0.add((List) arrayList0, (Comparable) minute0, (Comparable) hour0);
      Double double0 = (Double)defaultBoxAndWhiskerCategoryDataset0.getValue((Comparable) minute0, (Comparable) hour0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) "Fri Feb 14 20:21:21 GMT 2014", (Comparable) double0);
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getMinOutlier((Comparable) minute0, (Comparable) double0);
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      Minute minute0 = new Minute(0, hour0);
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) hour0, (Comparable) hour0);
      defaultBoxAndWhiskerCategoryDataset0.add((List) arrayList0, (Comparable) minute0, (Comparable) "Fri Feb 14 20:21:21 GMT 2014");
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getMedianValue((Comparable) hour0, (Comparable) "Fri Feb 14 20:21:21 GMT 2014");
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      Minute minute0 = new Minute(0, hour0);
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) hour0, (Comparable) hour0);
      defaultBoxAndWhiskerCategoryDataset0.add((List) arrayList0, (Comparable) minute0, (Comparable) hour0);
      assertEquals(2, defaultBoxAndWhiskerCategoryDataset0.getRowCount());
      
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getMedianValue(1, 0);
      assertEquals(Double.NaN, number0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      RegularTimePeriod regularTimePeriod0 = hour0.previous();
      Minute minute0 = new Minute(0, hour0);
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) regularTimePeriod0, (Comparable) regularTimePeriod0);
      defaultBoxAndWhiskerCategoryDataset0.add((List) arrayList0, (Comparable) minute0, (Comparable) hour0);
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getMedianValue(1, 0);
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) hour0, (Comparable) hour0);
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getMeanValue((Comparable) hour0, (Comparable) hour0);
      assertEquals(0, number0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      RegularTimePeriod regularTimePeriod0 = hour0.previous();
      Minute minute0 = new Minute(0, hour0);
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) regularTimePeriod0, (Comparable) regularTimePeriod0);
      defaultBoxAndWhiskerCategoryDataset0.add((List) arrayList0, (Comparable) minute0, (Comparable) hour0);
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getMeanValue((Comparable) regularTimePeriod0, (Comparable) hour0);
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) hour0, (Comparable) hour0);
      Number number0 = defaultBoxAndWhiskerCategoryDataset0.getMeanValue(0, 0);
      assertEquals(0, number0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      BigInteger bigInteger0 = BigInteger.ONE;
      Vector<BoxAndWhiskerItem> vector0 = new Vector<BoxAndWhiskerItem>();
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) null, (Number) null, (Number) null, (Number) null, (Number) null, (Number) null, (Number) null, bigInteger0, vector0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) bigInteger0, (Comparable) bigInteger0);
      assertEquals((byte)1, bigInteger0.byteValue());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      // Undeclared exception!
      try { 
        defaultBoxAndWhiskerCategoryDataset0.getItem(0, 446);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      Object object0 = defaultBoxAndWhiskerCategoryDataset0.clone();
      boolean boolean0 = defaultBoxAndWhiskerCategoryDataset0.equals(object0);
      assertTrue(boolean0);
      assertNotSame(object0, defaultBoxAndWhiskerCategoryDataset0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      double double0 = defaultBoxAndWhiskerCategoryDataset0.getRangeUpperBound(false);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      // Undeclared exception!
      try { 
        defaultBoxAndWhiskerCategoryDataset0.getColumnKey(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      int int0 = defaultBoxAndWhiskerCategoryDataset0.getColumnCount();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      Range range0 = defaultBoxAndWhiskerCategoryDataset0.getRangeBounds(true);
      assertEquals(0.0, range0.getLength(), 0.01);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      // Undeclared exception!
      try { 
        defaultBoxAndWhiskerCategoryDataset0.getValue((-1994), 852);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      List list0 = defaultBoxAndWhiskerCategoryDataset0.getRowKeys();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      List list0 = defaultBoxAndWhiskerCategoryDataset0.getColumnKeys();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      int int0 = defaultBoxAndWhiskerCategoryDataset0.getRowCount();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      double double0 = defaultBoxAndWhiskerCategoryDataset0.getRangeLowerBound(true);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      // Undeclared exception!
      try { 
        defaultBoxAndWhiskerCategoryDataset0.getRowKey((-703));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      Hour hour0 = new Hour();
      int int0 = defaultBoxAndWhiskerCategoryDataset0.getRowIndex(hour0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      int int0 = defaultBoxAndWhiskerCategoryDataset0.getColumnIndex((Comparable) null);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      DefaultBoxAndWhiskerCategoryDataset defaultBoxAndWhiskerCategoryDataset0 = new DefaultBoxAndWhiskerCategoryDataset();
      ArrayList<Locale> arrayList0 = new ArrayList<Locale>();
      Hour hour0 = new Hour();
      BoxAndWhiskerItem boxAndWhiskerItem0 = new BoxAndWhiskerItem((Number) 0, (Number) 0, (Number) 0, (Number) 59, (Number) 59, (Number) 0, (Number) 23, (Number) 23, (List) arrayList0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) hour0, (Comparable) hour0);
      defaultBoxAndWhiskerCategoryDataset0.add(boxAndWhiskerItem0, (Comparable) hour0, (Comparable) hour0);
      assertEquals(23, Hour.LAST_HOUR_IN_DAY);
  }
}
