package org.apache.commons.math3.distribution;

import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RegressionTest3 {

    public static boolean debug = false;

    public void assertBooleanArrayEquals(boolean[] expectedArray, boolean[] actualArray) {
        if (expectedArray.length != actualArray.length) {
            throw new AssertionError("Array lengths differ: " + expectedArray.length + " != " + actualArray.length);
        }
        for (int i = 0; i < expectedArray.length; i++) {
            if (expectedArray[i] != actualArray[i]) {
                throw new AssertionError("Arrays differ at index " + i + ": " + expectedArray[i] + " != " + actualArray[i]);
            }
        }
    }

    @Test
    public void test1501() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest3.test1501");
        org.apache.commons.math3.random.RandomGenerator randomGenerator0 = null;
        org.apache.commons.math3.random.RandomGenerator randomGenerator1 = null;
        double[] doubleArray3 = new double[] { 1 };
        double[] doubleArray5 = new double[] { 10L };
        double[][] doubleArray6 = new double[][] { doubleArray5 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution7 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator1, doubleArray3, doubleArray6);
        double[] doubleArray8 = multivariateNormalDistribution7.getMeans();
        org.apache.commons.math3.random.RandomGenerator randomGenerator9 = null;
        double[] doubleArray11 = new double[] { 1 };
        double[] doubleArray13 = new double[] { 10L };
        double[][] doubleArray14 = new double[][] { doubleArray13 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution15 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator9, doubleArray11, doubleArray14);
        org.apache.commons.math3.random.RandomGenerator randomGenerator16 = null;
        double[] doubleArray18 = new double[] { 1 };
        double[] doubleArray20 = new double[] { 10L };
        double[][] doubleArray21 = new double[][] { doubleArray20 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution22 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator16, doubleArray18, doubleArray21);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution23 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray11, doubleArray21);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution24 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray8, doubleArray21);
        int int25 = multivariateNormalDistribution24.getDimension();
        double[] doubleArray26 = multivariateNormalDistribution24.getStandardDeviations();
        org.apache.commons.math3.random.RandomGenerator randomGenerator27 = null;
        org.apache.commons.math3.random.RandomGenerator randomGenerator28 = null;
        org.apache.commons.math3.random.RandomGenerator randomGenerator29 = null;
        org.apache.commons.math3.random.RandomGenerator randomGenerator30 = null;
        double[] doubleArray32 = new double[] { 1 };
        double[] doubleArray34 = new double[] { 10L };
        double[][] doubleArray35 = new double[][] { doubleArray34 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution36 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator30, doubleArray32, doubleArray35);
        double[] doubleArray37 = multivariateNormalDistribution36.getMeans();
        org.apache.commons.math3.random.RandomGenerator randomGenerator38 = null;
        double[] doubleArray40 = new double[] { 1 };
        double[] doubleArray42 = new double[] { 10L };
        double[][] doubleArray43 = new double[][] { doubleArray42 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution44 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator38, doubleArray40, doubleArray43);
        org.apache.commons.math3.random.RandomGenerator randomGenerator45 = null;
        double[] doubleArray47 = new double[] { 1 };
        double[] doubleArray49 = new double[] { 10L };
        double[][] doubleArray50 = new double[][] { doubleArray49 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution51 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator45, doubleArray47, doubleArray50);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution52 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray40, doubleArray50);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution53 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator29, doubleArray37, doubleArray50);
        org.apache.commons.math3.random.RandomGenerator randomGenerator54 = null;
        double[] doubleArray56 = new double[] { 1 };
        double[] doubleArray58 = new double[] { 10L };
        double[][] doubleArray59 = new double[][] { doubleArray58 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution60 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator54, doubleArray56, doubleArray59);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution61 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator28, doubleArray37, doubleArray59);
        int int62 = multivariateNormalDistribution61.getDimension();
        double[] doubleArray63 = multivariateNormalDistribution61.getMeans();
        org.apache.commons.math3.random.RandomGenerator randomGenerator64 = null;
        org.apache.commons.math3.random.RandomGenerator randomGenerator65 = null;
        double[] doubleArray67 = new double[] { 1 };
        double[] doubleArray69 = new double[] { 10L };
        double[][] doubleArray70 = new double[][] { doubleArray69 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution71 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator65, doubleArray67, doubleArray70);
        double[] doubleArray72 = multivariateNormalDistribution71.getMeans();
        org.apache.commons.math3.random.RandomGenerator randomGenerator73 = null;
        double[] doubleArray75 = new double[] { 1 };
        double[] doubleArray77 = new double[] { 10L };
        double[][] doubleArray78 = new double[][] { doubleArray77 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution79 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator73, doubleArray75, doubleArray78);
        org.apache.commons.math3.random.RandomGenerator randomGenerator80 = null;
        double[] doubleArray82 = new double[] { 1 };
        double[] doubleArray84 = new double[] { 10L };
        double[][] doubleArray85 = new double[][] { doubleArray84 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution86 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator80, doubleArray82, doubleArray85);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution87 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray75, doubleArray85);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution88 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator64, doubleArray72, doubleArray85);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution89 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator27, doubleArray63, doubleArray85);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution90 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator0, doubleArray26, doubleArray85);
        int int91 = multivariateNormalDistribution90.getDimension();
        org.junit.Assert.assertNotNull(doubleArray3);
        org.junit.Assert.assertArrayEquals(doubleArray3, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray5);
        org.junit.Assert.assertArrayEquals(doubleArray5, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray6);
        org.junit.Assert.assertNotNull(doubleArray8);
        org.junit.Assert.assertArrayEquals(doubleArray8, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray11);
        org.junit.Assert.assertArrayEquals(doubleArray11, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray13);
        org.junit.Assert.assertArrayEquals(doubleArray13, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray14);
        org.junit.Assert.assertNotNull(doubleArray18);
        org.junit.Assert.assertArrayEquals(doubleArray18, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray20);
        org.junit.Assert.assertArrayEquals(doubleArray20, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray21);
        org.junit.Assert.assertTrue("'" + int25 + "' != '" + 1 + "'", int25 == 1);
        org.junit.Assert.assertNotNull(doubleArray26);
        org.junit.Assert.assertArrayEquals(doubleArray26, new double[] { 3.1622776601683795d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray32);
        org.junit.Assert.assertArrayEquals(doubleArray32, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray34);
        org.junit.Assert.assertArrayEquals(doubleArray34, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray35);
        org.junit.Assert.assertNotNull(doubleArray37);
        org.junit.Assert.assertArrayEquals(doubleArray37, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray40);
        org.junit.Assert.assertArrayEquals(doubleArray40, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray42);
        org.junit.Assert.assertArrayEquals(doubleArray42, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray43);
        org.junit.Assert.assertNotNull(doubleArray47);
        org.junit.Assert.assertArrayEquals(doubleArray47, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray49);
        org.junit.Assert.assertArrayEquals(doubleArray49, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray50);
        org.junit.Assert.assertNotNull(doubleArray56);
        org.junit.Assert.assertArrayEquals(doubleArray56, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray58);
        org.junit.Assert.assertArrayEquals(doubleArray58, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray59);
        org.junit.Assert.assertTrue("'" + int62 + "' != '" + 1 + "'", int62 == 1);
        org.junit.Assert.assertNotNull(doubleArray63);
        org.junit.Assert.assertArrayEquals(doubleArray63, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray67);
        org.junit.Assert.assertArrayEquals(doubleArray67, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray69);
        org.junit.Assert.assertArrayEquals(doubleArray69, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray70);
        org.junit.Assert.assertNotNull(doubleArray72);
        org.junit.Assert.assertArrayEquals(doubleArray72, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray75);
        org.junit.Assert.assertArrayEquals(doubleArray75, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray77);
        org.junit.Assert.assertArrayEquals(doubleArray77, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray78);
        org.junit.Assert.assertNotNull(doubleArray82);
        org.junit.Assert.assertArrayEquals(doubleArray82, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray84);
        org.junit.Assert.assertArrayEquals(doubleArray84, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray85);
        org.junit.Assert.assertTrue("'" + int91 + "' != '" + 1 + "'", int91 == 1);
    }

    @Test
    public void test1502() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest3.test1502");
        org.apache.commons.math3.random.RandomGenerator randomGenerator0 = null;
        double[] doubleArray2 = new double[] { 1 };
        double[] doubleArray4 = new double[] { 10L };
        double[][] doubleArray5 = new double[][] { doubleArray4 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution6 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator0, doubleArray2, doubleArray5);
        org.apache.commons.math3.random.RandomGenerator randomGenerator7 = null;
        double[] doubleArray9 = new double[] { 1 };
        double[] doubleArray11 = new double[] { 10L };
        double[][] doubleArray12 = new double[][] { doubleArray11 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution13 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator7, doubleArray9, doubleArray12);
        double[] doubleArray14 = multivariateNormalDistribution13.getMeans();
        double double15 = multivariateNormalDistribution6.density(doubleArray14);
        int int16 = multivariateNormalDistribution6.getDimension();
        double[] doubleArray17 = multivariateNormalDistribution6.getMeans();
        org.apache.commons.math3.random.RandomGenerator randomGenerator18 = null;
        double[] doubleArray20 = new double[] { 1 };
        double[] doubleArray22 = new double[] { 10L };
        double[][] doubleArray23 = new double[][] { doubleArray22 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution24 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator18, doubleArray20, doubleArray23);
        org.apache.commons.math3.random.RandomGenerator randomGenerator25 = null;
        double[] doubleArray27 = new double[] { 1 };
        double[] doubleArray29 = new double[] { 10L };
        double[][] doubleArray30 = new double[][] { doubleArray29 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution31 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator25, doubleArray27, doubleArray30);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution32 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray20, doubleArray30);
        org.apache.commons.math3.random.RandomGenerator randomGenerator33 = null;
        org.apache.commons.math3.random.RandomGenerator randomGenerator34 = null;
        double[] doubleArray36 = new double[] { 1 };
        double[] doubleArray38 = new double[] { 10L };
        double[][] doubleArray39 = new double[][] { doubleArray38 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution40 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator34, doubleArray36, doubleArray39);
        double[] doubleArray41 = multivariateNormalDistribution40.getMeans();
        org.apache.commons.math3.random.RandomGenerator randomGenerator42 = null;
        double[] doubleArray44 = new double[] { 1 };
        double[] doubleArray46 = new double[] { 10L };
        double[][] doubleArray47 = new double[][] { doubleArray46 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution48 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator42, doubleArray44, doubleArray47);
        org.apache.commons.math3.random.RandomGenerator randomGenerator49 = null;
        double[] doubleArray51 = new double[] { 1 };
        double[] doubleArray53 = new double[] { 10L };
        double[][] doubleArray54 = new double[][] { doubleArray53 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution55 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator49, doubleArray51, doubleArray54);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution56 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray44, doubleArray54);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution57 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray41, doubleArray54);
        org.apache.commons.math3.random.RandomGenerator randomGenerator58 = null;
        double[] doubleArray60 = new double[] { 1 };
        double[] doubleArray62 = new double[] { 10L };
        double[][] doubleArray63 = new double[][] { doubleArray62 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution64 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator58, doubleArray60, doubleArray63);
        org.apache.commons.math3.random.RandomGenerator randomGenerator65 = null;
        org.apache.commons.math3.random.RandomGenerator randomGenerator66 = null;
        double[] doubleArray68 = new double[] { 1 };
        double[] doubleArray70 = new double[] { 10L };
        double[][] doubleArray71 = new double[][] { doubleArray70 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution72 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator66, doubleArray68, doubleArray71);
        double[] doubleArray73 = multivariateNormalDistribution72.getMeans();
        org.apache.commons.math3.random.RandomGenerator randomGenerator74 = null;
        double[] doubleArray76 = new double[] { 1 };
        double[] doubleArray78 = new double[] { 10L };
        double[][] doubleArray79 = new double[][] { doubleArray78 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution80 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator74, doubleArray76, doubleArray79);
        org.apache.commons.math3.random.RandomGenerator randomGenerator81 = null;
        double[] doubleArray83 = new double[] { 1 };
        double[] doubleArray85 = new double[] { 10L };
        double[][] doubleArray86 = new double[][] { doubleArray85 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution87 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator81, doubleArray83, doubleArray86);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution88 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray76, doubleArray86);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution89 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator65, doubleArray73, doubleArray86);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution90 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray60, doubleArray86);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution91 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator33, doubleArray41, doubleArray86);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution92 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray20, doubleArray86);
        multivariateNormalDistribution92.reseedRandomGenerator((long) (short) -1);
        double[] doubleArray95 = multivariateNormalDistribution92.getMeans();
        double double96 = multivariateNormalDistribution6.density(doubleArray95);
        org.junit.Assert.assertNotNull(doubleArray2);
        org.junit.Assert.assertArrayEquals(doubleArray2, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray4);
        org.junit.Assert.assertArrayEquals(doubleArray4, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray5);
        org.junit.Assert.assertNotNull(doubleArray9);
        org.junit.Assert.assertArrayEquals(doubleArray9, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray11);
        org.junit.Assert.assertArrayEquals(doubleArray11, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray12);
        org.junit.Assert.assertNotNull(doubleArray14);
        org.junit.Assert.assertArrayEquals(doubleArray14, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertTrue("'" + double15 + "' != '" + 0.31622776601683794d + "'", double15 == 0.31622776601683794d);
        org.junit.Assert.assertTrue("'" + int16 + "' != '" + 1 + "'", int16 == 1);
        org.junit.Assert.assertNotNull(doubleArray17);
        org.junit.Assert.assertArrayEquals(doubleArray17, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray20);
        org.junit.Assert.assertArrayEquals(doubleArray20, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray22);
        org.junit.Assert.assertArrayEquals(doubleArray22, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray23);
        org.junit.Assert.assertNotNull(doubleArray27);
        org.junit.Assert.assertArrayEquals(doubleArray27, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray29);
        org.junit.Assert.assertArrayEquals(doubleArray29, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray30);
        org.junit.Assert.assertNotNull(doubleArray36);
        org.junit.Assert.assertArrayEquals(doubleArray36, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray38);
        org.junit.Assert.assertArrayEquals(doubleArray38, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray39);
        org.junit.Assert.assertNotNull(doubleArray41);
        org.junit.Assert.assertArrayEquals(doubleArray41, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray44);
        org.junit.Assert.assertArrayEquals(doubleArray44, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray46);
        org.junit.Assert.assertArrayEquals(doubleArray46, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray47);
        org.junit.Assert.assertNotNull(doubleArray51);
        org.junit.Assert.assertArrayEquals(doubleArray51, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray53);
        org.junit.Assert.assertArrayEquals(doubleArray53, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray54);
        org.junit.Assert.assertNotNull(doubleArray60);
        org.junit.Assert.assertArrayEquals(doubleArray60, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray62);
        org.junit.Assert.assertArrayEquals(doubleArray62, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray63);
        org.junit.Assert.assertNotNull(doubleArray68);
        org.junit.Assert.assertArrayEquals(doubleArray68, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray70);
        org.junit.Assert.assertArrayEquals(doubleArray70, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray71);
        org.junit.Assert.assertNotNull(doubleArray73);
        org.junit.Assert.assertArrayEquals(doubleArray73, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray76);
        org.junit.Assert.assertArrayEquals(doubleArray76, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray78);
        org.junit.Assert.assertArrayEquals(doubleArray78, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray79);
        org.junit.Assert.assertNotNull(doubleArray83);
        org.junit.Assert.assertArrayEquals(doubleArray83, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray85);
        org.junit.Assert.assertArrayEquals(doubleArray85, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray86);
        org.junit.Assert.assertNotNull(doubleArray95);
        org.junit.Assert.assertArrayEquals(doubleArray95, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertTrue("'" + double96 + "' != '" + 0.31622776601683794d + "'", double96 == 0.31622776601683794d);
    }

    @Test
    public void test1503() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest3.test1503");
        org.apache.commons.math3.random.RandomGenerator randomGenerator0 = null;
        double[] doubleArray2 = new double[] { 1 };
        double[] doubleArray4 = new double[] { 10L };
        double[][] doubleArray5 = new double[][] { doubleArray4 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution6 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator0, doubleArray2, doubleArray5);
        org.apache.commons.math3.random.RandomGenerator randomGenerator7 = null;
        double[] doubleArray9 = new double[] { 1 };
        double[] doubleArray11 = new double[] { 10L };
        double[][] doubleArray12 = new double[][] { doubleArray11 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution13 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator7, doubleArray9, doubleArray12);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution14 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray2, doubleArray12);
        org.apache.commons.math3.random.RandomGenerator randomGenerator15 = null;
        org.apache.commons.math3.random.RandomGenerator randomGenerator16 = null;
        double[] doubleArray18 = new double[] { 1 };
        double[] doubleArray20 = new double[] { 10L };
        double[][] doubleArray21 = new double[][] { doubleArray20 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution22 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator16, doubleArray18, doubleArray21);
        double[] doubleArray23 = multivariateNormalDistribution22.getMeans();
        org.apache.commons.math3.random.RandomGenerator randomGenerator24 = null;
        double[] doubleArray26 = new double[] { 1 };
        double[] doubleArray28 = new double[] { 10L };
        double[][] doubleArray29 = new double[][] { doubleArray28 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution30 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator24, doubleArray26, doubleArray29);
        org.apache.commons.math3.random.RandomGenerator randomGenerator31 = null;
        double[] doubleArray33 = new double[] { 1 };
        double[] doubleArray35 = new double[] { 10L };
        double[][] doubleArray36 = new double[][] { doubleArray35 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution37 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator31, doubleArray33, doubleArray36);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution38 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray26, doubleArray36);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution39 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator15, doubleArray23, doubleArray36);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution40 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray2, doubleArray36);
        int int41 = multivariateNormalDistribution40.getDimension();
        org.apache.commons.math3.random.RandomGenerator randomGenerator42 = null;
        double[] doubleArray44 = new double[] { 1 };
        double[] doubleArray46 = new double[] { 10L };
        double[][] doubleArray47 = new double[][] { doubleArray46 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution48 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator42, doubleArray44, doubleArray47);
        double[] doubleArray49 = multivariateNormalDistribution48.getStandardDeviations();
        double double50 = multivariateNormalDistribution40.density(doubleArray49);
        org.apache.commons.math3.linear.RealMatrix realMatrix51 = multivariateNormalDistribution40.getCovariances();
        double[] doubleArray52 = multivariateNormalDistribution40.getMeans();
        org.junit.Assert.assertNotNull(doubleArray2);
        org.junit.Assert.assertArrayEquals(doubleArray2, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray4);
        org.junit.Assert.assertArrayEquals(doubleArray4, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray5);
        org.junit.Assert.assertNotNull(doubleArray9);
        org.junit.Assert.assertArrayEquals(doubleArray9, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray11);
        org.junit.Assert.assertArrayEquals(doubleArray11, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray12);
        org.junit.Assert.assertNotNull(doubleArray18);
        org.junit.Assert.assertArrayEquals(doubleArray18, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray20);
        org.junit.Assert.assertArrayEquals(doubleArray20, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray21);
        org.junit.Assert.assertNotNull(doubleArray23);
        org.junit.Assert.assertArrayEquals(doubleArray23, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray26);
        org.junit.Assert.assertArrayEquals(doubleArray26, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray28);
        org.junit.Assert.assertArrayEquals(doubleArray28, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray29);
        org.junit.Assert.assertNotNull(doubleArray33);
        org.junit.Assert.assertArrayEquals(doubleArray33, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray35);
        org.junit.Assert.assertArrayEquals(doubleArray35, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray36);
        org.junit.Assert.assertTrue("'" + int41 + "' != '" + 1 + "'", int41 == 1);
        org.junit.Assert.assertNotNull(doubleArray44);
        org.junit.Assert.assertArrayEquals(doubleArray44, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray46);
        org.junit.Assert.assertArrayEquals(doubleArray46, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray47);
        org.junit.Assert.assertNotNull(doubleArray49);
        org.junit.Assert.assertArrayEquals(doubleArray49, new double[] { 3.1622776601683795d }, 1.0E-15);
        org.junit.Assert.assertTrue("'" + double50 + "' != '" + 0.25030758422097577d + "'", double50 == 0.25030758422097577d);
        org.junit.Assert.assertNotNull(realMatrix51);
        org.junit.Assert.assertNotNull(doubleArray52);
        org.junit.Assert.assertArrayEquals(doubleArray52, new double[] { 1.0d }, 1.0E-15);
    }

    @Test
    public void test1504() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest3.test1504");
        org.apache.commons.math3.random.RandomGenerator randomGenerator0 = null;
        double[] doubleArray2 = new double[] { 1 };
        double[] doubleArray4 = new double[] { 10L };
        double[][] doubleArray5 = new double[][] { doubleArray4 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution6 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator0, doubleArray2, doubleArray5);
        double[] doubleArray7 = multivariateNormalDistribution6.getMeans();
        org.apache.commons.math3.random.RandomGenerator randomGenerator8 = null;
        double[] doubleArray10 = new double[] { 1 };
        double[] doubleArray12 = new double[] { 10L };
        double[][] doubleArray13 = new double[][] { doubleArray12 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution14 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator8, doubleArray10, doubleArray13);
        org.apache.commons.math3.random.RandomGenerator randomGenerator15 = null;
        double[] doubleArray17 = new double[] { 1 };
        double[] doubleArray19 = new double[] { 10L };
        double[][] doubleArray20 = new double[][] { doubleArray19 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution21 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator15, doubleArray17, doubleArray20);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution22 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray10, doubleArray20);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution23 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray7, doubleArray20);
        int int24 = multivariateNormalDistribution23.getDimension();
        multivariateNormalDistribution23.reseedRandomGenerator((long) '4');
        int int27 = multivariateNormalDistribution23.getDimension();
        double[] doubleArray28 = multivariateNormalDistribution23.getStandardDeviations();
        org.apache.commons.math3.random.RandomGenerator randomGenerator29 = null;
        double[] doubleArray31 = new double[] { 1 };
        double[] doubleArray33 = new double[] { 10L };
        double[][] doubleArray34 = new double[][] { doubleArray33 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution35 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator29, doubleArray31, doubleArray34);
        double[] doubleArray36 = multivariateNormalDistribution35.getMeans();
        org.apache.commons.math3.random.RandomGenerator randomGenerator37 = null;
        double[] doubleArray39 = new double[] { 1 };
        double[] doubleArray41 = new double[] { 10L };
        double[][] doubleArray42 = new double[][] { doubleArray41 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution43 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator37, doubleArray39, doubleArray42);
        org.apache.commons.math3.random.RandomGenerator randomGenerator44 = null;
        double[] doubleArray46 = new double[] { 1 };
        double[] doubleArray48 = new double[] { 10L };
        double[][] doubleArray49 = new double[][] { doubleArray48 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution50 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator44, doubleArray46, doubleArray49);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution51 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray39, doubleArray49);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution52 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray36, doubleArray49);
        int int53 = multivariateNormalDistribution52.getDimension();
        multivariateNormalDistribution52.reseedRandomGenerator((long) '4');
        double[][] doubleArray57 = multivariateNormalDistribution52.sample((int) (short) 1);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution58 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray28, doubleArray57);
        org.apache.commons.math3.random.RandomGenerator randomGenerator59 = null;
        double[] doubleArray61 = new double[] { 1 };
        double[] doubleArray63 = new double[] { 10L };
        double[][] doubleArray64 = new double[][] { doubleArray63 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution65 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator59, doubleArray61, doubleArray64);
        org.apache.commons.math3.random.RandomGenerator randomGenerator66 = null;
        double[] doubleArray68 = new double[] { 1 };
        double[] doubleArray70 = new double[] { 10L };
        double[][] doubleArray71 = new double[][] { doubleArray70 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution72 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator66, doubleArray68, doubleArray71);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution73 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray61, doubleArray71);
        double[] doubleArray74 = multivariateNormalDistribution73.getStandardDeviations();
        double[] doubleArray75 = multivariateNormalDistribution73.sample();
        org.apache.commons.math3.random.RandomGenerator randomGenerator76 = null;
        double[] doubleArray78 = new double[] { 1 };
        double[] doubleArray80 = new double[] { 10L };
        double[][] doubleArray81 = new double[][] { doubleArray80 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution82 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator76, doubleArray78, doubleArray81);
        org.apache.commons.math3.random.RandomGenerator randomGenerator83 = null;
        double[] doubleArray85 = new double[] { 1 };
        double[] doubleArray87 = new double[] { 10L };
        double[][] doubleArray88 = new double[][] { doubleArray87 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution89 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator83, doubleArray85, doubleArray88);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution90 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray78, doubleArray88);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution91 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray75, doubleArray88);
        double[] doubleArray92 = multivariateNormalDistribution91.getStandardDeviations();
        double double93 = multivariateNormalDistribution58.density(doubleArray92);
        multivariateNormalDistribution58.reseedRandomGenerator((long) (byte) 100);
        int int96 = multivariateNormalDistribution58.getDimension();
        double[][] doubleArray98 = multivariateNormalDistribution58.sample((int) (byte) 100);
        org.junit.Assert.assertNotNull(doubleArray2);
        org.junit.Assert.assertArrayEquals(doubleArray2, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray4);
        org.junit.Assert.assertArrayEquals(doubleArray4, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray5);
        org.junit.Assert.assertNotNull(doubleArray7);
        org.junit.Assert.assertArrayEquals(doubleArray7, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray10);
        org.junit.Assert.assertArrayEquals(doubleArray10, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray12);
        org.junit.Assert.assertArrayEquals(doubleArray12, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray13);
        org.junit.Assert.assertNotNull(doubleArray17);
        org.junit.Assert.assertArrayEquals(doubleArray17, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray19);
        org.junit.Assert.assertArrayEquals(doubleArray19, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray20);
        org.junit.Assert.assertTrue("'" + int24 + "' != '" + 1 + "'", int24 == 1);
        org.junit.Assert.assertTrue("'" + int27 + "' != '" + 1 + "'", int27 == 1);
        org.junit.Assert.assertNotNull(doubleArray28);
        org.junit.Assert.assertArrayEquals(doubleArray28, new double[] { 3.1622776601683795d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray31);
        org.junit.Assert.assertArrayEquals(doubleArray31, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray33);
        org.junit.Assert.assertArrayEquals(doubleArray33, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray34);
        org.junit.Assert.assertNotNull(doubleArray36);
        org.junit.Assert.assertArrayEquals(doubleArray36, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray39);
        org.junit.Assert.assertArrayEquals(doubleArray39, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray41);
        org.junit.Assert.assertArrayEquals(doubleArray41, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray42);
        org.junit.Assert.assertNotNull(doubleArray46);
        org.junit.Assert.assertArrayEquals(doubleArray46, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray48);
        org.junit.Assert.assertArrayEquals(doubleArray48, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray49);
        org.junit.Assert.assertTrue("'" + int53 + "' != '" + 1 + "'", int53 == 1);
        org.junit.Assert.assertNotNull(doubleArray57);
        org.junit.Assert.assertNotNull(doubleArray61);
        org.junit.Assert.assertArrayEquals(doubleArray61, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray63);
        org.junit.Assert.assertArrayEquals(doubleArray63, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray64);
        org.junit.Assert.assertNotNull(doubleArray68);
        org.junit.Assert.assertArrayEquals(doubleArray68, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray70);
        org.junit.Assert.assertArrayEquals(doubleArray70, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray71);
        org.junit.Assert.assertNotNull(doubleArray74);
        org.junit.Assert.assertArrayEquals(doubleArray74, new double[] { 3.1622776601683795d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray75);
// flaky "1) test1504(org.apache.commons.math3.distribution.RegressionTest3)":         org.junit.Assert.assertArrayEquals(doubleArray75, new double[] { (-1.0597653634671067d) }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray78);
        org.junit.Assert.assertArrayEquals(doubleArray78, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray80);
        org.junit.Assert.assertArrayEquals(doubleArray80, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray81);
        org.junit.Assert.assertNotNull(doubleArray85);
        org.junit.Assert.assertArrayEquals(doubleArray85, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray87);
        org.junit.Assert.assertArrayEquals(doubleArray87, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray88);
        org.junit.Assert.assertNotNull(doubleArray92);
        org.junit.Assert.assertArrayEquals(doubleArray92, new double[] { 3.1622776601683795d }, 1.0E-15);
        org.junit.Assert.assertTrue("'" + double93 + "' != '" + 0.5289308613242657d + "'", double93 == 0.5289308613242657d);
        org.junit.Assert.assertTrue("'" + int96 + "' != '" + 1 + "'", int96 == 1);
        org.junit.Assert.assertNotNull(doubleArray98);
    }

    @Test
    public void test1505() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest3.test1505");
        org.apache.commons.math3.random.RandomGenerator randomGenerator0 = null;
        double[] doubleArray2 = new double[] { 1 };
        double[] doubleArray4 = new double[] { 10L };
        double[][] doubleArray5 = new double[][] { doubleArray4 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution6 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator0, doubleArray2, doubleArray5);
        org.apache.commons.math3.random.RandomGenerator randomGenerator7 = null;
        double[] doubleArray9 = new double[] { 1 };
        double[] doubleArray11 = new double[] { 10L };
        double[][] doubleArray12 = new double[][] { doubleArray11 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution13 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator7, doubleArray9, doubleArray12);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution14 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray2, doubleArray12);
        double[] doubleArray15 = multivariateNormalDistribution14.getStandardDeviations();
        org.apache.commons.math3.random.RandomGenerator randomGenerator16 = null;
        double[] doubleArray18 = new double[] { 1 };
        double[] doubleArray20 = new double[] { 10L };
        double[][] doubleArray21 = new double[][] { doubleArray20 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution22 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator16, doubleArray18, doubleArray21);
        double[] doubleArray23 = multivariateNormalDistribution22.getMeans();
        org.apache.commons.math3.random.RandomGenerator randomGenerator24 = null;
        double[] doubleArray26 = new double[] { 1 };
        double[] doubleArray28 = new double[] { 10L };
        double[][] doubleArray29 = new double[][] { doubleArray28 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution30 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator24, doubleArray26, doubleArray29);
        org.apache.commons.math3.random.RandomGenerator randomGenerator31 = null;
        double[] doubleArray33 = new double[] { 1 };
        double[] doubleArray35 = new double[] { 10L };
        double[][] doubleArray36 = new double[][] { doubleArray35 };
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution37 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(randomGenerator31, doubleArray33, doubleArray36);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution38 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray26, doubleArray36);
        org.apache.commons.math3.distribution.MultivariateNormalDistribution multivariateNormalDistribution39 = new org.apache.commons.math3.distribution.MultivariateNormalDistribution(doubleArray23, doubleArray36);
        double double40 = multivariateNormalDistribution14.density(doubleArray23);
        multivariateNormalDistribution14.reseedRandomGenerator((long) (byte) 1);
        double[] doubleArray43 = multivariateNormalDistribution14.getStandardDeviations();
        int int44 = multivariateNormalDistribution14.getDimension();
        double[] doubleArray45 = multivariateNormalDistribution14.getStandardDeviations();
        java.lang.Class<?> wildcardClass46 = multivariateNormalDistribution14.getClass();
        org.junit.Assert.assertNotNull(doubleArray2);
        org.junit.Assert.assertArrayEquals(doubleArray2, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray4);
        org.junit.Assert.assertArrayEquals(doubleArray4, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray5);
        org.junit.Assert.assertNotNull(doubleArray9);
        org.junit.Assert.assertArrayEquals(doubleArray9, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray11);
        org.junit.Assert.assertArrayEquals(doubleArray11, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray12);
        org.junit.Assert.assertNotNull(doubleArray15);
        org.junit.Assert.assertArrayEquals(doubleArray15, new double[] { 3.1622776601683795d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray18);
        org.junit.Assert.assertArrayEquals(doubleArray18, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray20);
        org.junit.Assert.assertArrayEquals(doubleArray20, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray21);
        org.junit.Assert.assertNotNull(doubleArray23);
        org.junit.Assert.assertArrayEquals(doubleArray23, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray26);
        org.junit.Assert.assertArrayEquals(doubleArray26, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray28);
        org.junit.Assert.assertArrayEquals(doubleArray28, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray29);
        org.junit.Assert.assertNotNull(doubleArray33);
        org.junit.Assert.assertArrayEquals(doubleArray33, new double[] { 1.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray35);
        org.junit.Assert.assertArrayEquals(doubleArray35, new double[] { 10.0d }, 1.0E-15);
        org.junit.Assert.assertNotNull(doubleArray36);
        org.junit.Assert.assertTrue("'" + double40 + "' != '" + 0.31622776601683794d + "'", double40 == 0.31622776601683794d);
        org.junit.Assert.assertNotNull(doubleArray43);
        org.junit.Assert.assertArrayEquals(doubleArray43, new double[] { 3.1622776601683795d }, 1.0E-15);
        org.junit.Assert.assertTrue("'" + int44 + "' != '" + 1 + "'", int44 == 1);
        org.junit.Assert.assertNotNull(doubleArray45);
        org.junit.Assert.assertArrayEquals(doubleArray45, new double[] { 3.1622776601683795d }, 1.0E-15);
        org.junit.Assert.assertNotNull(wildcardClass46);
    }
}
