package com.google.javascript.jscomp;

import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RegressionTest4 {

    public static boolean debug = false;

    public void assertBooleanArrayEquals(boolean[] expectedArray, boolean[] actualArray) {
        if (expectedArray.length != actualArray.length) {
            throw new AssertionError("Array lengths differ: " + expectedArray.length + " != " + actualArray.length);
        }
        for (int i = 0; i < expectedArray.length; i++) {
            if (expectedArray[i] != actualArray[i]) {
                throw new AssertionError("Arrays differ at index " + i + ": " + expectedArray[i] + " != " + actualArray[i]);
            }
        }
    }

    @Test
    public void test2001() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest4.test2001");
        com.google.javascript.jscomp.AbstractCompiler abstractCompiler0 = null;
        com.google.javascript.jscomp.ControlFlowAnalysis controlFlowAnalysis3 = new com.google.javascript.jscomp.ControlFlowAnalysis(abstractCompiler0, true, true);
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph4 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph5 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph6 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph7 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph8 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph9 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph10 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph11 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph12 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph13 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph14 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph15 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph16 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph17 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph18 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph19 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph20 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph21 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph22 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph23 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph24 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph25 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph26 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph27 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph28 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph29 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph30 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph31 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph32 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph33 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph34 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph35 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph36 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph37 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph38 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph39 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph40 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph41 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph42 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph43 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph44 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph45 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph46 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph47 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph48 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph49 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph50 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph51 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph52 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph53 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph54 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph55 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph56 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph57 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph58 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph59 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph60 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph61 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph62 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph63 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph64 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph65 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph66 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph67 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph68 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph69 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph70 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph71 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph72 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph73 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph74 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph75 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph76 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph77 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph78 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph79 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph80 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph81 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph82 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph83 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph84 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph85 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph86 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.NodeTraversal nodeTraversal87 = null;
        com.google.javascript.rhino.Node node88 = null;
        com.google.javascript.rhino.Node node89 = null;
        // The following exception was thrown during execution in test generation
        try {
            boolean boolean90 = controlFlowAnalysis3.shouldTraverse(nodeTraversal87, node88, node89);
            org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException; message: null");
        } catch (java.lang.NullPointerException e) {
            // Expected exception.
        }
        org.junit.Assert.assertNull(nodeControlFlowGraph4);
        org.junit.Assert.assertNull(nodeControlFlowGraph5);
        org.junit.Assert.assertNull(nodeControlFlowGraph6);
        org.junit.Assert.assertNull(nodeControlFlowGraph7);
        org.junit.Assert.assertNull(nodeControlFlowGraph8);
        org.junit.Assert.assertNull(nodeControlFlowGraph9);
        org.junit.Assert.assertNull(nodeControlFlowGraph10);
        org.junit.Assert.assertNull(nodeControlFlowGraph11);
        org.junit.Assert.assertNull(nodeControlFlowGraph12);
        org.junit.Assert.assertNull(nodeControlFlowGraph13);
        org.junit.Assert.assertNull(nodeControlFlowGraph14);
        org.junit.Assert.assertNull(nodeControlFlowGraph15);
        org.junit.Assert.assertNull(nodeControlFlowGraph16);
        org.junit.Assert.assertNull(nodeControlFlowGraph17);
        org.junit.Assert.assertNull(nodeControlFlowGraph18);
        org.junit.Assert.assertNull(nodeControlFlowGraph19);
        org.junit.Assert.assertNull(nodeControlFlowGraph20);
        org.junit.Assert.assertNull(nodeControlFlowGraph21);
        org.junit.Assert.assertNull(nodeControlFlowGraph22);
        org.junit.Assert.assertNull(nodeControlFlowGraph23);
        org.junit.Assert.assertNull(nodeControlFlowGraph24);
        org.junit.Assert.assertNull(nodeControlFlowGraph25);
        org.junit.Assert.assertNull(nodeControlFlowGraph26);
        org.junit.Assert.assertNull(nodeControlFlowGraph27);
        org.junit.Assert.assertNull(nodeControlFlowGraph28);
        org.junit.Assert.assertNull(nodeControlFlowGraph29);
        org.junit.Assert.assertNull(nodeControlFlowGraph30);
        org.junit.Assert.assertNull(nodeControlFlowGraph31);
        org.junit.Assert.assertNull(nodeControlFlowGraph32);
        org.junit.Assert.assertNull(nodeControlFlowGraph33);
        org.junit.Assert.assertNull(nodeControlFlowGraph34);
        org.junit.Assert.assertNull(nodeControlFlowGraph35);
        org.junit.Assert.assertNull(nodeControlFlowGraph36);
        org.junit.Assert.assertNull(nodeControlFlowGraph37);
        org.junit.Assert.assertNull(nodeControlFlowGraph38);
        org.junit.Assert.assertNull(nodeControlFlowGraph39);
        org.junit.Assert.assertNull(nodeControlFlowGraph40);
        org.junit.Assert.assertNull(nodeControlFlowGraph41);
        org.junit.Assert.assertNull(nodeControlFlowGraph42);
        org.junit.Assert.assertNull(nodeControlFlowGraph43);
        org.junit.Assert.assertNull(nodeControlFlowGraph44);
        org.junit.Assert.assertNull(nodeControlFlowGraph45);
        org.junit.Assert.assertNull(nodeControlFlowGraph46);
        org.junit.Assert.assertNull(nodeControlFlowGraph47);
        org.junit.Assert.assertNull(nodeControlFlowGraph48);
        org.junit.Assert.assertNull(nodeControlFlowGraph49);
        org.junit.Assert.assertNull(nodeControlFlowGraph50);
        org.junit.Assert.assertNull(nodeControlFlowGraph51);
        org.junit.Assert.assertNull(nodeControlFlowGraph52);
        org.junit.Assert.assertNull(nodeControlFlowGraph53);
        org.junit.Assert.assertNull(nodeControlFlowGraph54);
        org.junit.Assert.assertNull(nodeControlFlowGraph55);
        org.junit.Assert.assertNull(nodeControlFlowGraph56);
        org.junit.Assert.assertNull(nodeControlFlowGraph57);
        org.junit.Assert.assertNull(nodeControlFlowGraph58);
        org.junit.Assert.assertNull(nodeControlFlowGraph59);
        org.junit.Assert.assertNull(nodeControlFlowGraph60);
        org.junit.Assert.assertNull(nodeControlFlowGraph61);
        org.junit.Assert.assertNull(nodeControlFlowGraph62);
        org.junit.Assert.assertNull(nodeControlFlowGraph63);
        org.junit.Assert.assertNull(nodeControlFlowGraph64);
        org.junit.Assert.assertNull(nodeControlFlowGraph65);
        org.junit.Assert.assertNull(nodeControlFlowGraph66);
        org.junit.Assert.assertNull(nodeControlFlowGraph67);
        org.junit.Assert.assertNull(nodeControlFlowGraph68);
        org.junit.Assert.assertNull(nodeControlFlowGraph69);
        org.junit.Assert.assertNull(nodeControlFlowGraph70);
        org.junit.Assert.assertNull(nodeControlFlowGraph71);
        org.junit.Assert.assertNull(nodeControlFlowGraph72);
        org.junit.Assert.assertNull(nodeControlFlowGraph73);
        org.junit.Assert.assertNull(nodeControlFlowGraph74);
        org.junit.Assert.assertNull(nodeControlFlowGraph75);
        org.junit.Assert.assertNull(nodeControlFlowGraph76);
        org.junit.Assert.assertNull(nodeControlFlowGraph77);
        org.junit.Assert.assertNull(nodeControlFlowGraph78);
        org.junit.Assert.assertNull(nodeControlFlowGraph79);
        org.junit.Assert.assertNull(nodeControlFlowGraph80);
        org.junit.Assert.assertNull(nodeControlFlowGraph81);
        org.junit.Assert.assertNull(nodeControlFlowGraph82);
        org.junit.Assert.assertNull(nodeControlFlowGraph83);
        org.junit.Assert.assertNull(nodeControlFlowGraph84);
        org.junit.Assert.assertNull(nodeControlFlowGraph85);
        org.junit.Assert.assertNull(nodeControlFlowGraph86);
    }

    @Test
    public void test2002() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest4.test2002");
        com.google.javascript.jscomp.AbstractCompiler abstractCompiler0 = null;
        com.google.javascript.jscomp.ControlFlowAnalysis controlFlowAnalysis3 = new com.google.javascript.jscomp.ControlFlowAnalysis(abstractCompiler0, false, false);
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph4 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph5 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph6 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph7 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph8 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph9 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph10 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph11 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph12 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph13 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph14 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph15 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph16 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph17 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph18 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph19 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph20 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph21 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph22 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph23 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph24 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph25 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph26 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph27 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph28 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph29 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph30 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph31 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph32 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph33 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph34 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph35 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph36 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph37 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph38 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph39 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph40 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph41 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph42 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph43 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph44 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph45 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph46 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph47 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph48 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph49 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph50 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph51 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph52 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph53 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph54 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph55 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph56 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph57 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph58 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph59 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph60 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph61 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph62 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph63 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph64 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph65 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph66 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph67 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph68 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph69 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph70 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph71 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph72 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph73 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph74 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph75 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph76 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph77 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph78 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph79 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph80 = controlFlowAnalysis3.getCfg();
        org.junit.Assert.assertNull(nodeControlFlowGraph4);
        org.junit.Assert.assertNull(nodeControlFlowGraph5);
        org.junit.Assert.assertNull(nodeControlFlowGraph6);
        org.junit.Assert.assertNull(nodeControlFlowGraph7);
        org.junit.Assert.assertNull(nodeControlFlowGraph8);
        org.junit.Assert.assertNull(nodeControlFlowGraph9);
        org.junit.Assert.assertNull(nodeControlFlowGraph10);
        org.junit.Assert.assertNull(nodeControlFlowGraph11);
        org.junit.Assert.assertNull(nodeControlFlowGraph12);
        org.junit.Assert.assertNull(nodeControlFlowGraph13);
        org.junit.Assert.assertNull(nodeControlFlowGraph14);
        org.junit.Assert.assertNull(nodeControlFlowGraph15);
        org.junit.Assert.assertNull(nodeControlFlowGraph16);
        org.junit.Assert.assertNull(nodeControlFlowGraph17);
        org.junit.Assert.assertNull(nodeControlFlowGraph18);
        org.junit.Assert.assertNull(nodeControlFlowGraph19);
        org.junit.Assert.assertNull(nodeControlFlowGraph20);
        org.junit.Assert.assertNull(nodeControlFlowGraph21);
        org.junit.Assert.assertNull(nodeControlFlowGraph22);
        org.junit.Assert.assertNull(nodeControlFlowGraph23);
        org.junit.Assert.assertNull(nodeControlFlowGraph24);
        org.junit.Assert.assertNull(nodeControlFlowGraph25);
        org.junit.Assert.assertNull(nodeControlFlowGraph26);
        org.junit.Assert.assertNull(nodeControlFlowGraph27);
        org.junit.Assert.assertNull(nodeControlFlowGraph28);
        org.junit.Assert.assertNull(nodeControlFlowGraph29);
        org.junit.Assert.assertNull(nodeControlFlowGraph30);
        org.junit.Assert.assertNull(nodeControlFlowGraph31);
        org.junit.Assert.assertNull(nodeControlFlowGraph32);
        org.junit.Assert.assertNull(nodeControlFlowGraph33);
        org.junit.Assert.assertNull(nodeControlFlowGraph34);
        org.junit.Assert.assertNull(nodeControlFlowGraph35);
        org.junit.Assert.assertNull(nodeControlFlowGraph36);
        org.junit.Assert.assertNull(nodeControlFlowGraph37);
        org.junit.Assert.assertNull(nodeControlFlowGraph38);
        org.junit.Assert.assertNull(nodeControlFlowGraph39);
        org.junit.Assert.assertNull(nodeControlFlowGraph40);
        org.junit.Assert.assertNull(nodeControlFlowGraph41);
        org.junit.Assert.assertNull(nodeControlFlowGraph42);
        org.junit.Assert.assertNull(nodeControlFlowGraph43);
        org.junit.Assert.assertNull(nodeControlFlowGraph44);
        org.junit.Assert.assertNull(nodeControlFlowGraph45);
        org.junit.Assert.assertNull(nodeControlFlowGraph46);
        org.junit.Assert.assertNull(nodeControlFlowGraph47);
        org.junit.Assert.assertNull(nodeControlFlowGraph48);
        org.junit.Assert.assertNull(nodeControlFlowGraph49);
        org.junit.Assert.assertNull(nodeControlFlowGraph50);
        org.junit.Assert.assertNull(nodeControlFlowGraph51);
        org.junit.Assert.assertNull(nodeControlFlowGraph52);
        org.junit.Assert.assertNull(nodeControlFlowGraph53);
        org.junit.Assert.assertNull(nodeControlFlowGraph54);
        org.junit.Assert.assertNull(nodeControlFlowGraph55);
        org.junit.Assert.assertNull(nodeControlFlowGraph56);
        org.junit.Assert.assertNull(nodeControlFlowGraph57);
        org.junit.Assert.assertNull(nodeControlFlowGraph58);
        org.junit.Assert.assertNull(nodeControlFlowGraph59);
        org.junit.Assert.assertNull(nodeControlFlowGraph60);
        org.junit.Assert.assertNull(nodeControlFlowGraph61);
        org.junit.Assert.assertNull(nodeControlFlowGraph62);
        org.junit.Assert.assertNull(nodeControlFlowGraph63);
        org.junit.Assert.assertNull(nodeControlFlowGraph64);
        org.junit.Assert.assertNull(nodeControlFlowGraph65);
        org.junit.Assert.assertNull(nodeControlFlowGraph66);
        org.junit.Assert.assertNull(nodeControlFlowGraph67);
        org.junit.Assert.assertNull(nodeControlFlowGraph68);
        org.junit.Assert.assertNull(nodeControlFlowGraph69);
        org.junit.Assert.assertNull(nodeControlFlowGraph70);
        org.junit.Assert.assertNull(nodeControlFlowGraph71);
        org.junit.Assert.assertNull(nodeControlFlowGraph72);
        org.junit.Assert.assertNull(nodeControlFlowGraph73);
        org.junit.Assert.assertNull(nodeControlFlowGraph74);
        org.junit.Assert.assertNull(nodeControlFlowGraph75);
        org.junit.Assert.assertNull(nodeControlFlowGraph76);
        org.junit.Assert.assertNull(nodeControlFlowGraph77);
        org.junit.Assert.assertNull(nodeControlFlowGraph78);
        org.junit.Assert.assertNull(nodeControlFlowGraph79);
        org.junit.Assert.assertNull(nodeControlFlowGraph80);
    }

    @Test
    public void test2003() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest4.test2003");
        com.google.javascript.jscomp.AbstractCompiler abstractCompiler0 = null;
        com.google.javascript.jscomp.ControlFlowAnalysis controlFlowAnalysis3 = new com.google.javascript.jscomp.ControlFlowAnalysis(abstractCompiler0, true, true);
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph4 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph5 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph6 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph7 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph8 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph9 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph10 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph11 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph12 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph13 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph14 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph15 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph16 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph17 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph18 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph19 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph20 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph21 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph22 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph23 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph24 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph25 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph26 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph27 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph28 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph29 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph30 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph31 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph32 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph33 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph34 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph35 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph36 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph37 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph38 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph39 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph40 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph41 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph42 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph43 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph44 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph45 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph46 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph47 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph48 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph49 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph50 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph51 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph52 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph53 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph54 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph55 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph56 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph57 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph58 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph59 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph60 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph61 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph62 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph63 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph64 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph65 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph66 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph67 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph68 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph69 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph70 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph71 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph72 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph73 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph74 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph75 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph76 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph77 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph78 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph79 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph80 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph81 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph82 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph83 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph84 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph85 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph86 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph87 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.NodeTraversal nodeTraversal88 = null;
        com.google.javascript.rhino.Node node89 = null;
        com.google.javascript.rhino.Node node90 = null;
        // The following exception was thrown during execution in test generation
        try {
            boolean boolean91 = controlFlowAnalysis3.shouldTraverse(nodeTraversal88, node89, node90);
            org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException; message: null");
        } catch (java.lang.NullPointerException e) {
            // Expected exception.
        }
        org.junit.Assert.assertNull(nodeControlFlowGraph4);
        org.junit.Assert.assertNull(nodeControlFlowGraph5);
        org.junit.Assert.assertNull(nodeControlFlowGraph6);
        org.junit.Assert.assertNull(nodeControlFlowGraph7);
        org.junit.Assert.assertNull(nodeControlFlowGraph8);
        org.junit.Assert.assertNull(nodeControlFlowGraph9);
        org.junit.Assert.assertNull(nodeControlFlowGraph10);
        org.junit.Assert.assertNull(nodeControlFlowGraph11);
        org.junit.Assert.assertNull(nodeControlFlowGraph12);
        org.junit.Assert.assertNull(nodeControlFlowGraph13);
        org.junit.Assert.assertNull(nodeControlFlowGraph14);
        org.junit.Assert.assertNull(nodeControlFlowGraph15);
        org.junit.Assert.assertNull(nodeControlFlowGraph16);
        org.junit.Assert.assertNull(nodeControlFlowGraph17);
        org.junit.Assert.assertNull(nodeControlFlowGraph18);
        org.junit.Assert.assertNull(nodeControlFlowGraph19);
        org.junit.Assert.assertNull(nodeControlFlowGraph20);
        org.junit.Assert.assertNull(nodeControlFlowGraph21);
        org.junit.Assert.assertNull(nodeControlFlowGraph22);
        org.junit.Assert.assertNull(nodeControlFlowGraph23);
        org.junit.Assert.assertNull(nodeControlFlowGraph24);
        org.junit.Assert.assertNull(nodeControlFlowGraph25);
        org.junit.Assert.assertNull(nodeControlFlowGraph26);
        org.junit.Assert.assertNull(nodeControlFlowGraph27);
        org.junit.Assert.assertNull(nodeControlFlowGraph28);
        org.junit.Assert.assertNull(nodeControlFlowGraph29);
        org.junit.Assert.assertNull(nodeControlFlowGraph30);
        org.junit.Assert.assertNull(nodeControlFlowGraph31);
        org.junit.Assert.assertNull(nodeControlFlowGraph32);
        org.junit.Assert.assertNull(nodeControlFlowGraph33);
        org.junit.Assert.assertNull(nodeControlFlowGraph34);
        org.junit.Assert.assertNull(nodeControlFlowGraph35);
        org.junit.Assert.assertNull(nodeControlFlowGraph36);
        org.junit.Assert.assertNull(nodeControlFlowGraph37);
        org.junit.Assert.assertNull(nodeControlFlowGraph38);
        org.junit.Assert.assertNull(nodeControlFlowGraph39);
        org.junit.Assert.assertNull(nodeControlFlowGraph40);
        org.junit.Assert.assertNull(nodeControlFlowGraph41);
        org.junit.Assert.assertNull(nodeControlFlowGraph42);
        org.junit.Assert.assertNull(nodeControlFlowGraph43);
        org.junit.Assert.assertNull(nodeControlFlowGraph44);
        org.junit.Assert.assertNull(nodeControlFlowGraph45);
        org.junit.Assert.assertNull(nodeControlFlowGraph46);
        org.junit.Assert.assertNull(nodeControlFlowGraph47);
        org.junit.Assert.assertNull(nodeControlFlowGraph48);
        org.junit.Assert.assertNull(nodeControlFlowGraph49);
        org.junit.Assert.assertNull(nodeControlFlowGraph50);
        org.junit.Assert.assertNull(nodeControlFlowGraph51);
        org.junit.Assert.assertNull(nodeControlFlowGraph52);
        org.junit.Assert.assertNull(nodeControlFlowGraph53);
        org.junit.Assert.assertNull(nodeControlFlowGraph54);
        org.junit.Assert.assertNull(nodeControlFlowGraph55);
        org.junit.Assert.assertNull(nodeControlFlowGraph56);
        org.junit.Assert.assertNull(nodeControlFlowGraph57);
        org.junit.Assert.assertNull(nodeControlFlowGraph58);
        org.junit.Assert.assertNull(nodeControlFlowGraph59);
        org.junit.Assert.assertNull(nodeControlFlowGraph60);
        org.junit.Assert.assertNull(nodeControlFlowGraph61);
        org.junit.Assert.assertNull(nodeControlFlowGraph62);
        org.junit.Assert.assertNull(nodeControlFlowGraph63);
        org.junit.Assert.assertNull(nodeControlFlowGraph64);
        org.junit.Assert.assertNull(nodeControlFlowGraph65);
        org.junit.Assert.assertNull(nodeControlFlowGraph66);
        org.junit.Assert.assertNull(nodeControlFlowGraph67);
        org.junit.Assert.assertNull(nodeControlFlowGraph68);
        org.junit.Assert.assertNull(nodeControlFlowGraph69);
        org.junit.Assert.assertNull(nodeControlFlowGraph70);
        org.junit.Assert.assertNull(nodeControlFlowGraph71);
        org.junit.Assert.assertNull(nodeControlFlowGraph72);
        org.junit.Assert.assertNull(nodeControlFlowGraph73);
        org.junit.Assert.assertNull(nodeControlFlowGraph74);
        org.junit.Assert.assertNull(nodeControlFlowGraph75);
        org.junit.Assert.assertNull(nodeControlFlowGraph76);
        org.junit.Assert.assertNull(nodeControlFlowGraph77);
        org.junit.Assert.assertNull(nodeControlFlowGraph78);
        org.junit.Assert.assertNull(nodeControlFlowGraph79);
        org.junit.Assert.assertNull(nodeControlFlowGraph80);
        org.junit.Assert.assertNull(nodeControlFlowGraph81);
        org.junit.Assert.assertNull(nodeControlFlowGraph82);
        org.junit.Assert.assertNull(nodeControlFlowGraph83);
        org.junit.Assert.assertNull(nodeControlFlowGraph84);
        org.junit.Assert.assertNull(nodeControlFlowGraph85);
        org.junit.Assert.assertNull(nodeControlFlowGraph86);
        org.junit.Assert.assertNull(nodeControlFlowGraph87);
    }

    @Test
    public void test2004() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest4.test2004");
        com.google.javascript.jscomp.AbstractCompiler abstractCompiler0 = null;
        com.google.javascript.jscomp.ControlFlowAnalysis controlFlowAnalysis3 = new com.google.javascript.jscomp.ControlFlowAnalysis(abstractCompiler0, false, true);
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph4 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph5 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph6 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph7 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph8 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph9 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph10 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph11 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph12 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph13 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph14 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph15 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph16 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph17 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph18 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph19 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph20 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph21 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph22 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph23 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph24 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph25 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph26 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph27 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph28 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph29 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph30 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph31 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph32 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph33 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph34 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph35 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph36 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph37 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph38 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph39 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph40 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph41 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph42 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph43 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph44 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph45 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph46 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph47 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph48 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph49 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph50 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph51 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph52 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph53 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph54 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph55 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph56 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph57 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph58 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph59 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph60 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph61 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph62 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph63 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph64 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph65 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph66 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph67 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph68 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph69 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph70 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph71 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph72 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph73 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph74 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph75 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph76 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph77 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph78 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph79 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph80 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph81 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph82 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph83 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph84 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph85 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph86 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph87 = controlFlowAnalysis3.getCfg();
        org.junit.Assert.assertNull(nodeControlFlowGraph4);
        org.junit.Assert.assertNull(nodeControlFlowGraph5);
        org.junit.Assert.assertNull(nodeControlFlowGraph6);
        org.junit.Assert.assertNull(nodeControlFlowGraph7);
        org.junit.Assert.assertNull(nodeControlFlowGraph8);
        org.junit.Assert.assertNull(nodeControlFlowGraph9);
        org.junit.Assert.assertNull(nodeControlFlowGraph10);
        org.junit.Assert.assertNull(nodeControlFlowGraph11);
        org.junit.Assert.assertNull(nodeControlFlowGraph12);
        org.junit.Assert.assertNull(nodeControlFlowGraph13);
        org.junit.Assert.assertNull(nodeControlFlowGraph14);
        org.junit.Assert.assertNull(nodeControlFlowGraph15);
        org.junit.Assert.assertNull(nodeControlFlowGraph16);
        org.junit.Assert.assertNull(nodeControlFlowGraph17);
        org.junit.Assert.assertNull(nodeControlFlowGraph18);
        org.junit.Assert.assertNull(nodeControlFlowGraph19);
        org.junit.Assert.assertNull(nodeControlFlowGraph20);
        org.junit.Assert.assertNull(nodeControlFlowGraph21);
        org.junit.Assert.assertNull(nodeControlFlowGraph22);
        org.junit.Assert.assertNull(nodeControlFlowGraph23);
        org.junit.Assert.assertNull(nodeControlFlowGraph24);
        org.junit.Assert.assertNull(nodeControlFlowGraph25);
        org.junit.Assert.assertNull(nodeControlFlowGraph26);
        org.junit.Assert.assertNull(nodeControlFlowGraph27);
        org.junit.Assert.assertNull(nodeControlFlowGraph28);
        org.junit.Assert.assertNull(nodeControlFlowGraph29);
        org.junit.Assert.assertNull(nodeControlFlowGraph30);
        org.junit.Assert.assertNull(nodeControlFlowGraph31);
        org.junit.Assert.assertNull(nodeControlFlowGraph32);
        org.junit.Assert.assertNull(nodeControlFlowGraph33);
        org.junit.Assert.assertNull(nodeControlFlowGraph34);
        org.junit.Assert.assertNull(nodeControlFlowGraph35);
        org.junit.Assert.assertNull(nodeControlFlowGraph36);
        org.junit.Assert.assertNull(nodeControlFlowGraph37);
        org.junit.Assert.assertNull(nodeControlFlowGraph38);
        org.junit.Assert.assertNull(nodeControlFlowGraph39);
        org.junit.Assert.assertNull(nodeControlFlowGraph40);
        org.junit.Assert.assertNull(nodeControlFlowGraph41);
        org.junit.Assert.assertNull(nodeControlFlowGraph42);
        org.junit.Assert.assertNull(nodeControlFlowGraph43);
        org.junit.Assert.assertNull(nodeControlFlowGraph44);
        org.junit.Assert.assertNull(nodeControlFlowGraph45);
        org.junit.Assert.assertNull(nodeControlFlowGraph46);
        org.junit.Assert.assertNull(nodeControlFlowGraph47);
        org.junit.Assert.assertNull(nodeControlFlowGraph48);
        org.junit.Assert.assertNull(nodeControlFlowGraph49);
        org.junit.Assert.assertNull(nodeControlFlowGraph50);
        org.junit.Assert.assertNull(nodeControlFlowGraph51);
        org.junit.Assert.assertNull(nodeControlFlowGraph52);
        org.junit.Assert.assertNull(nodeControlFlowGraph53);
        org.junit.Assert.assertNull(nodeControlFlowGraph54);
        org.junit.Assert.assertNull(nodeControlFlowGraph55);
        org.junit.Assert.assertNull(nodeControlFlowGraph56);
        org.junit.Assert.assertNull(nodeControlFlowGraph57);
        org.junit.Assert.assertNull(nodeControlFlowGraph58);
        org.junit.Assert.assertNull(nodeControlFlowGraph59);
        org.junit.Assert.assertNull(nodeControlFlowGraph60);
        org.junit.Assert.assertNull(nodeControlFlowGraph61);
        org.junit.Assert.assertNull(nodeControlFlowGraph62);
        org.junit.Assert.assertNull(nodeControlFlowGraph63);
        org.junit.Assert.assertNull(nodeControlFlowGraph64);
        org.junit.Assert.assertNull(nodeControlFlowGraph65);
        org.junit.Assert.assertNull(nodeControlFlowGraph66);
        org.junit.Assert.assertNull(nodeControlFlowGraph67);
        org.junit.Assert.assertNull(nodeControlFlowGraph68);
        org.junit.Assert.assertNull(nodeControlFlowGraph69);
        org.junit.Assert.assertNull(nodeControlFlowGraph70);
        org.junit.Assert.assertNull(nodeControlFlowGraph71);
        org.junit.Assert.assertNull(nodeControlFlowGraph72);
        org.junit.Assert.assertNull(nodeControlFlowGraph73);
        org.junit.Assert.assertNull(nodeControlFlowGraph74);
        org.junit.Assert.assertNull(nodeControlFlowGraph75);
        org.junit.Assert.assertNull(nodeControlFlowGraph76);
        org.junit.Assert.assertNull(nodeControlFlowGraph77);
        org.junit.Assert.assertNull(nodeControlFlowGraph78);
        org.junit.Assert.assertNull(nodeControlFlowGraph79);
        org.junit.Assert.assertNull(nodeControlFlowGraph80);
        org.junit.Assert.assertNull(nodeControlFlowGraph81);
        org.junit.Assert.assertNull(nodeControlFlowGraph82);
        org.junit.Assert.assertNull(nodeControlFlowGraph83);
        org.junit.Assert.assertNull(nodeControlFlowGraph84);
        org.junit.Assert.assertNull(nodeControlFlowGraph85);
        org.junit.Assert.assertNull(nodeControlFlowGraph86);
        org.junit.Assert.assertNull(nodeControlFlowGraph87);
    }

    @Test
    public void test2005() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest4.test2005");
        com.google.javascript.jscomp.AbstractCompiler abstractCompiler0 = null;
        com.google.javascript.jscomp.ControlFlowAnalysis controlFlowAnalysis3 = new com.google.javascript.jscomp.ControlFlowAnalysis(abstractCompiler0, true, false);
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph4 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph5 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph6 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph7 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph8 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph9 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph10 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph11 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph12 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph13 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph14 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph15 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph16 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph17 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph18 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph19 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph20 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph21 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph22 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph23 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph24 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph25 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph26 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph27 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph28 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph29 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph30 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph31 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph32 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph33 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph34 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph35 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph36 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph37 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph38 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph39 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph40 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph41 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph42 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph43 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph44 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph45 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph46 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph47 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph48 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph49 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph50 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph51 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph52 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph53 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph54 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph55 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph56 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph57 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph58 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph59 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph60 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph61 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph62 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph63 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph64 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph65 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph66 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph67 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph68 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph69 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph70 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph71 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph72 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph73 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph74 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph75 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph76 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph77 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph78 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph79 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph80 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph81 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph82 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph83 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph84 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph85 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph86 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph87 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph88 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph89 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph90 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph91 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph92 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph93 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph94 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph95 = controlFlowAnalysis3.getCfg();
        com.google.javascript.jscomp.ControlFlowGraph<com.google.javascript.rhino.Node> nodeControlFlowGraph96 = controlFlowAnalysis3.getCfg();
        org.junit.Assert.assertNull(nodeControlFlowGraph4);
        org.junit.Assert.assertNull(nodeControlFlowGraph5);
        org.junit.Assert.assertNull(nodeControlFlowGraph6);
        org.junit.Assert.assertNull(nodeControlFlowGraph7);
        org.junit.Assert.assertNull(nodeControlFlowGraph8);
        org.junit.Assert.assertNull(nodeControlFlowGraph9);
        org.junit.Assert.assertNull(nodeControlFlowGraph10);
        org.junit.Assert.assertNull(nodeControlFlowGraph11);
        org.junit.Assert.assertNull(nodeControlFlowGraph12);
        org.junit.Assert.assertNull(nodeControlFlowGraph13);
        org.junit.Assert.assertNull(nodeControlFlowGraph14);
        org.junit.Assert.assertNull(nodeControlFlowGraph15);
        org.junit.Assert.assertNull(nodeControlFlowGraph16);
        org.junit.Assert.assertNull(nodeControlFlowGraph17);
        org.junit.Assert.assertNull(nodeControlFlowGraph18);
        org.junit.Assert.assertNull(nodeControlFlowGraph19);
        org.junit.Assert.assertNull(nodeControlFlowGraph20);
        org.junit.Assert.assertNull(nodeControlFlowGraph21);
        org.junit.Assert.assertNull(nodeControlFlowGraph22);
        org.junit.Assert.assertNull(nodeControlFlowGraph23);
        org.junit.Assert.assertNull(nodeControlFlowGraph24);
        org.junit.Assert.assertNull(nodeControlFlowGraph25);
        org.junit.Assert.assertNull(nodeControlFlowGraph26);
        org.junit.Assert.assertNull(nodeControlFlowGraph27);
        org.junit.Assert.assertNull(nodeControlFlowGraph28);
        org.junit.Assert.assertNull(nodeControlFlowGraph29);
        org.junit.Assert.assertNull(nodeControlFlowGraph30);
        org.junit.Assert.assertNull(nodeControlFlowGraph31);
        org.junit.Assert.assertNull(nodeControlFlowGraph32);
        org.junit.Assert.assertNull(nodeControlFlowGraph33);
        org.junit.Assert.assertNull(nodeControlFlowGraph34);
        org.junit.Assert.assertNull(nodeControlFlowGraph35);
        org.junit.Assert.assertNull(nodeControlFlowGraph36);
        org.junit.Assert.assertNull(nodeControlFlowGraph37);
        org.junit.Assert.assertNull(nodeControlFlowGraph38);
        org.junit.Assert.assertNull(nodeControlFlowGraph39);
        org.junit.Assert.assertNull(nodeControlFlowGraph40);
        org.junit.Assert.assertNull(nodeControlFlowGraph41);
        org.junit.Assert.assertNull(nodeControlFlowGraph42);
        org.junit.Assert.assertNull(nodeControlFlowGraph43);
        org.junit.Assert.assertNull(nodeControlFlowGraph44);
        org.junit.Assert.assertNull(nodeControlFlowGraph45);
        org.junit.Assert.assertNull(nodeControlFlowGraph46);
        org.junit.Assert.assertNull(nodeControlFlowGraph47);
        org.junit.Assert.assertNull(nodeControlFlowGraph48);
        org.junit.Assert.assertNull(nodeControlFlowGraph49);
        org.junit.Assert.assertNull(nodeControlFlowGraph50);
        org.junit.Assert.assertNull(nodeControlFlowGraph51);
        org.junit.Assert.assertNull(nodeControlFlowGraph52);
        org.junit.Assert.assertNull(nodeControlFlowGraph53);
        org.junit.Assert.assertNull(nodeControlFlowGraph54);
        org.junit.Assert.assertNull(nodeControlFlowGraph55);
        org.junit.Assert.assertNull(nodeControlFlowGraph56);
        org.junit.Assert.assertNull(nodeControlFlowGraph57);
        org.junit.Assert.assertNull(nodeControlFlowGraph58);
        org.junit.Assert.assertNull(nodeControlFlowGraph59);
        org.junit.Assert.assertNull(nodeControlFlowGraph60);
        org.junit.Assert.assertNull(nodeControlFlowGraph61);
        org.junit.Assert.assertNull(nodeControlFlowGraph62);
        org.junit.Assert.assertNull(nodeControlFlowGraph63);
        org.junit.Assert.assertNull(nodeControlFlowGraph64);
        org.junit.Assert.assertNull(nodeControlFlowGraph65);
        org.junit.Assert.assertNull(nodeControlFlowGraph66);
        org.junit.Assert.assertNull(nodeControlFlowGraph67);
        org.junit.Assert.assertNull(nodeControlFlowGraph68);
        org.junit.Assert.assertNull(nodeControlFlowGraph69);
        org.junit.Assert.assertNull(nodeControlFlowGraph70);
        org.junit.Assert.assertNull(nodeControlFlowGraph71);
        org.junit.Assert.assertNull(nodeControlFlowGraph72);
        org.junit.Assert.assertNull(nodeControlFlowGraph73);
        org.junit.Assert.assertNull(nodeControlFlowGraph74);
        org.junit.Assert.assertNull(nodeControlFlowGraph75);
        org.junit.Assert.assertNull(nodeControlFlowGraph76);
        org.junit.Assert.assertNull(nodeControlFlowGraph77);
        org.junit.Assert.assertNull(nodeControlFlowGraph78);
        org.junit.Assert.assertNull(nodeControlFlowGraph79);
        org.junit.Assert.assertNull(nodeControlFlowGraph80);
        org.junit.Assert.assertNull(nodeControlFlowGraph81);
        org.junit.Assert.assertNull(nodeControlFlowGraph82);
        org.junit.Assert.assertNull(nodeControlFlowGraph83);
        org.junit.Assert.assertNull(nodeControlFlowGraph84);
        org.junit.Assert.assertNull(nodeControlFlowGraph85);
        org.junit.Assert.assertNull(nodeControlFlowGraph86);
        org.junit.Assert.assertNull(nodeControlFlowGraph87);
        org.junit.Assert.assertNull(nodeControlFlowGraph88);
        org.junit.Assert.assertNull(nodeControlFlowGraph89);
        org.junit.Assert.assertNull(nodeControlFlowGraph90);
        org.junit.Assert.assertNull(nodeControlFlowGraph91);
        org.junit.Assert.assertNull(nodeControlFlowGraph92);
        org.junit.Assert.assertNull(nodeControlFlowGraph93);
        org.junit.Assert.assertNull(nodeControlFlowGraph94);
        org.junit.Assert.assertNull(nodeControlFlowGraph95);
        org.junit.Assert.assertNull(nodeControlFlowGraph96);
    }
}

