package com.google.javascript.rhino;

import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RegressionTest9 {

    public static boolean debug = false;

    public void assertBooleanArrayEquals(boolean[] expectedArray, boolean[] actualArray) {
        if (expectedArray.length != actualArray.length) {
            throw new AssertionError("Array lengths differ: " + expectedArray.length + " != " + actualArray.length);
        }
        for (int i = 0; i < expectedArray.length; i++) {
            if (expectedArray[i] != actualArray[i]) {
                throw new AssertionError("Arrays differ at index " + i + ": " + expectedArray[i] + " != " + actualArray[i]);
            }
        }
    }

    @Test
    public void test4501() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest9.test4501");
        com.google.javascript.rhino.Node[] nodeArray0 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node1 = com.google.javascript.rhino.IR.script(nodeArray0);
        com.google.javascript.rhino.Node node2 = com.google.javascript.rhino.IR.arraylit(nodeArray0);
        com.google.javascript.rhino.Node node3 = com.google.javascript.rhino.IR.paramList(nodeArray0);
        com.google.javascript.rhino.Node node4 = com.google.javascript.rhino.IR.block(nodeArray0);
        com.google.javascript.rhino.Node node5 = com.google.javascript.rhino.IR.arraylit(nodeArray0);
        com.google.javascript.rhino.Node[] nodeArray6 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node7 = com.google.javascript.rhino.IR.script(nodeArray6);
        com.google.javascript.rhino.Node node8 = com.google.javascript.rhino.IR.block(nodeArray6);
        com.google.javascript.rhino.Node node9 = com.google.javascript.rhino.IR.arraylit(nodeArray6);
        com.google.javascript.rhino.Node node10 = com.google.javascript.rhino.IR.script(nodeArray6);
        com.google.javascript.rhino.Node node11 = com.google.javascript.rhino.IR.arraylit(nodeArray6);
        com.google.javascript.rhino.Node node12 = com.google.javascript.rhino.IR.newNode(node5, nodeArray6);
        com.google.javascript.rhino.Node node13 = com.google.javascript.rhino.IR.block(nodeArray6);
        // The following exception was thrown during execution in test generation
        try {
            com.google.javascript.rhino.Node node14 = com.google.javascript.rhino.IR.not(node13);
            org.junit.Assert.fail("Expected exception of type java.lang.IllegalStateException; message: null");
        } catch (java.lang.IllegalStateException e) {
            // Expected exception.
        }
        org.junit.Assert.assertNotNull(nodeArray0);
        org.junit.Assert.assertArrayEquals(nodeArray0, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node1);
        org.junit.Assert.assertNotNull(node2);
        org.junit.Assert.assertNotNull(node3);
        org.junit.Assert.assertNotNull(node4);
        org.junit.Assert.assertNotNull(node5);
        org.junit.Assert.assertNotNull(nodeArray6);
        org.junit.Assert.assertArrayEquals(nodeArray6, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node7);
        org.junit.Assert.assertNotNull(node8);
        org.junit.Assert.assertNotNull(node9);
        org.junit.Assert.assertNotNull(node10);
        org.junit.Assert.assertNotNull(node11);
        org.junit.Assert.assertNotNull(node12);
        org.junit.Assert.assertNotNull(node13);
    }

    @Test
    public void test4502() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest9.test4502");
        com.google.javascript.rhino.Node node1 = com.google.javascript.rhino.IR.string("");
        com.google.javascript.rhino.Node node2 = com.google.javascript.rhino.IR.voidNode(node1);
        com.google.javascript.rhino.Node node4 = com.google.javascript.rhino.IR.name("hi!");
        com.google.javascript.rhino.Node[] nodeArray5 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node6 = com.google.javascript.rhino.IR.script(nodeArray5);
        com.google.javascript.rhino.Node node7 = com.google.javascript.rhino.IR.arraylit(nodeArray5);
        com.google.javascript.rhino.Node node8 = com.google.javascript.rhino.IR.block(nodeArray5);
        com.google.javascript.rhino.Node node9 = com.google.javascript.rhino.IR.script(nodeArray5);
        com.google.javascript.rhino.Node node10 = com.google.javascript.rhino.IR.arraylit(nodeArray5);
        com.google.javascript.rhino.Node node11 = com.google.javascript.rhino.IR.newNode(node4, nodeArray5);
        com.google.javascript.rhino.Node node12 = com.google.javascript.rhino.IR.paramList(nodeArray5);
        com.google.javascript.rhino.Node[] nodeArray13 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node14 = com.google.javascript.rhino.IR.script(nodeArray13);
        com.google.javascript.rhino.Node node15 = com.google.javascript.rhino.IR.arraylit(nodeArray13);
        com.google.javascript.rhino.Node node16 = com.google.javascript.rhino.IR.block(nodeArray13);
        com.google.javascript.rhino.Node node17 = com.google.javascript.rhino.IR.script(nodeArray13);
        com.google.javascript.rhino.Node node18 = com.google.javascript.rhino.IR.arraylit(nodeArray13);
        com.google.javascript.rhino.Node node19 = com.google.javascript.rhino.IR.not(node18);
        com.google.javascript.rhino.Node node20 = com.google.javascript.rhino.IR.thisNode();
        com.google.javascript.rhino.Node node21 = com.google.javascript.rhino.IR.or(node19, node20);
        com.google.javascript.rhino.Node[] nodeArray22 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node23 = com.google.javascript.rhino.IR.script(nodeArray22);
        com.google.javascript.rhino.Node node24 = com.google.javascript.rhino.IR.arraylit(nodeArray22);
        com.google.javascript.rhino.Node node25 = com.google.javascript.rhino.IR.block(nodeArray22);
        com.google.javascript.rhino.Node node26 = com.google.javascript.rhino.IR.script(nodeArray22);
        com.google.javascript.rhino.Node node27 = com.google.javascript.rhino.IR.switchNode(node21, nodeArray22);
        com.google.javascript.rhino.Node node28 = com.google.javascript.rhino.IR.block(nodeArray22);
        com.google.javascript.rhino.Node node29 = com.google.javascript.rhino.IR.newNode(node12, nodeArray22);
        com.google.javascript.rhino.Node[] nodeArray30 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node31 = com.google.javascript.rhino.IR.script(nodeArray30);
        com.google.javascript.rhino.Node node32 = com.google.javascript.rhino.IR.arraylit(nodeArray30);
        com.google.javascript.rhino.Node node33 = com.google.javascript.rhino.IR.block(nodeArray30);
        com.google.javascript.rhino.Node node34 = com.google.javascript.rhino.IR.script(nodeArray30);
        com.google.javascript.rhino.Node node35 = com.google.javascript.rhino.IR.arraylit(nodeArray30);
        com.google.javascript.rhino.Node node36 = com.google.javascript.rhino.IR.not(node35);
        com.google.javascript.rhino.Node node37 = com.google.javascript.rhino.IR.thisNode();
        com.google.javascript.rhino.Node node38 = com.google.javascript.rhino.IR.or(node36, node37);
        com.google.javascript.rhino.Node[] nodeArray39 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node40 = com.google.javascript.rhino.IR.script(nodeArray39);
        com.google.javascript.rhino.Node node41 = com.google.javascript.rhino.IR.arraylit(nodeArray39);
        com.google.javascript.rhino.Node node42 = com.google.javascript.rhino.IR.block(nodeArray39);
        com.google.javascript.rhino.Node node43 = com.google.javascript.rhino.IR.script(nodeArray39);
        com.google.javascript.rhino.Node node44 = com.google.javascript.rhino.IR.switchNode(node38, nodeArray39);
        com.google.javascript.rhino.Node node45 = com.google.javascript.rhino.IR.paramList(nodeArray39);
        com.google.javascript.rhino.Node node46 = com.google.javascript.rhino.IR.objectlit(nodeArray39);
        com.google.javascript.rhino.Node node47 = com.google.javascript.rhino.IR.paramList(nodeArray39);
        com.google.javascript.rhino.Node node48 = com.google.javascript.rhino.IR.newNode(node29, nodeArray39);
        com.google.javascript.rhino.Node node49 = com.google.javascript.rhino.IR.newNode(node2, nodeArray39);
        com.google.javascript.rhino.Node node50 = com.google.javascript.rhino.IR.objectlit(nodeArray39);
        com.google.javascript.rhino.Node node51 = com.google.javascript.rhino.IR.objectlit(nodeArray39);
        com.google.javascript.rhino.Node node52 = com.google.javascript.rhino.IR.arraylit(nodeArray39);
        com.google.javascript.rhino.Node node53 = com.google.javascript.rhino.IR.arraylit(nodeArray39);
        com.google.javascript.rhino.Node node54 = com.google.javascript.rhino.IR.script(nodeArray39);
        com.google.javascript.rhino.Node node55 = com.google.javascript.rhino.IR.arraylit(nodeArray39);
        com.google.javascript.rhino.Node node56 = com.google.javascript.rhino.IR.neg(node55);
        com.google.javascript.rhino.Node node57 = com.google.javascript.rhino.IR.exprResult(node56);
        com.google.javascript.rhino.Node node59 = com.google.javascript.rhino.IR.name("hi!");
        com.google.javascript.rhino.Node[] nodeArray60 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node61 = com.google.javascript.rhino.IR.script(nodeArray60);
        com.google.javascript.rhino.Node node62 = com.google.javascript.rhino.IR.arraylit(nodeArray60);
        com.google.javascript.rhino.Node node63 = com.google.javascript.rhino.IR.block(nodeArray60);
        com.google.javascript.rhino.Node node64 = com.google.javascript.rhino.IR.script(nodeArray60);
        com.google.javascript.rhino.Node node65 = com.google.javascript.rhino.IR.arraylit(nodeArray60);
        com.google.javascript.rhino.Node node66 = com.google.javascript.rhino.IR.newNode(node59, nodeArray60);
        com.google.javascript.rhino.Node node67 = com.google.javascript.rhino.IR.paramList(nodeArray60);
        com.google.javascript.rhino.Node[] nodeArray68 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node69 = com.google.javascript.rhino.IR.script(nodeArray68);
        com.google.javascript.rhino.Node node70 = com.google.javascript.rhino.IR.arraylit(nodeArray68);
        com.google.javascript.rhino.Node node71 = com.google.javascript.rhino.IR.block(nodeArray68);
        com.google.javascript.rhino.Node node72 = com.google.javascript.rhino.IR.script(nodeArray68);
        com.google.javascript.rhino.Node node73 = com.google.javascript.rhino.IR.arraylit(nodeArray68);
        com.google.javascript.rhino.Node node74 = com.google.javascript.rhino.IR.not(node73);
        com.google.javascript.rhino.Node node75 = com.google.javascript.rhino.IR.thisNode();
        com.google.javascript.rhino.Node node76 = com.google.javascript.rhino.IR.or(node74, node75);
        com.google.javascript.rhino.Node[] nodeArray77 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node78 = com.google.javascript.rhino.IR.script(nodeArray77);
        com.google.javascript.rhino.Node node79 = com.google.javascript.rhino.IR.arraylit(nodeArray77);
        com.google.javascript.rhino.Node node80 = com.google.javascript.rhino.IR.block(nodeArray77);
        com.google.javascript.rhino.Node node81 = com.google.javascript.rhino.IR.script(nodeArray77);
        com.google.javascript.rhino.Node node82 = com.google.javascript.rhino.IR.switchNode(node76, nodeArray77);
        com.google.javascript.rhino.Node node83 = com.google.javascript.rhino.IR.block(nodeArray77);
        com.google.javascript.rhino.Node node84 = com.google.javascript.rhino.IR.newNode(node67, nodeArray77);
        com.google.javascript.rhino.Node node85 = com.google.javascript.rhino.IR.call(node57, nodeArray77);
        org.junit.Assert.assertNotNull(node1);
        org.junit.Assert.assertNotNull(node2);
        org.junit.Assert.assertNotNull(node4);
        org.junit.Assert.assertNotNull(nodeArray5);
        org.junit.Assert.assertArrayEquals(nodeArray5, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node6);
        org.junit.Assert.assertNotNull(node7);
        org.junit.Assert.assertNotNull(node8);
        org.junit.Assert.assertNotNull(node9);
        org.junit.Assert.assertNotNull(node10);
        org.junit.Assert.assertNotNull(node11);
        org.junit.Assert.assertNotNull(node12);
        org.junit.Assert.assertNotNull(nodeArray13);
        org.junit.Assert.assertArrayEquals(nodeArray13, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node14);
        org.junit.Assert.assertNotNull(node15);
        org.junit.Assert.assertNotNull(node16);
        org.junit.Assert.assertNotNull(node17);
        org.junit.Assert.assertNotNull(node18);
        org.junit.Assert.assertNotNull(node19);
        org.junit.Assert.assertNotNull(node20);
        org.junit.Assert.assertNotNull(node21);
        org.junit.Assert.assertNotNull(nodeArray22);
        org.junit.Assert.assertArrayEquals(nodeArray22, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node23);
        org.junit.Assert.assertNotNull(node24);
        org.junit.Assert.assertNotNull(node25);
        org.junit.Assert.assertNotNull(node26);
        org.junit.Assert.assertNotNull(node27);
        org.junit.Assert.assertNotNull(node28);
        org.junit.Assert.assertNotNull(node29);
        org.junit.Assert.assertNotNull(nodeArray30);
        org.junit.Assert.assertArrayEquals(nodeArray30, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node31);
        org.junit.Assert.assertNotNull(node32);
        org.junit.Assert.assertNotNull(node33);
        org.junit.Assert.assertNotNull(node34);
        org.junit.Assert.assertNotNull(node35);
        org.junit.Assert.assertNotNull(node36);
        org.junit.Assert.assertNotNull(node37);
        org.junit.Assert.assertNotNull(node38);
        org.junit.Assert.assertNotNull(nodeArray39);
        org.junit.Assert.assertArrayEquals(nodeArray39, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node40);
        org.junit.Assert.assertNotNull(node41);
        org.junit.Assert.assertNotNull(node42);
        org.junit.Assert.assertNotNull(node43);
        org.junit.Assert.assertNotNull(node44);
        org.junit.Assert.assertNotNull(node45);
        org.junit.Assert.assertNotNull(node46);
        org.junit.Assert.assertNotNull(node47);
        org.junit.Assert.assertNotNull(node48);
        org.junit.Assert.assertNotNull(node49);
        org.junit.Assert.assertNotNull(node50);
        org.junit.Assert.assertNotNull(node51);
        org.junit.Assert.assertNotNull(node52);
        org.junit.Assert.assertNotNull(node53);
        org.junit.Assert.assertNotNull(node54);
        org.junit.Assert.assertNotNull(node55);
        org.junit.Assert.assertNotNull(node56);
        org.junit.Assert.assertNotNull(node57);
        org.junit.Assert.assertNotNull(node59);
        org.junit.Assert.assertNotNull(nodeArray60);
        org.junit.Assert.assertArrayEquals(nodeArray60, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node61);
        org.junit.Assert.assertNotNull(node62);
        org.junit.Assert.assertNotNull(node63);
        org.junit.Assert.assertNotNull(node64);
        org.junit.Assert.assertNotNull(node65);
        org.junit.Assert.assertNotNull(node66);
        org.junit.Assert.assertNotNull(node67);
        org.junit.Assert.assertNotNull(nodeArray68);
        org.junit.Assert.assertArrayEquals(nodeArray68, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node69);
        org.junit.Assert.assertNotNull(node70);
        org.junit.Assert.assertNotNull(node71);
        org.junit.Assert.assertNotNull(node72);
        org.junit.Assert.assertNotNull(node73);
        org.junit.Assert.assertNotNull(node74);
        org.junit.Assert.assertNotNull(node75);
        org.junit.Assert.assertNotNull(node76);
        org.junit.Assert.assertNotNull(nodeArray77);
        org.junit.Assert.assertArrayEquals(nodeArray77, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node78);
        org.junit.Assert.assertNotNull(node79);
        org.junit.Assert.assertNotNull(node80);
        org.junit.Assert.assertNotNull(node81);
        org.junit.Assert.assertNotNull(node82);
        org.junit.Assert.assertNotNull(node83);
        org.junit.Assert.assertNotNull(node84);
        org.junit.Assert.assertNotNull(node85);
    }

    @Test
    public void test4503() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest9.test4503");
        com.google.javascript.rhino.Node node0 = null;
        com.google.javascript.rhino.Node node2 = com.google.javascript.rhino.IR.name("hi!");
        com.google.javascript.rhino.Node[] nodeArray3 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node4 = com.google.javascript.rhino.IR.script(nodeArray3);
        com.google.javascript.rhino.Node node5 = com.google.javascript.rhino.IR.arraylit(nodeArray3);
        com.google.javascript.rhino.Node node6 = com.google.javascript.rhino.IR.block(nodeArray3);
        com.google.javascript.rhino.Node node7 = com.google.javascript.rhino.IR.script(nodeArray3);
        com.google.javascript.rhino.Node node8 = com.google.javascript.rhino.IR.arraylit(nodeArray3);
        com.google.javascript.rhino.Node node9 = com.google.javascript.rhino.IR.newNode(node2, nodeArray3);
        com.google.javascript.rhino.Node node10 = com.google.javascript.rhino.IR.script(nodeArray3);
        com.google.javascript.rhino.Node node11 = com.google.javascript.rhino.IR.arraylit(nodeArray3);
        com.google.javascript.rhino.Node node12 = com.google.javascript.rhino.IR.trueNode();
        com.google.javascript.rhino.Node node13 = com.google.javascript.rhino.IR.trueNode();
        com.google.javascript.rhino.Node node14 = com.google.javascript.rhino.IR.comma(node12, node13);
        com.google.javascript.rhino.Node node15 = com.google.javascript.rhino.IR.getelem(node11, node14);
        com.google.javascript.rhino.Node node16 = com.google.javascript.rhino.IR.pos(node15);
        com.google.javascript.rhino.Node node18 = com.google.javascript.rhino.IR.number((double) (short) 10);
        com.google.javascript.rhino.Node node20 = com.google.javascript.rhino.IR.name("hi!");
        com.google.javascript.rhino.Node[] nodeArray21 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node22 = com.google.javascript.rhino.IR.script(nodeArray21);
        com.google.javascript.rhino.Node node23 = com.google.javascript.rhino.IR.arraylit(nodeArray21);
        com.google.javascript.rhino.Node node24 = com.google.javascript.rhino.IR.block(nodeArray21);
        com.google.javascript.rhino.Node node25 = com.google.javascript.rhino.IR.script(nodeArray21);
        com.google.javascript.rhino.Node node26 = com.google.javascript.rhino.IR.arraylit(nodeArray21);
        com.google.javascript.rhino.Node node27 = com.google.javascript.rhino.IR.newNode(node20, nodeArray21);
        com.google.javascript.rhino.Node node28 = com.google.javascript.rhino.IR.paramList(nodeArray21);
        com.google.javascript.rhino.Node[] nodeArray29 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node30 = com.google.javascript.rhino.IR.script(nodeArray29);
        com.google.javascript.rhino.Node node31 = com.google.javascript.rhino.IR.arraylit(nodeArray29);
        com.google.javascript.rhino.Node node32 = com.google.javascript.rhino.IR.block(nodeArray29);
        com.google.javascript.rhino.Node node33 = com.google.javascript.rhino.IR.script(nodeArray29);
        com.google.javascript.rhino.Node node34 = com.google.javascript.rhino.IR.arraylit(nodeArray29);
        com.google.javascript.rhino.Node node35 = com.google.javascript.rhino.IR.not(node34);
        com.google.javascript.rhino.Node node36 = com.google.javascript.rhino.IR.thisNode();
        com.google.javascript.rhino.Node node37 = com.google.javascript.rhino.IR.or(node35, node36);
        com.google.javascript.rhino.Node[] nodeArray38 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node39 = com.google.javascript.rhino.IR.script(nodeArray38);
        com.google.javascript.rhino.Node node40 = com.google.javascript.rhino.IR.arraylit(nodeArray38);
        com.google.javascript.rhino.Node node41 = com.google.javascript.rhino.IR.block(nodeArray38);
        com.google.javascript.rhino.Node node42 = com.google.javascript.rhino.IR.script(nodeArray38);
        com.google.javascript.rhino.Node node43 = com.google.javascript.rhino.IR.switchNode(node37, nodeArray38);
        com.google.javascript.rhino.Node node44 = com.google.javascript.rhino.IR.block(nodeArray38);
        com.google.javascript.rhino.Node node45 = com.google.javascript.rhino.IR.newNode(node28, nodeArray38);
        com.google.javascript.rhino.Node node46 = com.google.javascript.rhino.IR.block(nodeArray38);
        com.google.javascript.rhino.Node node47 = com.google.javascript.rhino.IR.arraylit(nodeArray38);
        com.google.javascript.rhino.Node node48 = com.google.javascript.rhino.IR.call(node18, nodeArray38);
        com.google.javascript.rhino.Node node49 = com.google.javascript.rhino.IR.eq(node16, node48);
        com.google.javascript.rhino.Node node51 = com.google.javascript.rhino.IR.string("");
        com.google.javascript.rhino.Node node52 = com.google.javascript.rhino.IR.neg(node51);
        com.google.javascript.rhino.Node node53 = com.google.javascript.rhino.IR.trueNode();
        com.google.javascript.rhino.Node node55 = com.google.javascript.rhino.IR.string("");
        com.google.javascript.rhino.Node node56 = com.google.javascript.rhino.IR.trueNode();
        com.google.javascript.rhino.Node node57 = com.google.javascript.rhino.IR.hook(node53, node55, node56);
        com.google.javascript.rhino.Node node58 = com.google.javascript.rhino.IR.getelem(node52, node57);
        com.google.javascript.rhino.Node node59 = com.google.javascript.rhino.IR.voidNode(node58);
        com.google.javascript.rhino.Node node61 = com.google.javascript.rhino.IR.string("hi!");
        com.google.javascript.rhino.Node node62 = com.google.javascript.rhino.IR.voidNode(node61);
        com.google.javascript.rhino.Node node63 = com.google.javascript.rhino.IR.add(node59, node62);
        com.google.javascript.rhino.Node node64 = com.google.javascript.rhino.IR.pos(node63);
        com.google.javascript.rhino.Node[] nodeArray65 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node66 = com.google.javascript.rhino.IR.script(nodeArray65);
        com.google.javascript.rhino.Node node67 = com.google.javascript.rhino.IR.arraylit(nodeArray65);
        com.google.javascript.rhino.Node node68 = com.google.javascript.rhino.IR.paramList(nodeArray65);
        com.google.javascript.rhino.Node node69 = com.google.javascript.rhino.IR.block(nodeArray65);
        com.google.javascript.rhino.Node node70 = com.google.javascript.rhino.IR.arraylit(nodeArray65);
        // The following exception was thrown during execution in test generation
        try {
            com.google.javascript.rhino.Node node71 = com.google.javascript.rhino.IR.forNode(node0, node49, node64, node70);
            org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException; message: null");
        } catch (java.lang.NullPointerException e) {
            // Expected exception.
        }
        org.junit.Assert.assertNotNull(node2);
        org.junit.Assert.assertNotNull(nodeArray3);
        org.junit.Assert.assertArrayEquals(nodeArray3, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node4);
        org.junit.Assert.assertNotNull(node5);
        org.junit.Assert.assertNotNull(node6);
        org.junit.Assert.assertNotNull(node7);
        org.junit.Assert.assertNotNull(node8);
        org.junit.Assert.assertNotNull(node9);
        org.junit.Assert.assertNotNull(node10);
        org.junit.Assert.assertNotNull(node11);
        org.junit.Assert.assertNotNull(node12);
        org.junit.Assert.assertNotNull(node13);
        org.junit.Assert.assertNotNull(node14);
        org.junit.Assert.assertNotNull(node15);
        org.junit.Assert.assertNotNull(node16);
        org.junit.Assert.assertNotNull(node18);
        org.junit.Assert.assertNotNull(node20);
        org.junit.Assert.assertNotNull(nodeArray21);
        org.junit.Assert.assertArrayEquals(nodeArray21, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node22);
        org.junit.Assert.assertNotNull(node23);
        org.junit.Assert.assertNotNull(node24);
        org.junit.Assert.assertNotNull(node25);
        org.junit.Assert.assertNotNull(node26);
        org.junit.Assert.assertNotNull(node27);
        org.junit.Assert.assertNotNull(node28);
        org.junit.Assert.assertNotNull(nodeArray29);
        org.junit.Assert.assertArrayEquals(nodeArray29, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node30);
        org.junit.Assert.assertNotNull(node31);
        org.junit.Assert.assertNotNull(node32);
        org.junit.Assert.assertNotNull(node33);
        org.junit.Assert.assertNotNull(node34);
        org.junit.Assert.assertNotNull(node35);
        org.junit.Assert.assertNotNull(node36);
        org.junit.Assert.assertNotNull(node37);
        org.junit.Assert.assertNotNull(nodeArray38);
        org.junit.Assert.assertArrayEquals(nodeArray38, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node39);
        org.junit.Assert.assertNotNull(node40);
        org.junit.Assert.assertNotNull(node41);
        org.junit.Assert.assertNotNull(node42);
        org.junit.Assert.assertNotNull(node43);
        org.junit.Assert.assertNotNull(node44);
        org.junit.Assert.assertNotNull(node45);
        org.junit.Assert.assertNotNull(node46);
        org.junit.Assert.assertNotNull(node47);
        org.junit.Assert.assertNotNull(node48);
        org.junit.Assert.assertNotNull(node49);
        org.junit.Assert.assertNotNull(node51);
        org.junit.Assert.assertNotNull(node52);
        org.junit.Assert.assertNotNull(node53);
        org.junit.Assert.assertNotNull(node55);
        org.junit.Assert.assertNotNull(node56);
        org.junit.Assert.assertNotNull(node57);
        org.junit.Assert.assertNotNull(node58);
        org.junit.Assert.assertNotNull(node59);
        org.junit.Assert.assertNotNull(node61);
        org.junit.Assert.assertNotNull(node62);
        org.junit.Assert.assertNotNull(node63);
        org.junit.Assert.assertNotNull(node64);
        org.junit.Assert.assertNotNull(nodeArray65);
        org.junit.Assert.assertArrayEquals(nodeArray65, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node66);
        org.junit.Assert.assertNotNull(node67);
        org.junit.Assert.assertNotNull(node68);
        org.junit.Assert.assertNotNull(node69);
        org.junit.Assert.assertNotNull(node70);
    }

    @Test
    public void test4504() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest9.test4504");
        com.google.javascript.rhino.Node[] nodeArray0 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node1 = com.google.javascript.rhino.IR.script(nodeArray0);
        com.google.javascript.rhino.Node node2 = com.google.javascript.rhino.IR.arraylit(nodeArray0);
        com.google.javascript.rhino.Node node3 = com.google.javascript.rhino.IR.block(nodeArray0);
        com.google.javascript.rhino.Node node4 = com.google.javascript.rhino.IR.block(node3);
        com.google.javascript.rhino.Node[] nodeArray5 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node6 = com.google.javascript.rhino.IR.script(nodeArray5);
        com.google.javascript.rhino.Node node7 = com.google.javascript.rhino.IR.arraylit(nodeArray5);
        com.google.javascript.rhino.Node node8 = com.google.javascript.rhino.IR.block(nodeArray5);
        com.google.javascript.rhino.Node node9 = com.google.javascript.rhino.IR.script(nodeArray5);
        com.google.javascript.rhino.Node node10 = com.google.javascript.rhino.IR.arraylit(nodeArray5);
        com.google.javascript.rhino.Node node11 = com.google.javascript.rhino.IR.not(node10);
        com.google.javascript.rhino.Node node12 = com.google.javascript.rhino.IR.thisNode();
        com.google.javascript.rhino.Node node13 = com.google.javascript.rhino.IR.or(node11, node12);
        com.google.javascript.rhino.Node[] nodeArray14 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node15 = com.google.javascript.rhino.IR.script(nodeArray14);
        com.google.javascript.rhino.Node node16 = com.google.javascript.rhino.IR.arraylit(nodeArray14);
        com.google.javascript.rhino.Node node17 = com.google.javascript.rhino.IR.block(nodeArray14);
        com.google.javascript.rhino.Node node18 = com.google.javascript.rhino.IR.script(nodeArray14);
        com.google.javascript.rhino.Node node19 = com.google.javascript.rhino.IR.switchNode(node13, nodeArray14);
        com.google.javascript.rhino.Node node20 = com.google.javascript.rhino.IR.arraylit(nodeArray14);
        com.google.javascript.rhino.Node node21 = com.google.javascript.rhino.IR.objectlit(nodeArray14);
        com.google.javascript.rhino.Node node22 = com.google.javascript.rhino.IR.objectlit(nodeArray14);
        com.google.javascript.rhino.Node node23 = com.google.javascript.rhino.IR.script(nodeArray14);
        // The following exception was thrown during execution in test generation
        try {
            com.google.javascript.rhino.Node node24 = com.google.javascript.rhino.IR.caseNode(node4, node23);
            org.junit.Assert.fail("Expected exception of type java.lang.IllegalStateException; message: null");
        } catch (java.lang.IllegalStateException e) {
            // Expected exception.
        }
        org.junit.Assert.assertNotNull(nodeArray0);
        org.junit.Assert.assertArrayEquals(nodeArray0, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node1);
        org.junit.Assert.assertNotNull(node2);
        org.junit.Assert.assertNotNull(node3);
        org.junit.Assert.assertNotNull(node4);
        org.junit.Assert.assertNotNull(nodeArray5);
        org.junit.Assert.assertArrayEquals(nodeArray5, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node6);
        org.junit.Assert.assertNotNull(node7);
        org.junit.Assert.assertNotNull(node8);
        org.junit.Assert.assertNotNull(node9);
        org.junit.Assert.assertNotNull(node10);
        org.junit.Assert.assertNotNull(node11);
        org.junit.Assert.assertNotNull(node12);
        org.junit.Assert.assertNotNull(node13);
        org.junit.Assert.assertNotNull(nodeArray14);
        org.junit.Assert.assertArrayEquals(nodeArray14, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node15);
        org.junit.Assert.assertNotNull(node16);
        org.junit.Assert.assertNotNull(node17);
        org.junit.Assert.assertNotNull(node18);
        org.junit.Assert.assertNotNull(node19);
        org.junit.Assert.assertNotNull(node20);
        org.junit.Assert.assertNotNull(node21);
        org.junit.Assert.assertNotNull(node22);
        org.junit.Assert.assertNotNull(node23);
    }

    @Test
    public void test4505() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest9.test4505");
        com.google.javascript.rhino.Node[] nodeArray0 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node1 = com.google.javascript.rhino.IR.script(nodeArray0);
        com.google.javascript.rhino.Node node2 = com.google.javascript.rhino.IR.arraylit(nodeArray0);
        com.google.javascript.rhino.Node node3 = com.google.javascript.rhino.IR.block(nodeArray0);
        com.google.javascript.rhino.Node node4 = com.google.javascript.rhino.IR.script(nodeArray0);
        com.google.javascript.rhino.Node node5 = com.google.javascript.rhino.IR.arraylit(nodeArray0);
        com.google.javascript.rhino.Node node6 = com.google.javascript.rhino.IR.not(node5);
        com.google.javascript.rhino.Node node7 = com.google.javascript.rhino.IR.thisNode();
        com.google.javascript.rhino.Node node8 = com.google.javascript.rhino.IR.or(node6, node7);
        com.google.javascript.rhino.Node[] nodeArray9 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node10 = com.google.javascript.rhino.IR.script(nodeArray9);
        com.google.javascript.rhino.Node node11 = com.google.javascript.rhino.IR.arraylit(nodeArray9);
        com.google.javascript.rhino.Node node12 = com.google.javascript.rhino.IR.block(nodeArray9);
        com.google.javascript.rhino.Node node13 = com.google.javascript.rhino.IR.script(nodeArray9);
        com.google.javascript.rhino.Node node14 = com.google.javascript.rhino.IR.switchNode(node8, nodeArray9);
        com.google.javascript.rhino.Node node15 = com.google.javascript.rhino.IR.paramList(nodeArray9);
        com.google.javascript.rhino.Node node16 = com.google.javascript.rhino.IR.block(nodeArray9);
        com.google.javascript.rhino.Node node17 = com.google.javascript.rhino.IR.block(nodeArray9);
        com.google.javascript.rhino.Node node18 = com.google.javascript.rhino.IR.paramList(nodeArray9);
        com.google.javascript.rhino.Node node19 = com.google.javascript.rhino.IR.arraylit(nodeArray9);
        com.google.javascript.rhino.Node node20 = com.google.javascript.rhino.IR.block(nodeArray9);
        com.google.javascript.rhino.Node node21 = com.google.javascript.rhino.IR.paramList(nodeArray9);
        org.junit.Assert.assertNotNull(nodeArray0);
        org.junit.Assert.assertArrayEquals(nodeArray0, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node1);
        org.junit.Assert.assertNotNull(node2);
        org.junit.Assert.assertNotNull(node3);
        org.junit.Assert.assertNotNull(node4);
        org.junit.Assert.assertNotNull(node5);
        org.junit.Assert.assertNotNull(node6);
        org.junit.Assert.assertNotNull(node7);
        org.junit.Assert.assertNotNull(node8);
        org.junit.Assert.assertNotNull(nodeArray9);
        org.junit.Assert.assertArrayEquals(nodeArray9, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node10);
        org.junit.Assert.assertNotNull(node11);
        org.junit.Assert.assertNotNull(node12);
        org.junit.Assert.assertNotNull(node13);
        org.junit.Assert.assertNotNull(node14);
        org.junit.Assert.assertNotNull(node15);
        org.junit.Assert.assertNotNull(node16);
        org.junit.Assert.assertNotNull(node17);
        org.junit.Assert.assertNotNull(node18);
        org.junit.Assert.assertNotNull(node19);
        org.junit.Assert.assertNotNull(node20);
        org.junit.Assert.assertNotNull(node21);
    }

    @Test
    public void test4506() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest9.test4506");
        com.google.javascript.rhino.Node[] nodeArray0 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node1 = com.google.javascript.rhino.IR.script(nodeArray0);
        com.google.javascript.rhino.Node node2 = com.google.javascript.rhino.IR.arraylit(nodeArray0);
        com.google.javascript.rhino.Node node3 = com.google.javascript.rhino.IR.block(nodeArray0);
        com.google.javascript.rhino.Node node4 = com.google.javascript.rhino.IR.script(nodeArray0);
        com.google.javascript.rhino.Node node5 = com.google.javascript.rhino.IR.arraylit(nodeArray0);
        com.google.javascript.rhino.Node node6 = com.google.javascript.rhino.IR.not(node5);
        com.google.javascript.rhino.Node node7 = com.google.javascript.rhino.IR.thisNode();
        com.google.javascript.rhino.Node node8 = com.google.javascript.rhino.IR.or(node6, node7);
        com.google.javascript.rhino.Node[] nodeArray9 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node10 = com.google.javascript.rhino.IR.script(nodeArray9);
        com.google.javascript.rhino.Node node11 = com.google.javascript.rhino.IR.arraylit(nodeArray9);
        com.google.javascript.rhino.Node node12 = com.google.javascript.rhino.IR.block(nodeArray9);
        com.google.javascript.rhino.Node node13 = com.google.javascript.rhino.IR.script(nodeArray9);
        com.google.javascript.rhino.Node node14 = com.google.javascript.rhino.IR.switchNode(node8, nodeArray9);
        com.google.javascript.rhino.Node node15 = com.google.javascript.rhino.IR.block(nodeArray9);
        com.google.javascript.rhino.Node node16 = com.google.javascript.rhino.IR.paramList(nodeArray9);
        com.google.javascript.rhino.Node node17 = com.google.javascript.rhino.IR.block(nodeArray9);
        org.junit.Assert.assertNotNull(nodeArray0);
        org.junit.Assert.assertArrayEquals(nodeArray0, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node1);
        org.junit.Assert.assertNotNull(node2);
        org.junit.Assert.assertNotNull(node3);
        org.junit.Assert.assertNotNull(node4);
        org.junit.Assert.assertNotNull(node5);
        org.junit.Assert.assertNotNull(node6);
        org.junit.Assert.assertNotNull(node7);
        org.junit.Assert.assertNotNull(node8);
        org.junit.Assert.assertNotNull(nodeArray9);
        org.junit.Assert.assertArrayEquals(nodeArray9, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node10);
        org.junit.Assert.assertNotNull(node11);
        org.junit.Assert.assertNotNull(node12);
        org.junit.Assert.assertNotNull(node13);
        org.junit.Assert.assertNotNull(node14);
        org.junit.Assert.assertNotNull(node15);
        org.junit.Assert.assertNotNull(node16);
        org.junit.Assert.assertNotNull(node17);
    }

    @Test
    public void test4507() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest9.test4507");
        com.google.javascript.rhino.Node[] nodeArray0 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node1 = com.google.javascript.rhino.IR.script(nodeArray0);
        com.google.javascript.rhino.Node node2 = com.google.javascript.rhino.IR.arraylit(nodeArray0);
        com.google.javascript.rhino.Node node3 = com.google.javascript.rhino.IR.block(nodeArray0);
        com.google.javascript.rhino.Node node4 = com.google.javascript.rhino.IR.script(nodeArray0);
        com.google.javascript.rhino.Node node5 = com.google.javascript.rhino.IR.arraylit(nodeArray0);
        com.google.javascript.rhino.Node node6 = com.google.javascript.rhino.IR.not(node5);
        com.google.javascript.rhino.Node node7 = com.google.javascript.rhino.IR.thisNode();
        com.google.javascript.rhino.Node node8 = com.google.javascript.rhino.IR.or(node6, node7);
        com.google.javascript.rhino.Node[] nodeArray9 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node10 = com.google.javascript.rhino.IR.script(nodeArray9);
        com.google.javascript.rhino.Node node11 = com.google.javascript.rhino.IR.arraylit(nodeArray9);
        com.google.javascript.rhino.Node node12 = com.google.javascript.rhino.IR.block(nodeArray9);
        com.google.javascript.rhino.Node node13 = com.google.javascript.rhino.IR.script(nodeArray9);
        com.google.javascript.rhino.Node node14 = com.google.javascript.rhino.IR.arraylit(nodeArray9);
        com.google.javascript.rhino.Node node15 = com.google.javascript.rhino.IR.not(node14);
        com.google.javascript.rhino.Node node17 = com.google.javascript.rhino.IR.number((double) 0.0f);
        com.google.javascript.rhino.Node node18 = com.google.javascript.rhino.IR.or(node15, node17);
        com.google.javascript.rhino.Node node19 = com.google.javascript.rhino.IR.sheq(node8, node18);
        com.google.javascript.rhino.Node[] nodeArray20 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node21 = com.google.javascript.rhino.IR.script(nodeArray20);
        com.google.javascript.rhino.Node node22 = com.google.javascript.rhino.IR.arraylit(nodeArray20);
        com.google.javascript.rhino.Node node23 = com.google.javascript.rhino.IR.block(nodeArray20);
        com.google.javascript.rhino.Node node24 = com.google.javascript.rhino.IR.script(nodeArray20);
        com.google.javascript.rhino.Node node25 = com.google.javascript.rhino.IR.arraylit(nodeArray20);
        com.google.javascript.rhino.Node node26 = com.google.javascript.rhino.IR.not(node25);
        com.google.javascript.rhino.Node node28 = com.google.javascript.rhino.IR.number((double) 0.0f);
        com.google.javascript.rhino.Node node29 = com.google.javascript.rhino.IR.or(node26, node28);
        com.google.javascript.rhino.Node node30 = com.google.javascript.rhino.IR.neg(node29);
        com.google.javascript.rhino.Node[] nodeArray31 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node32 = com.google.javascript.rhino.IR.script(nodeArray31);
        com.google.javascript.rhino.Node node33 = com.google.javascript.rhino.IR.arraylit(nodeArray31);
        com.google.javascript.rhino.Node node34 = com.google.javascript.rhino.IR.block(nodeArray31);
        com.google.javascript.rhino.Node node35 = com.google.javascript.rhino.IR.block(node34);
        com.google.javascript.rhino.Node[] nodeArray36 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node37 = com.google.javascript.rhino.IR.script(nodeArray36);
        com.google.javascript.rhino.Node node38 = com.google.javascript.rhino.IR.arraylit(nodeArray36);
        com.google.javascript.rhino.Node node39 = com.google.javascript.rhino.IR.block(nodeArray36);
        com.google.javascript.rhino.Node node40 = com.google.javascript.rhino.IR.script(nodeArray36);
        com.google.javascript.rhino.Node node41 = com.google.javascript.rhino.IR.arraylit(nodeArray36);
        com.google.javascript.rhino.Node node42 = com.google.javascript.rhino.IR.script(nodeArray36);
        com.google.javascript.rhino.Node node43 = com.google.javascript.rhino.IR.script(nodeArray36);
        com.google.javascript.rhino.Node node44 = com.google.javascript.rhino.IR.block(nodeArray36);
        com.google.javascript.rhino.Node node45 = com.google.javascript.rhino.IR.newNode(node35, nodeArray36);
        com.google.javascript.rhino.Node node46 = com.google.javascript.rhino.IR.sheq(node30, node45);
        com.google.javascript.rhino.Node node47 = com.google.javascript.rhino.IR.comma(node19, node46);
        com.google.javascript.rhino.Node[] nodeArray48 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node49 = com.google.javascript.rhino.IR.script(nodeArray48);
        com.google.javascript.rhino.Node node50 = com.google.javascript.rhino.IR.arraylit(nodeArray48);
        com.google.javascript.rhino.Node node51 = com.google.javascript.rhino.IR.block(nodeArray48);
        com.google.javascript.rhino.Node[] nodeArray52 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node53 = com.google.javascript.rhino.IR.script(nodeArray52);
        com.google.javascript.rhino.Node node54 = com.google.javascript.rhino.IR.arraylit(nodeArray52);
        com.google.javascript.rhino.Node node55 = com.google.javascript.rhino.IR.block(nodeArray52);
        com.google.javascript.rhino.Node node56 = com.google.javascript.rhino.IR.script(nodeArray52);
        com.google.javascript.rhino.Node node57 = com.google.javascript.rhino.IR.arraylit(nodeArray52);
        com.google.javascript.rhino.Node node58 = com.google.javascript.rhino.IR.not(node57);
        com.google.javascript.rhino.Node node59 = com.google.javascript.rhino.IR.thisNode();
        com.google.javascript.rhino.Node node60 = com.google.javascript.rhino.IR.or(node58, node59);
        com.google.javascript.rhino.Node[] nodeArray61 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node62 = com.google.javascript.rhino.IR.script(nodeArray61);
        com.google.javascript.rhino.Node node63 = com.google.javascript.rhino.IR.arraylit(nodeArray61);
        com.google.javascript.rhino.Node node64 = com.google.javascript.rhino.IR.block(nodeArray61);
        com.google.javascript.rhino.Node node65 = com.google.javascript.rhino.IR.script(nodeArray61);
        com.google.javascript.rhino.Node node66 = com.google.javascript.rhino.IR.switchNode(node60, nodeArray61);
        com.google.javascript.rhino.Node node67 = com.google.javascript.rhino.IR.paramList(nodeArray61);
        com.google.javascript.rhino.Node node68 = com.google.javascript.rhino.IR.block(nodeArray61);
        com.google.javascript.rhino.Node node69 = com.google.javascript.rhino.IR.block(nodeArray61);
        com.google.javascript.rhino.Node node70 = com.google.javascript.rhino.IR.paramList(nodeArray61);
        com.google.javascript.rhino.Node node71 = com.google.javascript.rhino.IR.arraylit(nodeArray61);
        com.google.javascript.rhino.Node node72 = com.google.javascript.rhino.IR.newNode(node51, nodeArray61);
        com.google.javascript.rhino.Node node73 = com.google.javascript.rhino.IR.paramList(nodeArray61);
        com.google.javascript.rhino.Node node74 = com.google.javascript.rhino.IR.script(nodeArray61);
        com.google.javascript.rhino.Node node75 = com.google.javascript.rhino.IR.paramList(nodeArray61);
        com.google.javascript.rhino.Node node76 = com.google.javascript.rhino.IR.call(node47, nodeArray61);
        org.junit.Assert.assertNotNull(nodeArray0);
        org.junit.Assert.assertArrayEquals(nodeArray0, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node1);
        org.junit.Assert.assertNotNull(node2);
        org.junit.Assert.assertNotNull(node3);
        org.junit.Assert.assertNotNull(node4);
        org.junit.Assert.assertNotNull(node5);
        org.junit.Assert.assertNotNull(node6);
        org.junit.Assert.assertNotNull(node7);
        org.junit.Assert.assertNotNull(node8);
        org.junit.Assert.assertNotNull(nodeArray9);
        org.junit.Assert.assertArrayEquals(nodeArray9, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node10);
        org.junit.Assert.assertNotNull(node11);
        org.junit.Assert.assertNotNull(node12);
        org.junit.Assert.assertNotNull(node13);
        org.junit.Assert.assertNotNull(node14);
        org.junit.Assert.assertNotNull(node15);
        org.junit.Assert.assertNotNull(node17);
        org.junit.Assert.assertNotNull(node18);
        org.junit.Assert.assertNotNull(node19);
        org.junit.Assert.assertNotNull(nodeArray20);
        org.junit.Assert.assertArrayEquals(nodeArray20, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node21);
        org.junit.Assert.assertNotNull(node22);
        org.junit.Assert.assertNotNull(node23);
        org.junit.Assert.assertNotNull(node24);
        org.junit.Assert.assertNotNull(node25);
        org.junit.Assert.assertNotNull(node26);
        org.junit.Assert.assertNotNull(node28);
        org.junit.Assert.assertNotNull(node29);
        org.junit.Assert.assertNotNull(node30);
        org.junit.Assert.assertNotNull(nodeArray31);
        org.junit.Assert.assertArrayEquals(nodeArray31, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node32);
        org.junit.Assert.assertNotNull(node33);
        org.junit.Assert.assertNotNull(node34);
        org.junit.Assert.assertNotNull(node35);
        org.junit.Assert.assertNotNull(nodeArray36);
        org.junit.Assert.assertArrayEquals(nodeArray36, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node37);
        org.junit.Assert.assertNotNull(node38);
        org.junit.Assert.assertNotNull(node39);
        org.junit.Assert.assertNotNull(node40);
        org.junit.Assert.assertNotNull(node41);
        org.junit.Assert.assertNotNull(node42);
        org.junit.Assert.assertNotNull(node43);
        org.junit.Assert.assertNotNull(node44);
        org.junit.Assert.assertNotNull(node45);
        org.junit.Assert.assertNotNull(node46);
        org.junit.Assert.assertNotNull(node47);
        org.junit.Assert.assertNotNull(nodeArray48);
        org.junit.Assert.assertArrayEquals(nodeArray48, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node49);
        org.junit.Assert.assertNotNull(node50);
        org.junit.Assert.assertNotNull(node51);
        org.junit.Assert.assertNotNull(nodeArray52);
        org.junit.Assert.assertArrayEquals(nodeArray52, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node53);
        org.junit.Assert.assertNotNull(node54);
        org.junit.Assert.assertNotNull(node55);
        org.junit.Assert.assertNotNull(node56);
        org.junit.Assert.assertNotNull(node57);
        org.junit.Assert.assertNotNull(node58);
        org.junit.Assert.assertNotNull(node59);
        org.junit.Assert.assertNotNull(node60);
        org.junit.Assert.assertNotNull(nodeArray61);
        org.junit.Assert.assertArrayEquals(nodeArray61, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node62);
        org.junit.Assert.assertNotNull(node63);
        org.junit.Assert.assertNotNull(node64);
        org.junit.Assert.assertNotNull(node65);
        org.junit.Assert.assertNotNull(node66);
        org.junit.Assert.assertNotNull(node67);
        org.junit.Assert.assertNotNull(node68);
        org.junit.Assert.assertNotNull(node69);
        org.junit.Assert.assertNotNull(node70);
        org.junit.Assert.assertNotNull(node71);
        org.junit.Assert.assertNotNull(node72);
        org.junit.Assert.assertNotNull(node73);
        org.junit.Assert.assertNotNull(node74);
        org.junit.Assert.assertNotNull(node75);
        org.junit.Assert.assertNotNull(node76);
    }

    @Test
    public void test4508() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest9.test4508");
        com.google.javascript.rhino.Node node0 = com.google.javascript.rhino.IR.trueNode();
        com.google.javascript.rhino.Node node1 = com.google.javascript.rhino.IR.trueNode();
        com.google.javascript.rhino.Node node2 = com.google.javascript.rhino.IR.comma(node0, node1);
        com.google.javascript.rhino.Node node3 = com.google.javascript.rhino.IR.neg(node2);
        com.google.javascript.rhino.Node node5 = com.google.javascript.rhino.IR.name("hi!");
        com.google.javascript.rhino.Node[] nodeArray6 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node7 = com.google.javascript.rhino.IR.script(nodeArray6);
        com.google.javascript.rhino.Node node8 = com.google.javascript.rhino.IR.arraylit(nodeArray6);
        com.google.javascript.rhino.Node node9 = com.google.javascript.rhino.IR.block(nodeArray6);
        com.google.javascript.rhino.Node node10 = com.google.javascript.rhino.IR.script(nodeArray6);
        com.google.javascript.rhino.Node node11 = com.google.javascript.rhino.IR.arraylit(nodeArray6);
        com.google.javascript.rhino.Node node12 = com.google.javascript.rhino.IR.newNode(node5, nodeArray6);
        com.google.javascript.rhino.Node node13 = com.google.javascript.rhino.IR.newNode(node3, nodeArray6);
        com.google.javascript.rhino.Node[] nodeArray14 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node15 = com.google.javascript.rhino.IR.script(nodeArray14);
        com.google.javascript.rhino.Node node16 = com.google.javascript.rhino.IR.arraylit(nodeArray14);
        com.google.javascript.rhino.Node node17 = com.google.javascript.rhino.IR.block(nodeArray14);
        com.google.javascript.rhino.Node node18 = com.google.javascript.rhino.IR.newNode(node13, nodeArray14);
        com.google.javascript.rhino.Node node19 = com.google.javascript.rhino.IR.arraylit(nodeArray14);
        com.google.javascript.rhino.Node node20 = com.google.javascript.rhino.IR.trueNode();
        com.google.javascript.rhino.Node node21 = com.google.javascript.rhino.IR.trueNode();
        com.google.javascript.rhino.Node node22 = com.google.javascript.rhino.IR.comma(node20, node21);
        com.google.javascript.rhino.Node node23 = com.google.javascript.rhino.IR.neg(node22);
        com.google.javascript.rhino.Node node25 = com.google.javascript.rhino.IR.name("hi!");
        com.google.javascript.rhino.Node[] nodeArray26 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node27 = com.google.javascript.rhino.IR.script(nodeArray26);
        com.google.javascript.rhino.Node node28 = com.google.javascript.rhino.IR.arraylit(nodeArray26);
        com.google.javascript.rhino.Node node29 = com.google.javascript.rhino.IR.block(nodeArray26);
        com.google.javascript.rhino.Node node30 = com.google.javascript.rhino.IR.script(nodeArray26);
        com.google.javascript.rhino.Node node31 = com.google.javascript.rhino.IR.arraylit(nodeArray26);
        com.google.javascript.rhino.Node node32 = com.google.javascript.rhino.IR.newNode(node25, nodeArray26);
        com.google.javascript.rhino.Node node33 = com.google.javascript.rhino.IR.newNode(node23, nodeArray26);
        com.google.javascript.rhino.Node[] nodeArray34 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node35 = com.google.javascript.rhino.IR.script(nodeArray34);
        com.google.javascript.rhino.Node node36 = com.google.javascript.rhino.IR.arraylit(nodeArray34);
        com.google.javascript.rhino.Node node37 = com.google.javascript.rhino.IR.block(nodeArray34);
        com.google.javascript.rhino.Node node38 = com.google.javascript.rhino.IR.newNode(node33, nodeArray34);
        com.google.javascript.rhino.Node node39 = com.google.javascript.rhino.IR.arraylit(nodeArray34);
        com.google.javascript.rhino.Node node40 = com.google.javascript.rhino.IR.newNode(node19, nodeArray34);
        com.google.javascript.rhino.Node node41 = com.google.javascript.rhino.IR.block(nodeArray34);
        com.google.javascript.rhino.Node node42 = com.google.javascript.rhino.IR.paramList(nodeArray34);
        com.google.javascript.rhino.Node node43 = com.google.javascript.rhino.IR.objectlit(nodeArray34);
        com.google.javascript.rhino.Node node44 = com.google.javascript.rhino.IR.block(nodeArray34);
        org.junit.Assert.assertNotNull(node0);
        org.junit.Assert.assertNotNull(node1);
        org.junit.Assert.assertNotNull(node2);
        org.junit.Assert.assertNotNull(node3);
        org.junit.Assert.assertNotNull(node5);
        org.junit.Assert.assertNotNull(nodeArray6);
        org.junit.Assert.assertArrayEquals(nodeArray6, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node7);
        org.junit.Assert.assertNotNull(node8);
        org.junit.Assert.assertNotNull(node9);
        org.junit.Assert.assertNotNull(node10);
        org.junit.Assert.assertNotNull(node11);
        org.junit.Assert.assertNotNull(node12);
        org.junit.Assert.assertNotNull(node13);
        org.junit.Assert.assertNotNull(nodeArray14);
        org.junit.Assert.assertArrayEquals(nodeArray14, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node15);
        org.junit.Assert.assertNotNull(node16);
        org.junit.Assert.assertNotNull(node17);
        org.junit.Assert.assertNotNull(node18);
        org.junit.Assert.assertNotNull(node19);
        org.junit.Assert.assertNotNull(node20);
        org.junit.Assert.assertNotNull(node21);
        org.junit.Assert.assertNotNull(node22);
        org.junit.Assert.assertNotNull(node23);
        org.junit.Assert.assertNotNull(node25);
        org.junit.Assert.assertNotNull(nodeArray26);
        org.junit.Assert.assertArrayEquals(nodeArray26, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node27);
        org.junit.Assert.assertNotNull(node28);
        org.junit.Assert.assertNotNull(node29);
        org.junit.Assert.assertNotNull(node30);
        org.junit.Assert.assertNotNull(node31);
        org.junit.Assert.assertNotNull(node32);
        org.junit.Assert.assertNotNull(node33);
        org.junit.Assert.assertNotNull(nodeArray34);
        org.junit.Assert.assertArrayEquals(nodeArray34, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node35);
        org.junit.Assert.assertNotNull(node36);
        org.junit.Assert.assertNotNull(node37);
        org.junit.Assert.assertNotNull(node38);
        org.junit.Assert.assertNotNull(node39);
        org.junit.Assert.assertNotNull(node40);
        org.junit.Assert.assertNotNull(node41);
        org.junit.Assert.assertNotNull(node42);
        org.junit.Assert.assertNotNull(node43);
        org.junit.Assert.assertNotNull(node44);
    }

    @Test
    public void test4509() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest9.test4509");
        com.google.javascript.rhino.Node[] nodeArray0 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node1 = com.google.javascript.rhino.IR.script(nodeArray0);
        com.google.javascript.rhino.Node node2 = com.google.javascript.rhino.IR.arraylit(nodeArray0);
        com.google.javascript.rhino.Node node3 = com.google.javascript.rhino.IR.block(nodeArray0);
        com.google.javascript.rhino.Node node4 = com.google.javascript.rhino.IR.script(nodeArray0);
        com.google.javascript.rhino.Node node5 = com.google.javascript.rhino.IR.arraylit(nodeArray0);
        com.google.javascript.rhino.Node node6 = com.google.javascript.rhino.IR.not(node5);
        com.google.javascript.rhino.Node node7 = com.google.javascript.rhino.IR.thisNode();
        com.google.javascript.rhino.Node node8 = com.google.javascript.rhino.IR.or(node6, node7);
        com.google.javascript.rhino.Node[] nodeArray9 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node10 = com.google.javascript.rhino.IR.script(nodeArray9);
        com.google.javascript.rhino.Node node11 = com.google.javascript.rhino.IR.arraylit(nodeArray9);
        com.google.javascript.rhino.Node node12 = com.google.javascript.rhino.IR.block(nodeArray9);
        com.google.javascript.rhino.Node node13 = com.google.javascript.rhino.IR.script(nodeArray9);
        com.google.javascript.rhino.Node node14 = com.google.javascript.rhino.IR.switchNode(node8, nodeArray9);
        com.google.javascript.rhino.Node node15 = com.google.javascript.rhino.IR.paramList(nodeArray9);
        com.google.javascript.rhino.Node node17 = com.google.javascript.rhino.IR.name("hi!");
        com.google.javascript.rhino.Node[] nodeArray18 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node19 = com.google.javascript.rhino.IR.script(nodeArray18);
        com.google.javascript.rhino.Node node20 = com.google.javascript.rhino.IR.arraylit(nodeArray18);
        com.google.javascript.rhino.Node node21 = com.google.javascript.rhino.IR.block(nodeArray18);
        com.google.javascript.rhino.Node node22 = com.google.javascript.rhino.IR.script(nodeArray18);
        com.google.javascript.rhino.Node node23 = com.google.javascript.rhino.IR.arraylit(nodeArray18);
        com.google.javascript.rhino.Node node24 = com.google.javascript.rhino.IR.newNode(node17, nodeArray18);
        com.google.javascript.rhino.Node node25 = com.google.javascript.rhino.IR.paramList(nodeArray18);
        com.google.javascript.rhino.Node node26 = com.google.javascript.rhino.IR.arraylit(nodeArray18);
        com.google.javascript.rhino.Node node27 = com.google.javascript.rhino.IR.block(nodeArray18);
        com.google.javascript.rhino.Node node28 = com.google.javascript.rhino.IR.script(nodeArray18);
        com.google.javascript.rhino.Node node29 = com.google.javascript.rhino.IR.paramList(nodeArray18);
        com.google.javascript.rhino.Node node30 = com.google.javascript.rhino.IR.call(node15, nodeArray18);
        // The following exception was thrown during execution in test generation
        try {
            com.google.javascript.rhino.Node node31 = com.google.javascript.rhino.IR.breakNode(node30);
            org.junit.Assert.fail("Expected exception of type java.lang.IllegalStateException; message: null");
        } catch (java.lang.IllegalStateException e) {
            // Expected exception.
        }
        org.junit.Assert.assertNotNull(nodeArray0);
        org.junit.Assert.assertArrayEquals(nodeArray0, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node1);
        org.junit.Assert.assertNotNull(node2);
        org.junit.Assert.assertNotNull(node3);
        org.junit.Assert.assertNotNull(node4);
        org.junit.Assert.assertNotNull(node5);
        org.junit.Assert.assertNotNull(node6);
        org.junit.Assert.assertNotNull(node7);
        org.junit.Assert.assertNotNull(node8);
        org.junit.Assert.assertNotNull(nodeArray9);
        org.junit.Assert.assertArrayEquals(nodeArray9, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node10);
        org.junit.Assert.assertNotNull(node11);
        org.junit.Assert.assertNotNull(node12);
        org.junit.Assert.assertNotNull(node13);
        org.junit.Assert.assertNotNull(node14);
        org.junit.Assert.assertNotNull(node15);
        org.junit.Assert.assertNotNull(node17);
        org.junit.Assert.assertNotNull(nodeArray18);
        org.junit.Assert.assertArrayEquals(nodeArray18, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node19);
        org.junit.Assert.assertNotNull(node20);
        org.junit.Assert.assertNotNull(node21);
        org.junit.Assert.assertNotNull(node22);
        org.junit.Assert.assertNotNull(node23);
        org.junit.Assert.assertNotNull(node24);
        org.junit.Assert.assertNotNull(node25);
        org.junit.Assert.assertNotNull(node26);
        org.junit.Assert.assertNotNull(node27);
        org.junit.Assert.assertNotNull(node28);
        org.junit.Assert.assertNotNull(node29);
        org.junit.Assert.assertNotNull(node30);
    }

    @Test
    public void test4510() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest9.test4510");
        com.google.javascript.rhino.Node[] nodeArray0 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node1 = com.google.javascript.rhino.IR.script(nodeArray0);
        com.google.javascript.rhino.Node node2 = com.google.javascript.rhino.IR.arraylit(nodeArray0);
        com.google.javascript.rhino.Node node3 = com.google.javascript.rhino.IR.paramList(nodeArray0);
        com.google.javascript.rhino.Node node4 = com.google.javascript.rhino.IR.block(nodeArray0);
        com.google.javascript.rhino.Node node5 = com.google.javascript.rhino.IR.arraylit(nodeArray0);
        com.google.javascript.rhino.Node node6 = com.google.javascript.rhino.IR.block(nodeArray0);
        com.google.javascript.rhino.Node node8 = com.google.javascript.rhino.IR.string("");
        com.google.javascript.rhino.Node node9 = com.google.javascript.rhino.IR.voidNode(node8);
        com.google.javascript.rhino.Node node10 = com.google.javascript.rhino.IR.trueNode();
        com.google.javascript.rhino.Node node11 = com.google.javascript.rhino.IR.trueNode();
        com.google.javascript.rhino.Node node12 = com.google.javascript.rhino.IR.comma(node10, node11);
        com.google.javascript.rhino.Node node13 = com.google.javascript.rhino.IR.neg(node12);
        com.google.javascript.rhino.Node node14 = com.google.javascript.rhino.IR.sheq(node9, node13);
        // The following exception was thrown during execution in test generation
        try {
            com.google.javascript.rhino.Node node15 = com.google.javascript.rhino.IR.assign(node6, node14);
            org.junit.Assert.fail("Expected exception of type java.lang.IllegalStateException; message: null");
        } catch (java.lang.IllegalStateException e) {
            // Expected exception.
        }
        org.junit.Assert.assertNotNull(nodeArray0);
        org.junit.Assert.assertArrayEquals(nodeArray0, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node1);
        org.junit.Assert.assertNotNull(node2);
        org.junit.Assert.assertNotNull(node3);
        org.junit.Assert.assertNotNull(node4);
        org.junit.Assert.assertNotNull(node5);
        org.junit.Assert.assertNotNull(node6);
        org.junit.Assert.assertNotNull(node8);
        org.junit.Assert.assertNotNull(node9);
        org.junit.Assert.assertNotNull(node10);
        org.junit.Assert.assertNotNull(node11);
        org.junit.Assert.assertNotNull(node12);
        org.junit.Assert.assertNotNull(node13);
        org.junit.Assert.assertNotNull(node14);
    }

    @Test
    public void test4511() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest9.test4511");
        com.google.javascript.rhino.Node node0 = com.google.javascript.rhino.IR.trueNode();
        com.google.javascript.rhino.Node node1 = com.google.javascript.rhino.IR.trueNode();
        com.google.javascript.rhino.Node node2 = com.google.javascript.rhino.IR.comma(node0, node1);
        com.google.javascript.rhino.Node node3 = com.google.javascript.rhino.IR.neg(node2);
        com.google.javascript.rhino.Node node5 = com.google.javascript.rhino.IR.name("hi!");
        com.google.javascript.rhino.Node[] nodeArray6 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node7 = com.google.javascript.rhino.IR.script(nodeArray6);
        com.google.javascript.rhino.Node node8 = com.google.javascript.rhino.IR.arraylit(nodeArray6);
        com.google.javascript.rhino.Node node9 = com.google.javascript.rhino.IR.block(nodeArray6);
        com.google.javascript.rhino.Node node10 = com.google.javascript.rhino.IR.script(nodeArray6);
        com.google.javascript.rhino.Node node11 = com.google.javascript.rhino.IR.arraylit(nodeArray6);
        com.google.javascript.rhino.Node node12 = com.google.javascript.rhino.IR.newNode(node5, nodeArray6);
        com.google.javascript.rhino.Node node13 = com.google.javascript.rhino.IR.newNode(node3, nodeArray6);
        com.google.javascript.rhino.Node node14 = com.google.javascript.rhino.IR.trueNode();
        com.google.javascript.rhino.Node node16 = com.google.javascript.rhino.IR.string("");
        com.google.javascript.rhino.Node node17 = com.google.javascript.rhino.IR.trueNode();
        com.google.javascript.rhino.Node node18 = com.google.javascript.rhino.IR.hook(node14, node16, node17);
        com.google.javascript.rhino.Node node20 = com.google.javascript.rhino.IR.name("hi!");
        com.google.javascript.rhino.Node[] nodeArray21 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node22 = com.google.javascript.rhino.IR.script(nodeArray21);
        com.google.javascript.rhino.Node node23 = com.google.javascript.rhino.IR.arraylit(nodeArray21);
        com.google.javascript.rhino.Node node24 = com.google.javascript.rhino.IR.block(nodeArray21);
        com.google.javascript.rhino.Node node25 = com.google.javascript.rhino.IR.script(nodeArray21);
        com.google.javascript.rhino.Node node26 = com.google.javascript.rhino.IR.arraylit(nodeArray21);
        com.google.javascript.rhino.Node node27 = com.google.javascript.rhino.IR.newNode(node20, nodeArray21);
        com.google.javascript.rhino.Node node28 = com.google.javascript.rhino.IR.paramList(nodeArray21);
        com.google.javascript.rhino.Node node29 = com.google.javascript.rhino.IR.arraylit(nodeArray21);
        com.google.javascript.rhino.Node node30 = com.google.javascript.rhino.IR.script(nodeArray21);
        com.google.javascript.rhino.Node node31 = com.google.javascript.rhino.IR.paramList(nodeArray21);
        com.google.javascript.rhino.Node node32 = com.google.javascript.rhino.IR.newNode(node18, nodeArray21);
        com.google.javascript.rhino.Node node33 = com.google.javascript.rhino.IR.add(node13, node32);
        org.junit.Assert.assertNotNull(node0);
        org.junit.Assert.assertNotNull(node1);
        org.junit.Assert.assertNotNull(node2);
        org.junit.Assert.assertNotNull(node3);
        org.junit.Assert.assertNotNull(node5);
        org.junit.Assert.assertNotNull(nodeArray6);
        org.junit.Assert.assertArrayEquals(nodeArray6, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node7);
        org.junit.Assert.assertNotNull(node8);
        org.junit.Assert.assertNotNull(node9);
        org.junit.Assert.assertNotNull(node10);
        org.junit.Assert.assertNotNull(node11);
        org.junit.Assert.assertNotNull(node12);
        org.junit.Assert.assertNotNull(node13);
        org.junit.Assert.assertNotNull(node14);
        org.junit.Assert.assertNotNull(node16);
        org.junit.Assert.assertNotNull(node17);
        org.junit.Assert.assertNotNull(node18);
        org.junit.Assert.assertNotNull(node20);
        org.junit.Assert.assertNotNull(nodeArray21);
        org.junit.Assert.assertArrayEquals(nodeArray21, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node22);
        org.junit.Assert.assertNotNull(node23);
        org.junit.Assert.assertNotNull(node24);
        org.junit.Assert.assertNotNull(node25);
        org.junit.Assert.assertNotNull(node26);
        org.junit.Assert.assertNotNull(node27);
        org.junit.Assert.assertNotNull(node28);
        org.junit.Assert.assertNotNull(node29);
        org.junit.Assert.assertNotNull(node30);
        org.junit.Assert.assertNotNull(node31);
        org.junit.Assert.assertNotNull(node32);
        org.junit.Assert.assertNotNull(node33);
    }

    @Test
    public void test4512() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest9.test4512");
        com.google.javascript.rhino.Node[] nodeArray0 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node1 = com.google.javascript.rhino.IR.script(nodeArray0);
        com.google.javascript.rhino.Node node2 = com.google.javascript.rhino.IR.block(nodeArray0);
        com.google.javascript.rhino.Node node3 = com.google.javascript.rhino.IR.objectlit(nodeArray0);
        com.google.javascript.rhino.Node node4 = com.google.javascript.rhino.IR.script(nodeArray0);
        com.google.javascript.rhino.Node node5 = com.google.javascript.rhino.IR.block(nodeArray0);
        com.google.javascript.rhino.Node node6 = com.google.javascript.rhino.IR.arraylit(nodeArray0);
        com.google.javascript.rhino.Node node7 = com.google.javascript.rhino.IR.trueNode();
        com.google.javascript.rhino.Node node8 = com.google.javascript.rhino.IR.trueNode();
        com.google.javascript.rhino.Node node9 = com.google.javascript.rhino.IR.comma(node7, node8);
        com.google.javascript.rhino.Node node10 = com.google.javascript.rhino.IR.neg(node9);
        com.google.javascript.rhino.Node node12 = com.google.javascript.rhino.IR.name("hi!");
        com.google.javascript.rhino.Node[] nodeArray13 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node14 = com.google.javascript.rhino.IR.script(nodeArray13);
        com.google.javascript.rhino.Node node15 = com.google.javascript.rhino.IR.arraylit(nodeArray13);
        com.google.javascript.rhino.Node node16 = com.google.javascript.rhino.IR.block(nodeArray13);
        com.google.javascript.rhino.Node node17 = com.google.javascript.rhino.IR.script(nodeArray13);
        com.google.javascript.rhino.Node node18 = com.google.javascript.rhino.IR.arraylit(nodeArray13);
        com.google.javascript.rhino.Node node19 = com.google.javascript.rhino.IR.newNode(node12, nodeArray13);
        com.google.javascript.rhino.Node node20 = com.google.javascript.rhino.IR.newNode(node10, nodeArray13);
        com.google.javascript.rhino.Node[] nodeArray21 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node22 = com.google.javascript.rhino.IR.script(nodeArray21);
        com.google.javascript.rhino.Node node23 = com.google.javascript.rhino.IR.arraylit(nodeArray21);
        com.google.javascript.rhino.Node node24 = com.google.javascript.rhino.IR.block(nodeArray21);
        com.google.javascript.rhino.Node node25 = com.google.javascript.rhino.IR.newNode(node20, nodeArray21);
        com.google.javascript.rhino.Node node26 = com.google.javascript.rhino.IR.returnNode(node25);
        com.google.javascript.rhino.Node node28 = com.google.javascript.rhino.IR.name("hi!");
        com.google.javascript.rhino.Node[] nodeArray29 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node30 = com.google.javascript.rhino.IR.script(nodeArray29);
        com.google.javascript.rhino.Node node31 = com.google.javascript.rhino.IR.arraylit(nodeArray29);
        com.google.javascript.rhino.Node node32 = com.google.javascript.rhino.IR.block(nodeArray29);
        com.google.javascript.rhino.Node node33 = com.google.javascript.rhino.IR.script(nodeArray29);
        com.google.javascript.rhino.Node node34 = com.google.javascript.rhino.IR.arraylit(nodeArray29);
        com.google.javascript.rhino.Node node35 = com.google.javascript.rhino.IR.newNode(node28, nodeArray29);
        com.google.javascript.rhino.Node node36 = com.google.javascript.rhino.IR.paramList(nodeArray29);
        com.google.javascript.rhino.Node[] nodeArray37 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node38 = com.google.javascript.rhino.IR.script(nodeArray37);
        com.google.javascript.rhino.Node node39 = com.google.javascript.rhino.IR.arraylit(nodeArray37);
        com.google.javascript.rhino.Node node40 = com.google.javascript.rhino.IR.block(nodeArray37);
        com.google.javascript.rhino.Node node41 = com.google.javascript.rhino.IR.script(nodeArray37);
        com.google.javascript.rhino.Node node42 = com.google.javascript.rhino.IR.arraylit(nodeArray37);
        com.google.javascript.rhino.Node node43 = com.google.javascript.rhino.IR.not(node42);
        com.google.javascript.rhino.Node node44 = com.google.javascript.rhino.IR.thisNode();
        com.google.javascript.rhino.Node node45 = com.google.javascript.rhino.IR.or(node43, node44);
        com.google.javascript.rhino.Node[] nodeArray46 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node47 = com.google.javascript.rhino.IR.script(nodeArray46);
        com.google.javascript.rhino.Node node48 = com.google.javascript.rhino.IR.arraylit(nodeArray46);
        com.google.javascript.rhino.Node node49 = com.google.javascript.rhino.IR.block(nodeArray46);
        com.google.javascript.rhino.Node node50 = com.google.javascript.rhino.IR.script(nodeArray46);
        com.google.javascript.rhino.Node node51 = com.google.javascript.rhino.IR.switchNode(node45, nodeArray46);
        com.google.javascript.rhino.Node node52 = com.google.javascript.rhino.IR.block(nodeArray46);
        com.google.javascript.rhino.Node node53 = com.google.javascript.rhino.IR.newNode(node36, nodeArray46);
        com.google.javascript.rhino.Node node54 = com.google.javascript.rhino.IR.block(nodeArray46);
        com.google.javascript.rhino.Node node55 = com.google.javascript.rhino.IR.call(node26, nodeArray46);
        com.google.javascript.rhino.Node[] nodeArray56 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node57 = com.google.javascript.rhino.IR.script(nodeArray56);
        com.google.javascript.rhino.Node node58 = com.google.javascript.rhino.IR.arraylit(nodeArray56);
        com.google.javascript.rhino.Node node59 = com.google.javascript.rhino.IR.block(nodeArray56);
        com.google.javascript.rhino.Node node60 = com.google.javascript.rhino.IR.script(nodeArray56);
        com.google.javascript.rhino.Node node61 = com.google.javascript.rhino.IR.arraylit(nodeArray56);
        com.google.javascript.rhino.Node node62 = com.google.javascript.rhino.IR.not(node61);
        com.google.javascript.rhino.Node node64 = com.google.javascript.rhino.IR.name("hi!");
        com.google.javascript.rhino.Node[] nodeArray65 = new com.google.javascript.rhino.Node[] {};
        com.google.javascript.rhino.Node node66 = com.google.javascript.rhino.IR.script(nodeArray65);
        com.google.javascript.rhino.Node node67 = com.google.javascript.rhino.IR.arraylit(nodeArray65);
        com.google.javascript.rhino.Node node68 = com.google.javascript.rhino.IR.block(nodeArray65);
        com.google.javascript.rhino.Node node69 = com.google.javascript.rhino.IR.script(nodeArray65);
        com.google.javascript.rhino.Node node70 = com.google.javascript.rhino.IR.arraylit(nodeArray65);
        com.google.javascript.rhino.Node node71 = com.google.javascript.rhino.IR.newNode(node64, nodeArray65);
        com.google.javascript.rhino.Node node72 = com.google.javascript.rhino.IR.call(node62, nodeArray65);
        com.google.javascript.rhino.Node node73 = com.google.javascript.rhino.IR.block(nodeArray65);
        com.google.javascript.rhino.Node node74 = com.google.javascript.rhino.IR.block(nodeArray65);
        com.google.javascript.rhino.Node node75 = com.google.javascript.rhino.IR.objectlit(nodeArray65);
        com.google.javascript.rhino.Node node76 = com.google.javascript.rhino.IR.newNode(node55, nodeArray65);
        // The following exception was thrown during execution in test generation
        try {
            com.google.javascript.rhino.Node node77 = com.google.javascript.rhino.IR.getelem(node6, node55);
            org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException; message: second new child has existing parent");
        } catch (java.lang.IllegalArgumentException e) {
            // Expected exception.
        }
        org.junit.Assert.assertNotNull(nodeArray0);
        org.junit.Assert.assertArrayEquals(nodeArray0, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node1);
        org.junit.Assert.assertNotNull(node2);
        org.junit.Assert.assertNotNull(node3);
        org.junit.Assert.assertNotNull(node4);
        org.junit.Assert.assertNotNull(node5);
        org.junit.Assert.assertNotNull(node6);
        org.junit.Assert.assertNotNull(node7);
        org.junit.Assert.assertNotNull(node8);
        org.junit.Assert.assertNotNull(node9);
        org.junit.Assert.assertNotNull(node10);
        org.junit.Assert.assertNotNull(node12);
        org.junit.Assert.assertNotNull(nodeArray13);
        org.junit.Assert.assertArrayEquals(nodeArray13, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node14);
        org.junit.Assert.assertNotNull(node15);
        org.junit.Assert.assertNotNull(node16);
        org.junit.Assert.assertNotNull(node17);
        org.junit.Assert.assertNotNull(node18);
        org.junit.Assert.assertNotNull(node19);
        org.junit.Assert.assertNotNull(node20);
        org.junit.Assert.assertNotNull(nodeArray21);
        org.junit.Assert.assertArrayEquals(nodeArray21, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node22);
        org.junit.Assert.assertNotNull(node23);
        org.junit.Assert.assertNotNull(node24);
        org.junit.Assert.assertNotNull(node25);
        org.junit.Assert.assertNotNull(node26);
        org.junit.Assert.assertNotNull(node28);
        org.junit.Assert.assertNotNull(nodeArray29);
        org.junit.Assert.assertArrayEquals(nodeArray29, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node30);
        org.junit.Assert.assertNotNull(node31);
        org.junit.Assert.assertNotNull(node32);
        org.junit.Assert.assertNotNull(node33);
        org.junit.Assert.assertNotNull(node34);
        org.junit.Assert.assertNotNull(node35);
        org.junit.Assert.assertNotNull(node36);
        org.junit.Assert.assertNotNull(nodeArray37);
        org.junit.Assert.assertArrayEquals(nodeArray37, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node38);
        org.junit.Assert.assertNotNull(node39);
        org.junit.Assert.assertNotNull(node40);
        org.junit.Assert.assertNotNull(node41);
        org.junit.Assert.assertNotNull(node42);
        org.junit.Assert.assertNotNull(node43);
        org.junit.Assert.assertNotNull(node44);
        org.junit.Assert.assertNotNull(node45);
        org.junit.Assert.assertNotNull(nodeArray46);
        org.junit.Assert.assertArrayEquals(nodeArray46, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node47);
        org.junit.Assert.assertNotNull(node48);
        org.junit.Assert.assertNotNull(node49);
        org.junit.Assert.assertNotNull(node50);
        org.junit.Assert.assertNotNull(node51);
        org.junit.Assert.assertNotNull(node52);
        org.junit.Assert.assertNotNull(node53);
        org.junit.Assert.assertNotNull(node54);
        org.junit.Assert.assertNotNull(node55);
        org.junit.Assert.assertNotNull(nodeArray56);
        org.junit.Assert.assertArrayEquals(nodeArray56, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node57);
        org.junit.Assert.assertNotNull(node58);
        org.junit.Assert.assertNotNull(node59);
        org.junit.Assert.assertNotNull(node60);
        org.junit.Assert.assertNotNull(node61);
        org.junit.Assert.assertNotNull(node62);
        org.junit.Assert.assertNotNull(node64);
        org.junit.Assert.assertNotNull(nodeArray65);
        org.junit.Assert.assertArrayEquals(nodeArray65, new com.google.javascript.rhino.Node[] {});
        org.junit.Assert.assertNotNull(node66);
        org.junit.Assert.assertNotNull(node67);
        org.junit.Assert.assertNotNull(node68);
        org.junit.Assert.assertNotNull(node69);
        org.junit.Assert.assertNotNull(node70);
        org.junit.Assert.assertNotNull(node71);
        org.junit.Assert.assertNotNull(node72);
        org.junit.Assert.assertNotNull(node73);
        org.junit.Assert.assertNotNull(node74);
        org.junit.Assert.assertNotNull(node75);
        org.junit.Assert.assertNotNull(node76);
    }
}

