package org.jfree.chart.plot;

import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class ErrorTest1 {

    public static boolean debug = false;

    public void assertBooleanArrayEquals(boolean[] expectedArray, boolean[] actualArray) {
        if (expectedArray.length != actualArray.length) {
            throw new AssertionError("Array lengths differ: " + expectedArray.length + " != " + actualArray.length);
        }
        for (int i = 0; i < expectedArray.length; i++) {
            if (expectedArray[i] != actualArray[i]) {
                throw new AssertionError("Arrays differ at index " + i + ": " + expectedArray[i] + " != " + actualArray[i]);
            }
        }
    }

    @Test
    public void test501() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest1.test501");
        org.jfree.data.xy.XYDataset xYDataset0 = null;
        org.jfree.chart.axis.ValueAxis valueAxis1 = null;
        org.jfree.chart.axis.ValueAxis valueAxis2 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer3 = null;
        org.jfree.chart.plot.XYPlot xYPlot4 = new org.jfree.chart.plot.XYPlot(xYDataset0, valueAxis1, valueAxis2, xYItemRenderer3);
        boolean boolean5 = xYPlot4.isDomainGridlinesVisible();
        org.jfree.chart.axis.ValueAxis valueAxis6 = null;
        xYPlot4.setRangeAxis(valueAxis6);
        java.awt.Paint paint8 = xYPlot4.getDomainCrosshairPaint();
        xYPlot4.setDomainCrosshairValue((double) 10.0f, true);
        java.awt.Graphics2D graphics2D12 = null;
        java.awt.geom.Rectangle2D rectangle2D13 = null;
        java.util.List list14 = null;
        xYPlot4.drawRangeGridlines(graphics2D12, rectangle2D13, list14);
        org.jfree.data.xy.XYDataset xYDataset16 = null;
        org.jfree.chart.axis.ValueAxis valueAxis17 = null;
        org.jfree.chart.axis.ValueAxis valueAxis18 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer19 = null;
        org.jfree.chart.plot.XYPlot xYPlot20 = new org.jfree.chart.plot.XYPlot(xYDataset16, valueAxis17, valueAxis18, xYItemRenderer19);
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo22 = null;
        java.awt.geom.Point2D point2D23 = null;
        xYPlot20.zoomRangeAxes(0.0d, plotRenderingInfo22, point2D23, false);
        boolean boolean26 = xYPlot20.isDomainZoomable();
        boolean boolean27 = xYPlot20.isDomainZoomable();
        java.awt.Paint paint28 = xYPlot20.getDomainGridlinePaint();
        xYPlot4.setDomainMinorGridlinePaint(paint28);
        org.jfree.chart.LegendItemCollection legendItemCollection30 = xYPlot4.getFixedLegendItems();
        java.awt.Paint paint31 = org.jfree.chart.plot.XYPlot.DEFAULT_CROSSHAIR_PAINT;
        xYPlot4.setRangeZeroBaselinePaint(paint31);
        org.jfree.data.xy.XYDataset xYDataset33 = null;
        org.jfree.chart.axis.ValueAxis valueAxis34 = null;
        org.jfree.chart.axis.ValueAxis valueAxis35 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer36 = null;
        org.jfree.chart.plot.XYPlot xYPlot37 = new org.jfree.chart.plot.XYPlot(xYDataset33, valueAxis34, valueAxis35, xYItemRenderer36);
        org.jfree.chart.plot.Marker marker38 = null;
        boolean boolean39 = xYPlot37.removeDomainMarker(marker38);
        org.jfree.chart.axis.AxisLocation axisLocation41 = xYPlot37.getRangeAxisLocation((int) (byte) -1);
        int int42 = xYPlot37.getBackgroundImageAlignment();
        org.jfree.chart.axis.AxisLocation axisLocation44 = xYPlot37.getDomainAxisLocation(15);
        xYPlot4.setRangeAxisLocation(axisLocation44, true);
        org.junit.Assert.assertTrue("Contract failed: equals-hashcode on xYPlot20 and xYPlot37", xYPlot20.equals(xYPlot37) ? xYPlot20.hashCode() == xYPlot37.hashCode() : true);
    }

    @Test
    public void test502() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest1.test502");
        org.jfree.data.xy.XYDataset xYDataset0 = null;
        org.jfree.chart.axis.ValueAxis valueAxis1 = null;
        org.jfree.chart.axis.ValueAxis valueAxis2 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer3 = null;
        org.jfree.chart.plot.XYPlot xYPlot4 = new org.jfree.chart.plot.XYPlot(xYDataset0, valueAxis1, valueAxis2, xYItemRenderer3);
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo6 = null;
        java.awt.geom.Point2D point2D7 = null;
        xYPlot4.zoomRangeAxes(0.0d, plotRenderingInfo6, point2D7, false);
        boolean boolean10 = xYPlot4.isDomainZoomable();
        boolean boolean11 = xYPlot4.isDomainZoomable();
        java.awt.Paint paint12 = xYPlot4.getDomainGridlinePaint();
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo14 = null;
        org.jfree.data.xy.XYDataset xYDataset15 = null;
        org.jfree.chart.axis.ValueAxis valueAxis16 = null;
        org.jfree.chart.axis.ValueAxis valueAxis17 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer18 = null;
        org.jfree.chart.plot.XYPlot xYPlot19 = new org.jfree.chart.plot.XYPlot(xYDataset15, valueAxis16, valueAxis17, xYItemRenderer18);
        boolean boolean20 = xYPlot19.isDomainGridlinesVisible();
        org.jfree.chart.axis.ValueAxis valueAxis21 = null;
        int int22 = xYPlot19.getRangeAxisIndex(valueAxis21);
        xYPlot19.setDomainGridlinesVisible(false);
        boolean boolean25 = xYPlot19.isOutlineVisible();
        java.awt.Stroke stroke26 = xYPlot19.getDomainGridlineStroke();
        boolean boolean27 = xYPlot19.canSelectByPoint();
        org.jfree.chart.util.Layer layer29 = null;
        java.util.Collection collection30 = xYPlot19.getRangeMarkers((int) '4', layer29);
        org.jfree.chart.axis.ValueAxis valueAxis31 = null;
        org.jfree.data.Range range32 = xYPlot19.getDataRange(valueAxis31);
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo34 = null;
        org.jfree.data.xy.XYDataset xYDataset35 = null;
        org.jfree.chart.axis.ValueAxis valueAxis36 = null;
        org.jfree.chart.axis.ValueAxis valueAxis37 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer38 = null;
        org.jfree.chart.plot.XYPlot xYPlot39 = new org.jfree.chart.plot.XYPlot(xYDataset35, valueAxis36, valueAxis37, xYItemRenderer38);
        java.awt.geom.Point2D point2D40 = xYPlot39.getQuadrantOrigin();
        java.awt.geom.GeneralPath generalPath41 = null;
        java.awt.geom.Rectangle2D rectangle2D42 = null;
        org.jfree.chart.RenderingSource renderingSource43 = null;
        xYPlot39.select(generalPath41, rectangle2D42, renderingSource43);
        org.jfree.data.xy.XYDataset xYDataset45 = null;
        org.jfree.chart.axis.ValueAxis valueAxis46 = null;
        org.jfree.chart.axis.ValueAxis valueAxis47 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer48 = null;
        org.jfree.chart.plot.XYPlot xYPlot49 = new org.jfree.chart.plot.XYPlot(xYDataset45, valueAxis46, valueAxis47, xYItemRenderer48);
        boolean boolean50 = xYPlot49.isDomainGridlinesVisible();
        org.jfree.chart.axis.ValueAxis valueAxis51 = null;
        xYPlot49.setRangeAxis(valueAxis51);
        org.jfree.chart.event.PlotChangeListener plotChangeListener53 = null;
        xYPlot49.addChangeListener(plotChangeListener53);
        org.jfree.chart.event.AxisChangeEvent axisChangeEvent55 = null;
        xYPlot49.axisChanged(axisChangeEvent55);
        org.jfree.chart.LegendItemCollection legendItemCollection57 = xYPlot49.getLegendItems();
        xYPlot39.setFixedLegendItems(legendItemCollection57);
        xYPlot39.setBackgroundImageAlignment(15);
        java.awt.Paint paint61 = xYPlot39.getRangeGridlinePaint();
        boolean boolean62 = xYPlot39.isDomainPannable();
        boolean boolean63 = xYPlot39.isRangeCrosshairVisible();
        java.awt.geom.Point2D point2D64 = xYPlot39.getQuadrantOrigin();
        xYPlot19.panDomainAxes((double) 0.0f, plotRenderingInfo34, point2D64);
        xYPlot4.panRangeAxes((double) (short) 0, plotRenderingInfo14, point2D64);
        org.junit.Assert.assertTrue("Contract failed: equals-hashcode on xYPlot4 and xYPlot49", xYPlot4.equals(xYPlot49) ? xYPlot4.hashCode() == xYPlot49.hashCode() : true);
    }

    @Test
    public void test503() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest1.test503");
        org.jfree.data.xy.XYDataset xYDataset0 = null;
        org.jfree.chart.axis.ValueAxis valueAxis1 = null;
        org.jfree.chart.axis.ValueAxis valueAxis2 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer3 = null;
        org.jfree.chart.plot.XYPlot xYPlot4 = new org.jfree.chart.plot.XYPlot(xYDataset0, valueAxis1, valueAxis2, xYItemRenderer3);
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo6 = null;
        java.awt.geom.Point2D point2D7 = null;
        xYPlot4.zoomRangeAxes(0.0d, plotRenderingInfo6, point2D7, false);
        org.jfree.data.xy.XYDataset xYDataset10 = null;
        org.jfree.chart.axis.ValueAxis valueAxis11 = null;
        org.jfree.chart.axis.ValueAxis valueAxis12 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer13 = null;
        org.jfree.chart.plot.XYPlot xYPlot14 = new org.jfree.chart.plot.XYPlot(xYDataset10, valueAxis11, valueAxis12, xYItemRenderer13);
        java.awt.Paint paint15 = xYPlot14.getRangeMinorGridlinePaint();
        xYPlot4.setRangeZeroBaselinePaint(paint15);
        xYPlot4.setDomainCrosshairVisible(true);
        xYPlot4.clearRangeMarkers();
        java.awt.Stroke stroke20 = org.jfree.chart.plot.Plot.DEFAULT_OUTLINE_STROKE;
        xYPlot4.setDomainGridlineStroke(stroke20);
        boolean boolean22 = xYPlot4.isDomainMinorGridlinesVisible();
        boolean boolean23 = xYPlot4.isDomainZoomable();
        boolean boolean24 = xYPlot4.isRangeZoomable();
        java.awt.Paint paint25 = xYPlot4.getNoDataMessagePaint();
        java.awt.Font font26 = xYPlot4.getNoDataMessageFont();
        xYPlot4.setOutlineVisible(true);
        org.jfree.chart.axis.ValueAxis valueAxis30 = null;
        xYPlot4.setDomainAxis((int) (short) 10, valueAxis30, true);
        org.jfree.data.xy.XYDataset xYDataset33 = null;
        org.jfree.chart.axis.ValueAxis valueAxis34 = null;
        org.jfree.chart.axis.ValueAxis valueAxis35 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer36 = null;
        org.jfree.chart.plot.XYPlot xYPlot37 = new org.jfree.chart.plot.XYPlot(xYDataset33, valueAxis34, valueAxis35, xYItemRenderer36);
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo39 = null;
        java.awt.geom.Point2D point2D40 = null;
        xYPlot37.zoomRangeAxes(0.0d, plotRenderingInfo39, point2D40, false);
        org.jfree.chart.util.Layer layer43 = null;
        java.util.Collection collection44 = xYPlot37.getDomainMarkers(layer43);
        org.jfree.chart.plot.DrawingSupplier drawingSupplier45 = null;
        xYPlot37.setDrawingSupplier(drawingSupplier45);
        org.jfree.chart.axis.AxisLocation axisLocation48 = xYPlot37.getDomainAxisLocation((int) ' ');
        org.jfree.chart.util.RectangleInsets rectangleInsets49 = xYPlot37.getInsets();
        org.jfree.data.xy.XYDataset xYDataset50 = null;
        org.jfree.chart.axis.ValueAxis valueAxis51 = null;
        org.jfree.chart.axis.ValueAxis valueAxis52 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer53 = null;
        org.jfree.chart.plot.XYPlot xYPlot54 = new org.jfree.chart.plot.XYPlot(xYDataset50, valueAxis51, valueAxis52, xYItemRenderer53);
        java.awt.geom.Point2D point2D55 = xYPlot54.getQuadrantOrigin();
        java.awt.geom.GeneralPath generalPath56 = null;
        java.awt.geom.Rectangle2D rectangle2D57 = null;
        org.jfree.chart.RenderingSource renderingSource58 = null;
        xYPlot54.select(generalPath56, rectangle2D57, renderingSource58);
        org.jfree.data.xy.XYDataset xYDataset60 = null;
        org.jfree.chart.axis.ValueAxis valueAxis61 = null;
        org.jfree.chart.axis.ValueAxis valueAxis62 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer63 = null;
        org.jfree.chart.plot.XYPlot xYPlot64 = new org.jfree.chart.plot.XYPlot(xYDataset60, valueAxis61, valueAxis62, xYItemRenderer63);
        org.jfree.chart.axis.AxisLocation axisLocation65 = xYPlot64.getRangeAxisLocation();
        xYPlot64.setForegroundAlpha((-1.0f));
        org.jfree.chart.plot.Plot plot68 = xYPlot64.getParent();
        org.jfree.chart.axis.ValueAxis valueAxis69 = xYPlot64.getRangeAxis();
        org.jfree.chart.axis.AxisLocation axisLocation71 = xYPlot64.getDomainAxisLocation(15);
        xYPlot54.setDomainAxisLocation(axisLocation71, true);
        double double74 = xYPlot54.getDomainCrosshairValue();
        org.jfree.data.xy.XYDataset xYDataset75 = null;
        org.jfree.chart.axis.ValueAxis valueAxis76 = null;
        org.jfree.chart.axis.ValueAxis valueAxis77 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer78 = null;
        org.jfree.chart.plot.XYPlot xYPlot79 = new org.jfree.chart.plot.XYPlot(xYDataset75, valueAxis76, valueAxis77, xYItemRenderer78);
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo81 = null;
        java.awt.geom.Point2D point2D82 = null;
        xYPlot79.zoomRangeAxes(0.0d, plotRenderingInfo81, point2D82, false);
        org.jfree.data.xy.XYDataset xYDataset85 = null;
        org.jfree.chart.axis.ValueAxis valueAxis86 = null;
        org.jfree.chart.axis.ValueAxis valueAxis87 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer88 = null;
        org.jfree.chart.plot.XYPlot xYPlot89 = new org.jfree.chart.plot.XYPlot(xYDataset85, valueAxis86, valueAxis87, xYItemRenderer88);
        java.awt.Paint paint90 = xYPlot89.getRangeMinorGridlinePaint();
        xYPlot79.setRangeZeroBaselinePaint(paint90);
        org.jfree.chart.axis.ValueAxis valueAxis93 = xYPlot79.getDomainAxisForDataset((int) (short) 0);
        org.jfree.chart.util.RectangleInsets rectangleInsets94 = xYPlot79.getAxisOffset();
        xYPlot54.setAxisOffset(rectangleInsets94);
        xYPlot37.setInsets(rectangleInsets94);
        java.awt.Paint paint97 = xYPlot37.getRangeZeroBaselinePaint();
        xYPlot4.setDomainCrosshairPaint(paint97);
        org.junit.Assert.assertTrue("Contract failed: equals-hashcode on xYPlot14 and xYPlot89", xYPlot14.equals(xYPlot89) ? xYPlot14.hashCode() == xYPlot89.hashCode() : true);
    }

    @Test
    public void test504() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest1.test504");
        org.jfree.data.xy.XYDataset xYDataset0 = null;
        org.jfree.chart.axis.ValueAxis valueAxis1 = null;
        org.jfree.chart.axis.ValueAxis valueAxis2 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer3 = null;
        org.jfree.chart.plot.XYPlot xYPlot4 = new org.jfree.chart.plot.XYPlot(xYDataset0, valueAxis1, valueAxis2, xYItemRenderer3);
        org.jfree.chart.plot.Marker marker5 = null;
        boolean boolean6 = xYPlot4.removeDomainMarker(marker5);
        org.jfree.chart.axis.AxisLocation axisLocation8 = xYPlot4.getRangeAxisLocation((int) (byte) -1);
        int int9 = xYPlot4.getBackgroundImageAlignment();
        java.awt.Graphics2D graphics2D10 = null;
        java.awt.geom.Rectangle2D rectangle2D11 = null;
        org.jfree.chart.util.Layer layer13 = null;
        xYPlot4.drawRangeMarkers(graphics2D10, rectangle2D11, 15, layer13);
        org.jfree.chart.axis.ValueAxis valueAxis15 = null;
        org.jfree.data.Range range16 = xYPlot4.getDataRange(valueAxis15);
        org.jfree.chart.util.RectangleEdge rectangleEdge18 = xYPlot4.getRangeAxisEdge((int) (short) 10);
        java.lang.String str19 = xYPlot4.getNoDataMessage();
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo21 = null;
        org.jfree.data.xy.XYDataset xYDataset22 = null;
        org.jfree.chart.axis.ValueAxis valueAxis23 = null;
        org.jfree.chart.axis.ValueAxis valueAxis24 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer25 = null;
        org.jfree.chart.plot.XYPlot xYPlot26 = new org.jfree.chart.plot.XYPlot(xYDataset22, valueAxis23, valueAxis24, xYItemRenderer25);
        org.jfree.chart.plot.Marker marker27 = null;
        boolean boolean28 = xYPlot26.removeDomainMarker(marker27);
        org.jfree.chart.axis.AxisLocation axisLocation30 = xYPlot26.getRangeAxisLocation((int) (byte) -1);
        int int31 = xYPlot26.getBackgroundImageAlignment();
        xYPlot26.setRangeMinorGridlinesVisible(true);
        double double34 = xYPlot26.getRangeCrosshairValue();
        org.jfree.data.xy.XYDataset xYDataset35 = null;
        org.jfree.chart.axis.ValueAxis valueAxis36 = null;
        org.jfree.chart.axis.ValueAxis valueAxis37 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer38 = null;
        org.jfree.chart.plot.XYPlot xYPlot39 = new org.jfree.chart.plot.XYPlot(xYDataset35, valueAxis36, valueAxis37, xYItemRenderer38);
        org.jfree.chart.plot.Marker marker40 = null;
        boolean boolean41 = xYPlot39.removeDomainMarker(marker40);
        org.jfree.chart.axis.AxisLocation axisLocation43 = xYPlot39.getRangeAxisLocation((int) (byte) -1);
        int int44 = xYPlot39.getBackgroundImageAlignment();
        xYPlot39.setRangeMinorGridlinesVisible(true);
        org.jfree.chart.renderer.xy.XYItemRenderer[] xYItemRendererArray47 = new org.jfree.chart.renderer.xy.XYItemRenderer[] {};
        xYPlot39.setRenderers(xYItemRendererArray47);
        org.jfree.chart.util.RectangleEdge rectangleEdge50 = xYPlot39.getDomainAxisEdge((int) (byte) 0);
        java.awt.Paint paint51 = xYPlot39.getRangeGridlinePaint();
        xYPlot26.setDomainZeroBaselinePaint(paint51);
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo55 = null;
        org.jfree.data.xy.XYDataset xYDataset56 = null;
        org.jfree.chart.axis.ValueAxis valueAxis57 = null;
        org.jfree.chart.axis.ValueAxis valueAxis58 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer59 = null;
        org.jfree.chart.plot.XYPlot xYPlot60 = new org.jfree.chart.plot.XYPlot(xYDataset56, valueAxis57, valueAxis58, xYItemRenderer59);
        org.jfree.chart.plot.Marker marker61 = null;
        boolean boolean62 = xYPlot60.removeDomainMarker(marker61);
        xYPlot60.setBackgroundImageAlignment((int) (short) 0);
        xYPlot60.setBackgroundAlpha((float) '4');
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo68 = null;
        org.jfree.data.xy.XYDataset xYDataset69 = null;
        org.jfree.chart.axis.ValueAxis valueAxis70 = null;
        org.jfree.chart.axis.ValueAxis valueAxis71 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer72 = null;
        org.jfree.chart.plot.XYPlot xYPlot73 = new org.jfree.chart.plot.XYPlot(xYDataset69, valueAxis70, valueAxis71, xYItemRenderer72);
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo75 = null;
        java.awt.geom.Point2D point2D76 = null;
        xYPlot73.zoomRangeAxes(0.0d, plotRenderingInfo75, point2D76, false);
        boolean boolean79 = xYPlot73.isDomainZoomable();
        boolean boolean80 = xYPlot73.canSelectByPoint();
        java.awt.Graphics2D graphics2D81 = null;
        java.awt.geom.Rectangle2D rectangle2D82 = null;
        xYPlot73.drawQuadrants(graphics2D81, rectangle2D82);
        java.awt.geom.Point2D point2D84 = xYPlot73.getQuadrantOrigin();
        xYPlot60.zoomDomainAxes((double) 'a', plotRenderingInfo68, point2D84, true);
        xYPlot26.zoomRangeAxes((double) '#', (double) 100, plotRenderingInfo55, point2D84);
        xYPlot4.panDomainAxes((double) 'a', plotRenderingInfo21, point2D84);
        org.junit.Assert.assertTrue("Contract failed: equals-hashcode on xYPlot4 and xYPlot73", xYPlot4.equals(xYPlot73) ? xYPlot4.hashCode() == xYPlot73.hashCode() : true);
    }

    @Test
    public void test505() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest1.test505");
        org.jfree.data.xy.XYDataset xYDataset0 = null;
        org.jfree.chart.axis.ValueAxis valueAxis1 = null;
        org.jfree.chart.axis.ValueAxis valueAxis2 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer3 = null;
        org.jfree.chart.plot.XYPlot xYPlot4 = new org.jfree.chart.plot.XYPlot(xYDataset0, valueAxis1, valueAxis2, xYItemRenderer3);
        boolean boolean5 = xYPlot4.isDomainGridlinesVisible();
        org.jfree.chart.axis.ValueAxis valueAxis6 = null;
        int int7 = xYPlot4.getRangeAxisIndex(valueAxis6);
        boolean boolean8 = xYPlot4.isOutlineVisible();
        org.jfree.chart.LegendItemCollection legendItemCollection9 = xYPlot4.getLegendItems();
        org.jfree.data.xy.XYDataset xYDataset11 = null;
        xYPlot4.setDataset((int) 'a', xYDataset11);
        org.jfree.chart.plot.DrawingSupplier drawingSupplier13 = xYPlot4.getDrawingSupplier();
        org.jfree.data.xy.XYDataset xYDataset15 = null;
        org.jfree.chart.axis.ValueAxis valueAxis16 = null;
        org.jfree.chart.axis.ValueAxis valueAxis17 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer18 = null;
        org.jfree.chart.plot.XYPlot xYPlot19 = new org.jfree.chart.plot.XYPlot(xYDataset15, valueAxis16, valueAxis17, xYItemRenderer18);
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo21 = null;
        java.awt.geom.Point2D point2D22 = null;
        xYPlot19.zoomRangeAxes(0.0d, plotRenderingInfo21, point2D22, false);
        boolean boolean25 = xYPlot19.isDomainZoomable();
        boolean boolean26 = xYPlot19.canSelectByPoint();
        java.awt.Graphics2D graphics2D27 = null;
        java.awt.geom.Rectangle2D rectangle2D28 = null;
        xYPlot19.drawQuadrants(graphics2D27, rectangle2D28);
        java.awt.geom.Point2D point2D30 = xYPlot19.getQuadrantOrigin();
        java.awt.Image image31 = xYPlot19.getBackgroundImage();
        boolean boolean32 = xYPlot19.isDomainCrosshairLockedOnData();
        xYPlot19.setRangeCrosshairValue(1.0d, false);
        java.awt.Stroke stroke36 = org.jfree.chart.plot.XYPlot.DEFAULT_GRIDLINE_STROKE;
        xYPlot19.setRangeMinorGridlineStroke(stroke36);
        org.jfree.data.xy.XYDataset xYDataset38 = null;
        org.jfree.chart.axis.ValueAxis valueAxis39 = null;
        org.jfree.chart.axis.ValueAxis valueAxis40 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer41 = null;
        org.jfree.chart.plot.XYPlot xYPlot42 = new org.jfree.chart.plot.XYPlot(xYDataset38, valueAxis39, valueAxis40, xYItemRenderer41);
        org.jfree.chart.plot.Marker marker43 = null;
        boolean boolean44 = xYPlot42.removeDomainMarker(marker43);
        org.jfree.chart.axis.AxisLocation axisLocation46 = xYPlot42.getRangeAxisLocation((int) (byte) -1);
        org.jfree.data.xy.XYDataset xYDataset47 = xYPlot42.getDataset();
        boolean boolean48 = xYPlot42.isRangeZoomable();
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer49 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer[] xYItemRendererArray50 = new org.jfree.chart.renderer.xy.XYItemRenderer[] { xYItemRenderer49 };
        xYPlot42.setRenderers(xYItemRendererArray50);
        org.jfree.chart.axis.AxisLocation axisLocation53 = xYPlot42.getDomainAxisLocation((int) (short) 0);
        xYPlot19.setRangeAxisLocation(axisLocation53);
        xYPlot4.setDomainAxisLocation(10, axisLocation53, false);
        // This assertion (symmetry of equals) fails
        org.junit.Assert.assertTrue("Contract failed: equals-symmetric on xYPlot4 and xYPlot42.", xYPlot4.equals(xYPlot42) == xYPlot42.equals(xYPlot4));
    }

    @Test
    public void test506() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest1.test506");
        org.jfree.data.xy.XYDataset xYDataset0 = null;
        org.jfree.chart.axis.ValueAxis valueAxis1 = null;
        org.jfree.chart.axis.ValueAxis valueAxis2 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer3 = null;
        org.jfree.chart.plot.XYPlot xYPlot4 = new org.jfree.chart.plot.XYPlot(xYDataset0, valueAxis1, valueAxis2, xYItemRenderer3);
        boolean boolean5 = xYPlot4.isDomainGridlinesVisible();
        org.jfree.chart.axis.ValueAxis valueAxis6 = null;
        int int7 = xYPlot4.getRangeAxisIndex(valueAxis6);
        java.awt.Stroke stroke8 = xYPlot4.getDomainGridlineStroke();
        org.jfree.chart.axis.ValueAxis valueAxis9 = xYPlot4.getDomainAxis();
        org.jfree.chart.util.Layer layer11 = null;
        java.util.Collection collection12 = xYPlot4.getDomainMarkers((int) (byte) 10, layer11);
        xYPlot4.setWeight((int) (byte) 10);
        java.awt.Graphics2D graphics2D15 = null;
        java.awt.geom.Rectangle2D rectangle2D16 = null;
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo18 = null;
        org.jfree.chart.plot.CrosshairState crosshairState19 = null;
        boolean boolean20 = xYPlot4.render(graphics2D15, rectangle2D16, (int) (short) -1, plotRenderingInfo18, crosshairState19);
        java.awt.Graphics2D graphics2D21 = null;
        java.awt.geom.Rectangle2D rectangle2D22 = null;
        xYPlot4.drawBackgroundImage(graphics2D21, rectangle2D22);
        java.awt.Font font24 = xYPlot4.getNoDataMessageFont();
        org.jfree.data.xy.XYDataset xYDataset25 = null;
        org.jfree.chart.axis.ValueAxis valueAxis26 = null;
        org.jfree.chart.axis.ValueAxis valueAxis27 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer28 = null;
        org.jfree.chart.plot.XYPlot xYPlot29 = new org.jfree.chart.plot.XYPlot(xYDataset25, valueAxis26, valueAxis27, xYItemRenderer28);
        boolean boolean30 = xYPlot29.isDomainGridlinesVisible();
        org.jfree.chart.axis.ValueAxis valueAxis31 = null;
        int int32 = xYPlot29.getRangeAxisIndex(valueAxis31);
        xYPlot29.setDomainGridlinesVisible(false);
        org.jfree.chart.plot.Marker marker36 = null;
        org.jfree.chart.util.Layer layer37 = null;
        boolean boolean38 = xYPlot29.removeDomainMarker((int) (short) -1, marker36, layer37);
        org.jfree.data.xy.XYDataset xYDataset39 = null;
        org.jfree.chart.axis.ValueAxis valueAxis40 = null;
        org.jfree.chart.axis.ValueAxis valueAxis41 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer42 = null;
        org.jfree.chart.plot.XYPlot xYPlot43 = new org.jfree.chart.plot.XYPlot(xYDataset39, valueAxis40, valueAxis41, xYItemRenderer42);
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo45 = null;
        java.awt.geom.Point2D point2D46 = null;
        xYPlot43.zoomRangeAxes(0.0d, plotRenderingInfo45, point2D46, false);
        xYPlot43.setDomainCrosshairValue((double) 10L);
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer51 = null;
        xYPlot43.setRenderer(xYItemRenderer51);
        org.jfree.chart.util.RectangleEdge rectangleEdge54 = xYPlot43.getDomainAxisEdge((int) (byte) 100);
        org.jfree.data.xy.XYDataset xYDataset55 = null;
        org.jfree.chart.axis.ValueAxis valueAxis56 = null;
        org.jfree.chart.axis.ValueAxis valueAxis57 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer58 = null;
        org.jfree.chart.plot.XYPlot xYPlot59 = new org.jfree.chart.plot.XYPlot(xYDataset55, valueAxis56, valueAxis57, xYItemRenderer58);
        boolean boolean60 = xYPlot59.isDomainGridlinesVisible();
        org.jfree.chart.axis.ValueAxis valueAxis61 = null;
        xYPlot59.setRangeAxis(valueAxis61);
        org.jfree.data.general.DatasetGroup datasetGroup63 = xYPlot59.getDatasetGroup();
        org.jfree.chart.axis.AxisSpace axisSpace64 = null;
        xYPlot59.setFixedDomainAxisSpace(axisSpace64);
        org.jfree.chart.plot.DrawingSupplier drawingSupplier66 = xYPlot59.getDrawingSupplier();
        xYPlot43.setDrawingSupplier(drawingSupplier66);
        xYPlot29.setDrawingSupplier(drawingSupplier66, true);
        xYPlot4.setDrawingSupplier(drawingSupplier66);
        boolean boolean71 = xYPlot4.canSelectByPoint();
        boolean boolean72 = xYPlot4.isNotify();
        org.jfree.data.xy.XYDataset xYDataset74 = null;
        org.jfree.chart.axis.ValueAxis valueAxis75 = null;
        org.jfree.chart.axis.ValueAxis valueAxis76 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer77 = null;
        org.jfree.chart.plot.XYPlot xYPlot78 = new org.jfree.chart.plot.XYPlot(xYDataset74, valueAxis75, valueAxis76, xYItemRenderer77);
        org.jfree.chart.plot.Marker marker79 = null;
        boolean boolean80 = xYPlot78.removeDomainMarker(marker79);
        org.jfree.chart.axis.AxisLocation axisLocation82 = xYPlot78.getRangeAxisLocation((int) (byte) -1);
        java.awt.Stroke stroke83 = xYPlot78.getDomainCrosshairStroke();
        org.jfree.chart.axis.AxisLocation axisLocation84 = xYPlot78.getDomainAxisLocation();
        xYPlot4.setRangeAxisLocation((int) '#', axisLocation84, true);
        org.junit.Assert.assertTrue("Contract failed: equals-hashcode on xYPlot59 and xYPlot78", xYPlot59.equals(xYPlot78) ? xYPlot59.hashCode() == xYPlot78.hashCode() : true);
    }

    @Test
    public void test507() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest1.test507");
        org.jfree.data.xy.XYDataset xYDataset0 = null;
        org.jfree.chart.axis.ValueAxis valueAxis1 = null;
        org.jfree.chart.axis.ValueAxis valueAxis2 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer3 = null;
        org.jfree.chart.plot.XYPlot xYPlot4 = new org.jfree.chart.plot.XYPlot(xYDataset0, valueAxis1, valueAxis2, xYItemRenderer3);
        boolean boolean5 = xYPlot4.isDomainGridlinesVisible();
        org.jfree.chart.axis.ValueAxis valueAxis6 = null;
        xYPlot4.setRangeAxis(valueAxis6);
        org.jfree.chart.event.PlotChangeListener plotChangeListener8 = null;
        xYPlot4.addChangeListener(plotChangeListener8);
        org.jfree.data.xy.XYDataset xYDataset10 = null;
        org.jfree.chart.axis.ValueAxis valueAxis11 = null;
        org.jfree.chart.axis.ValueAxis valueAxis12 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer13 = null;
        org.jfree.chart.plot.XYPlot xYPlot14 = new org.jfree.chart.plot.XYPlot(xYDataset10, valueAxis11, valueAxis12, xYItemRenderer13);
        java.awt.Paint paint15 = xYPlot14.getRangeMinorGridlinePaint();
        org.jfree.chart.axis.ValueAxis valueAxis17 = null;
        xYPlot14.setRangeAxis((int) ' ', valueAxis17, false);
        org.jfree.chart.axis.ValueAxis valueAxis20 = null;
        org.jfree.data.Range range21 = xYPlot14.getDataRange(valueAxis20);
        java.awt.Stroke stroke22 = xYPlot14.getRangeMinorGridlineStroke();
        java.awt.Stroke stroke23 = xYPlot14.getDomainCrosshairStroke();
        xYPlot4.setDomainMinorGridlineStroke(stroke23);
        org.junit.Assert.assertTrue("Contract failed: equals-hashcode on xYPlot4 and xYPlot14", xYPlot4.equals(xYPlot14) ? xYPlot4.hashCode() == xYPlot14.hashCode() : true);
    }

    @Test
    public void test508() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest1.test508");
        org.jfree.data.xy.XYDataset xYDataset0 = null;
        org.jfree.chart.axis.ValueAxis valueAxis1 = null;
        org.jfree.chart.axis.ValueAxis valueAxis2 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer3 = null;
        org.jfree.chart.plot.XYPlot xYPlot4 = new org.jfree.chart.plot.XYPlot(xYDataset0, valueAxis1, valueAxis2, xYItemRenderer3);
        java.awt.geom.Point2D point2D5 = xYPlot4.getQuadrantOrigin();
        java.awt.geom.GeneralPath generalPath6 = null;
        java.awt.geom.Rectangle2D rectangle2D7 = null;
        org.jfree.chart.RenderingSource renderingSource8 = null;
        xYPlot4.select(generalPath6, rectangle2D7, renderingSource8);
        org.jfree.data.xy.XYDataset xYDataset10 = null;
        org.jfree.chart.axis.ValueAxis valueAxis11 = null;
        org.jfree.chart.axis.ValueAxis valueAxis12 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer13 = null;
        org.jfree.chart.plot.XYPlot xYPlot14 = new org.jfree.chart.plot.XYPlot(xYDataset10, valueAxis11, valueAxis12, xYItemRenderer13);
        boolean boolean15 = xYPlot14.isDomainGridlinesVisible();
        org.jfree.chart.axis.ValueAxis valueAxis16 = null;
        xYPlot14.setRangeAxis(valueAxis16);
        org.jfree.chart.event.PlotChangeListener plotChangeListener18 = null;
        xYPlot14.addChangeListener(plotChangeListener18);
        org.jfree.chart.event.AxisChangeEvent axisChangeEvent20 = null;
        xYPlot14.axisChanged(axisChangeEvent20);
        org.jfree.chart.LegendItemCollection legendItemCollection22 = xYPlot14.getLegendItems();
        xYPlot4.setFixedLegendItems(legendItemCollection22);
        org.jfree.chart.plot.Plot plot24 = xYPlot4.getParent();
        org.jfree.chart.axis.ValueAxis valueAxis25 = null;
        int int26 = xYPlot4.getRangeAxisIndex(valueAxis25);
        org.jfree.data.xy.XYDataset xYDataset27 = null;
        org.jfree.chart.axis.ValueAxis valueAxis28 = null;
        org.jfree.chart.axis.ValueAxis valueAxis29 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer30 = null;
        org.jfree.chart.plot.XYPlot xYPlot31 = new org.jfree.chart.plot.XYPlot(xYDataset27, valueAxis28, valueAxis29, xYItemRenderer30);
        boolean boolean32 = xYPlot31.isRangeCrosshairLockedOnData();
        java.awt.Stroke stroke33 = org.jfree.chart.plot.XYPlot.DEFAULT_CROSSHAIR_STROKE;
        xYPlot31.setOutlineStroke(stroke33);
        org.jfree.chart.axis.AxisLocation axisLocation36 = xYPlot31.getDomainAxisLocation(10);
        java.awt.Font font37 = xYPlot31.getNoDataMessageFont();
        java.awt.Graphics2D graphics2D38 = null;
        java.awt.geom.Rectangle2D rectangle2D39 = null;
        org.jfree.data.xy.XYDataset xYDataset40 = null;
        org.jfree.chart.axis.ValueAxis valueAxis41 = null;
        org.jfree.chart.axis.ValueAxis valueAxis42 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer43 = null;
        org.jfree.chart.plot.XYPlot xYPlot44 = new org.jfree.chart.plot.XYPlot(xYDataset40, valueAxis41, valueAxis42, xYItemRenderer43);
        org.jfree.chart.plot.Marker marker45 = null;
        boolean boolean46 = xYPlot44.removeDomainMarker(marker45);
        org.jfree.chart.axis.AxisLocation axisLocation48 = xYPlot44.getRangeAxisLocation((int) (byte) -1);
        int int49 = xYPlot44.getBackgroundImageAlignment();
        xYPlot44.setRangeMinorGridlinesVisible(true);
        double double52 = xYPlot44.getRangeCrosshairValue();
        xYPlot44.setRangeGridlinesVisible(true);
        xYPlot44.clearDomainMarkers();
        java.awt.Graphics2D graphics2D56 = null;
        java.awt.geom.Rectangle2D rectangle2D57 = null;
        org.jfree.data.xy.XYDataset xYDataset58 = null;
        org.jfree.chart.axis.ValueAxis valueAxis59 = null;
        org.jfree.chart.axis.ValueAxis valueAxis60 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer61 = null;
        org.jfree.chart.plot.XYPlot xYPlot62 = new org.jfree.chart.plot.XYPlot(xYDataset58, valueAxis59, valueAxis60, xYItemRenderer61);
        boolean boolean63 = xYPlot62.isDomainGridlinesVisible();
        org.jfree.chart.axis.ValueAxis valueAxis64 = null;
        int int65 = xYPlot62.getRangeAxisIndex(valueAxis64);
        xYPlot62.setDomainGridlinesVisible(false);
        org.jfree.chart.plot.Marker marker69 = null;
        org.jfree.chart.util.Layer layer70 = null;
        boolean boolean71 = xYPlot62.removeDomainMarker((int) (short) -1, marker69, layer70);
        org.jfree.data.xy.XYDataset xYDataset72 = null;
        org.jfree.chart.axis.ValueAxis valueAxis73 = null;
        org.jfree.chart.axis.ValueAxis valueAxis74 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer75 = null;
        org.jfree.chart.plot.XYPlot xYPlot76 = new org.jfree.chart.plot.XYPlot(xYDataset72, valueAxis73, valueAxis74, xYItemRenderer75);
        boolean boolean77 = xYPlot76.isDomainGridlinesVisible();
        java.awt.Stroke stroke78 = xYPlot76.getRangeMinorGridlineStroke();
        java.awt.Stroke stroke79 = xYPlot76.getDomainMinorGridlineStroke();
        java.awt.Graphics2D graphics2D80 = null;
        java.awt.geom.Rectangle2D rectangle2D81 = null;
        org.jfree.chart.axis.AxisSpace axisSpace82 = null;
        org.jfree.chart.axis.AxisSpace axisSpace83 = xYPlot76.calculateRangeAxisSpace(graphics2D80, rectangle2D81, axisSpace82);
        xYPlot62.setFixedRangeAxisSpace(axisSpace83);
        org.jfree.chart.axis.AxisSpace axisSpace85 = xYPlot44.calculateDomainAxisSpace(graphics2D56, rectangle2D57, axisSpace83);
        org.jfree.chart.axis.AxisSpace axisSpace86 = xYPlot31.calculateDomainAxisSpace(graphics2D38, rectangle2D39, axisSpace83);
        xYPlot4.setFixedRangeAxisSpace(axisSpace83);
        org.junit.Assert.assertTrue("Contract failed: equals-hashcode on xYPlot14 and xYPlot76", xYPlot14.equals(xYPlot76) ? xYPlot14.hashCode() == xYPlot76.hashCode() : true);
    }

    @Test
    public void test509() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest1.test509");
        org.jfree.data.xy.XYDataset xYDataset0 = null;
        org.jfree.chart.axis.ValueAxis valueAxis1 = null;
        org.jfree.chart.axis.ValueAxis valueAxis2 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer3 = null;
        org.jfree.chart.plot.XYPlot xYPlot4 = new org.jfree.chart.plot.XYPlot(xYDataset0, valueAxis1, valueAxis2, xYItemRenderer3);
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo6 = null;
        java.awt.geom.Point2D point2D7 = null;
        xYPlot4.zoomRangeAxes(0.0d, plotRenderingInfo6, point2D7, false);
        boolean boolean10 = xYPlot4.isDomainZoomable();
        boolean boolean11 = xYPlot4.canSelectByPoint();
        java.awt.Graphics2D graphics2D12 = null;
        java.awt.geom.Rectangle2D rectangle2D13 = null;
        xYPlot4.drawQuadrants(graphics2D12, rectangle2D13);
        java.awt.geom.Point2D point2D15 = xYPlot4.getQuadrantOrigin();
        java.awt.Image image16 = xYPlot4.getBackgroundImage();
        boolean boolean17 = xYPlot4.isDomainCrosshairLockedOnData();
        xYPlot4.setRangeCrosshairValue(1.0d, false);
        java.awt.Stroke stroke21 = org.jfree.chart.plot.XYPlot.DEFAULT_GRIDLINE_STROKE;
        xYPlot4.setRangeMinorGridlineStroke(stroke21);
        org.jfree.data.xy.XYDataset xYDataset23 = null;
        org.jfree.chart.axis.ValueAxis valueAxis24 = null;
        org.jfree.chart.axis.ValueAxis valueAxis25 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer26 = null;
        org.jfree.chart.plot.XYPlot xYPlot27 = new org.jfree.chart.plot.XYPlot(xYDataset23, valueAxis24, valueAxis25, xYItemRenderer26);
        org.jfree.chart.plot.Marker marker28 = null;
        boolean boolean29 = xYPlot27.removeDomainMarker(marker28);
        org.jfree.chart.axis.AxisLocation axisLocation31 = xYPlot27.getRangeAxisLocation((int) (byte) -1);
        org.jfree.data.xy.XYDataset xYDataset32 = xYPlot27.getDataset();
        boolean boolean33 = xYPlot27.isRangeZoomable();
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer34 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer[] xYItemRendererArray35 = new org.jfree.chart.renderer.xy.XYItemRenderer[] { xYItemRenderer34 };
        xYPlot27.setRenderers(xYItemRendererArray35);
        org.jfree.chart.axis.AxisLocation axisLocation38 = xYPlot27.getDomainAxisLocation((int) (short) 0);
        xYPlot4.setRangeAxisLocation(axisLocation38);
        org.jfree.data.xy.XYDataset xYDataset40 = null;
        org.jfree.chart.axis.ValueAxis valueAxis41 = null;
        org.jfree.chart.axis.ValueAxis valueAxis42 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer43 = null;
        org.jfree.chart.plot.XYPlot xYPlot44 = new org.jfree.chart.plot.XYPlot(xYDataset40, valueAxis41, valueAxis42, xYItemRenderer43);
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo46 = null;
        java.awt.geom.Point2D point2D47 = null;
        xYPlot44.zoomRangeAxes(0.0d, plotRenderingInfo46, point2D47, false);
        org.jfree.chart.util.Layer layer50 = null;
        java.util.Collection collection51 = xYPlot44.getDomainMarkers(layer50);
        xYPlot44.clearRangeMarkers();
        java.awt.geom.GeneralPath generalPath53 = null;
        java.awt.geom.Rectangle2D rectangle2D54 = null;
        org.jfree.chart.RenderingSource renderingSource55 = null;
        xYPlot44.select(generalPath53, rectangle2D54, renderingSource55);
        org.jfree.data.xy.XYDataset xYDataset57 = null;
        org.jfree.chart.axis.ValueAxis valueAxis58 = null;
        org.jfree.chart.axis.ValueAxis valueAxis59 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer60 = null;
        org.jfree.chart.plot.XYPlot xYPlot61 = new org.jfree.chart.plot.XYPlot(xYDataset57, valueAxis58, valueAxis59, xYItemRenderer60);
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo63 = null;
        java.awt.geom.Point2D point2D64 = null;
        xYPlot61.zoomRangeAxes(0.0d, plotRenderingInfo63, point2D64, false);
        xYPlot61.setDomainCrosshairValue((double) 10L);
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer69 = null;
        xYPlot61.setRenderer(xYItemRenderer69);
        int int71 = xYPlot61.getBackgroundImageAlignment();
        xYPlot61.setRangeMinorGridlinesVisible(true);
        java.awt.Stroke stroke74 = xYPlot61.getRangeMinorGridlineStroke();
        org.jfree.chart.plot.PlotOrientation plotOrientation75 = xYPlot61.getOrientation();
        xYPlot44.setOrientation(plotOrientation75);
        org.jfree.chart.util.RectangleEdge rectangleEdge77 = org.jfree.chart.plot.Plot.resolveRangeAxisLocation(axisLocation38, plotOrientation75);
        org.junit.Assert.assertTrue("Contract failed: equals-hashcode on xYPlot27 and xYPlot44", xYPlot27.equals(xYPlot44) ? xYPlot27.hashCode() == xYPlot44.hashCode() : true);
    }

    @Test
    public void test510() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest1.test510");
        org.jfree.data.xy.XYDataset xYDataset0 = null;
        org.jfree.chart.axis.ValueAxis valueAxis1 = null;
        org.jfree.chart.axis.ValueAxis valueAxis2 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer3 = null;
        org.jfree.chart.plot.XYPlot xYPlot4 = new org.jfree.chart.plot.XYPlot(xYDataset0, valueAxis1, valueAxis2, xYItemRenderer3);
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo6 = null;
        java.awt.geom.Point2D point2D7 = null;
        xYPlot4.zoomRangeAxes(0.0d, plotRenderingInfo6, point2D7, false);
        org.jfree.data.xy.XYDataset xYDataset10 = null;
        org.jfree.chart.axis.ValueAxis valueAxis11 = null;
        org.jfree.chart.axis.ValueAxis valueAxis12 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer13 = null;
        org.jfree.chart.plot.XYPlot xYPlot14 = new org.jfree.chart.plot.XYPlot(xYDataset10, valueAxis11, valueAxis12, xYItemRenderer13);
        java.awt.Paint paint15 = xYPlot14.getRangeMinorGridlinePaint();
        xYPlot4.setRangeZeroBaselinePaint(paint15);
        xYPlot4.setDomainCrosshairVisible(true);
        xYPlot4.clearRangeMarkers();
        java.awt.Stroke stroke20 = org.jfree.chart.plot.Plot.DEFAULT_OUTLINE_STROKE;
        xYPlot4.setDomainGridlineStroke(stroke20);
        boolean boolean22 = xYPlot4.isDomainMinorGridlinesVisible();
        boolean boolean23 = xYPlot4.isDomainZoomable();
        xYPlot4.setRangeCrosshairValue((double) 10.0f);
        xYPlot4.setDomainCrosshairLockedOnData(false);
        org.jfree.data.xy.XYDataset xYDataset28 = null;
        org.jfree.chart.axis.ValueAxis valueAxis29 = null;
        org.jfree.chart.axis.ValueAxis valueAxis30 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer31 = null;
        org.jfree.chart.plot.XYPlot xYPlot32 = new org.jfree.chart.plot.XYPlot(xYDataset28, valueAxis29, valueAxis30, xYItemRenderer31);
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo34 = null;
        java.awt.geom.Point2D point2D35 = null;
        xYPlot32.zoomRangeAxes(0.0d, plotRenderingInfo34, point2D35, false);
        boolean boolean38 = xYPlot32.isDomainZoomable();
        boolean boolean39 = xYPlot32.canSelectByPoint();
        java.awt.Graphics2D graphics2D40 = null;
        java.awt.geom.Rectangle2D rectangle2D41 = null;
        xYPlot32.drawQuadrants(graphics2D40, rectangle2D41);
        java.awt.geom.Point2D point2D43 = xYPlot32.getQuadrantOrigin();
        java.awt.Stroke stroke44 = xYPlot32.getDomainGridlineStroke();
        xYPlot4.setRangeMinorGridlineStroke(stroke44);
        org.junit.Assert.assertTrue("Contract failed: equals-hashcode on xYPlot14 and xYPlot32", xYPlot14.equals(xYPlot32) ? xYPlot14.hashCode() == xYPlot32.hashCode() : true);
    }

    @Test
    public void test511() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest1.test511");
        org.jfree.data.xy.XYDataset xYDataset0 = null;
        org.jfree.chart.axis.ValueAxis valueAxis1 = null;
        org.jfree.chart.axis.ValueAxis valueAxis2 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer3 = null;
        org.jfree.chart.plot.XYPlot xYPlot4 = new org.jfree.chart.plot.XYPlot(xYDataset0, valueAxis1, valueAxis2, xYItemRenderer3);
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo6 = null;
        java.awt.geom.Point2D point2D7 = null;
        xYPlot4.zoomRangeAxes(0.0d, plotRenderingInfo6, point2D7, false);
        org.jfree.data.xy.XYDataset xYDataset10 = null;
        org.jfree.chart.axis.ValueAxis valueAxis11 = null;
        org.jfree.chart.axis.ValueAxis valueAxis12 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer13 = null;
        org.jfree.chart.plot.XYPlot xYPlot14 = new org.jfree.chart.plot.XYPlot(xYDataset10, valueAxis11, valueAxis12, xYItemRenderer13);
        java.awt.Paint paint15 = xYPlot14.getRangeMinorGridlinePaint();
        xYPlot4.setRangeZeroBaselinePaint(paint15);
        xYPlot4.setDomainCrosshairVisible(true);
        xYPlot4.clearRangeMarkers();
        java.awt.Stroke stroke20 = org.jfree.chart.plot.Plot.DEFAULT_OUTLINE_STROKE;
        xYPlot4.setDomainGridlineStroke(stroke20);
        boolean boolean22 = xYPlot4.isDomainMinorGridlinesVisible();
        boolean boolean23 = xYPlot4.isDomainZoomable();
        boolean boolean24 = xYPlot4.isRangeZoomable();
        org.jfree.chart.event.MarkerChangeEvent markerChangeEvent25 = null;
        xYPlot4.markerChanged(markerChangeEvent25);
        org.jfree.data.xy.XYDataset xYDataset27 = null;
        org.jfree.chart.axis.ValueAxis valueAxis28 = null;
        org.jfree.chart.axis.ValueAxis valueAxis29 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer30 = null;
        org.jfree.chart.plot.XYPlot xYPlot31 = new org.jfree.chart.plot.XYPlot(xYDataset27, valueAxis28, valueAxis29, xYItemRenderer30);
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo33 = null;
        java.awt.geom.Point2D point2D34 = null;
        xYPlot31.zoomRangeAxes(0.0d, plotRenderingInfo33, point2D34, false);
        org.jfree.chart.axis.AxisSpace axisSpace37 = null;
        xYPlot31.setFixedDomainAxisSpace(axisSpace37);
        java.awt.Stroke stroke39 = xYPlot31.getDomainZeroBaselineStroke();
        int int40 = xYPlot31.getDomainAxisCount();
        boolean boolean41 = xYPlot31.isRangeCrosshairLockedOnData();
        xYPlot31.clearSelection();
        java.awt.Stroke stroke43 = xYPlot31.getRangeZeroBaselineStroke();
        org.jfree.data.xy.XYDataset xYDataset45 = null;
        org.jfree.chart.axis.ValueAxis valueAxis46 = null;
        org.jfree.chart.axis.ValueAxis valueAxis47 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer48 = null;
        org.jfree.chart.plot.XYPlot xYPlot49 = new org.jfree.chart.plot.XYPlot(xYDataset45, valueAxis46, valueAxis47, xYItemRenderer48);
        boolean boolean50 = xYPlot49.isDomainGridlinesVisible();
        org.jfree.chart.axis.ValueAxis valueAxis51 = null;
        int int52 = xYPlot49.getRangeAxisIndex(valueAxis51);
        xYPlot49.setDomainGridlinesVisible(false);
        org.jfree.chart.plot.Marker marker56 = null;
        org.jfree.chart.util.Layer layer57 = null;
        boolean boolean58 = xYPlot49.removeDomainMarker((int) (short) -1, marker56, layer57);
        java.awt.Graphics2D graphics2D59 = null;
        java.awt.geom.Rectangle2D rectangle2D60 = null;
        java.util.List list61 = null;
        xYPlot49.drawDomainGridlines(graphics2D59, rectangle2D60, list61);
        org.jfree.chart.axis.AxisLocation axisLocation64 = xYPlot49.getRangeAxisLocation(15);
        xYPlot31.setDomainAxisLocation((int) 'a', axisLocation64, false);
        xYPlot4.setDomainAxisLocation(axisLocation64);
        // This assertion (symmetry of equals) fails
        org.junit.Assert.assertTrue("Contract failed: equals-symmetric on xYPlot14 and xYPlot31.", xYPlot14.equals(xYPlot31) == xYPlot31.equals(xYPlot14));
    }

    @Test
    public void test512() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest1.test512");
        org.jfree.data.xy.XYDataset xYDataset0 = null;
        org.jfree.chart.axis.ValueAxis valueAxis1 = null;
        org.jfree.chart.axis.ValueAxis valueAxis2 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer3 = null;
        org.jfree.chart.plot.XYPlot xYPlot4 = new org.jfree.chart.plot.XYPlot(xYDataset0, valueAxis1, valueAxis2, xYItemRenderer3);
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo6 = null;
        java.awt.geom.Point2D point2D7 = null;
        xYPlot4.zoomRangeAxes(0.0d, plotRenderingInfo6, point2D7, false);
        org.jfree.chart.axis.AxisSpace axisSpace10 = null;
        xYPlot4.setFixedDomainAxisSpace(axisSpace10);
        java.awt.Stroke stroke12 = xYPlot4.getDomainZeroBaselineStroke();
        int int13 = xYPlot4.getDomainAxisCount();
        boolean boolean14 = xYPlot4.isRangeCrosshairLockedOnData();
        java.awt.Graphics2D graphics2D15 = null;
        java.awt.geom.Rectangle2D rectangle2D16 = null;
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo17 = null;
        xYPlot4.drawAnnotations(graphics2D15, rectangle2D16, plotRenderingInfo17);
        org.jfree.chart.axis.AxisSpace axisSpace19 = xYPlot4.getFixedRangeAxisSpace();
        java.awt.Graphics2D graphics2D20 = null;
        java.awt.geom.Rectangle2D rectangle2D21 = null;
        org.jfree.chart.util.Layer layer23 = null;
        xYPlot4.drawDomainMarkers(graphics2D20, rectangle2D21, 0, layer23);
        org.jfree.chart.axis.ValueAxis valueAxis25 = xYPlot4.getRangeAxis();
        java.awt.Graphics2D graphics2D26 = null;
        java.awt.geom.Rectangle2D rectangle2D27 = null;
        org.jfree.data.xy.XYDataset xYDataset28 = null;
        org.jfree.chart.axis.ValueAxis valueAxis29 = null;
        org.jfree.chart.axis.ValueAxis valueAxis30 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer31 = null;
        org.jfree.chart.plot.XYPlot xYPlot32 = new org.jfree.chart.plot.XYPlot(xYDataset28, valueAxis29, valueAxis30, xYItemRenderer31);
        org.jfree.chart.plot.Marker marker33 = null;
        boolean boolean34 = xYPlot32.removeDomainMarker(marker33);
        org.jfree.chart.axis.AxisLocation axisLocation36 = xYPlot32.getRangeAxisLocation((int) (byte) -1);
        int int37 = xYPlot32.getBackgroundImageAlignment();
        xYPlot32.setRangeMinorGridlinesVisible(true);
        double double40 = xYPlot32.getRangeCrosshairValue();
        xYPlot32.setRangeGridlinesVisible(true);
        xYPlot32.clearDomainMarkers();
        java.awt.Graphics2D graphics2D44 = null;
        java.awt.geom.Rectangle2D rectangle2D45 = null;
        org.jfree.data.xy.XYDataset xYDataset46 = null;
        org.jfree.chart.axis.ValueAxis valueAxis47 = null;
        org.jfree.chart.axis.ValueAxis valueAxis48 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer49 = null;
        org.jfree.chart.plot.XYPlot xYPlot50 = new org.jfree.chart.plot.XYPlot(xYDataset46, valueAxis47, valueAxis48, xYItemRenderer49);
        boolean boolean51 = xYPlot50.isDomainGridlinesVisible();
        org.jfree.chart.axis.ValueAxis valueAxis52 = null;
        int int53 = xYPlot50.getRangeAxisIndex(valueAxis52);
        xYPlot50.setDomainGridlinesVisible(false);
        org.jfree.chart.plot.Marker marker57 = null;
        org.jfree.chart.util.Layer layer58 = null;
        boolean boolean59 = xYPlot50.removeDomainMarker((int) (short) -1, marker57, layer58);
        org.jfree.data.xy.XYDataset xYDataset60 = null;
        org.jfree.chart.axis.ValueAxis valueAxis61 = null;
        org.jfree.chart.axis.ValueAxis valueAxis62 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer63 = null;
        org.jfree.chart.plot.XYPlot xYPlot64 = new org.jfree.chart.plot.XYPlot(xYDataset60, valueAxis61, valueAxis62, xYItemRenderer63);
        boolean boolean65 = xYPlot64.isDomainGridlinesVisible();
        java.awt.Stroke stroke66 = xYPlot64.getRangeMinorGridlineStroke();
        java.awt.Stroke stroke67 = xYPlot64.getDomainMinorGridlineStroke();
        java.awt.Graphics2D graphics2D68 = null;
        java.awt.geom.Rectangle2D rectangle2D69 = null;
        org.jfree.chart.axis.AxisSpace axisSpace70 = null;
        org.jfree.chart.axis.AxisSpace axisSpace71 = xYPlot64.calculateRangeAxisSpace(graphics2D68, rectangle2D69, axisSpace70);
        xYPlot50.setFixedRangeAxisSpace(axisSpace71);
        org.jfree.chart.axis.AxisSpace axisSpace73 = xYPlot32.calculateDomainAxisSpace(graphics2D44, rectangle2D45, axisSpace71);
        org.jfree.chart.axis.AxisSpace axisSpace74 = xYPlot4.calculateRangeAxisSpace(graphics2D26, rectangle2D27, axisSpace71);
        org.junit.Assert.assertTrue("Contract failed: equals-hashcode on xYPlot4 and xYPlot64", xYPlot4.equals(xYPlot64) ? xYPlot4.hashCode() == xYPlot64.hashCode() : true);
    }

    @Test
    public void test513() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest1.test513");
        org.jfree.data.xy.XYDataset xYDataset0 = null;
        org.jfree.chart.axis.ValueAxis valueAxis1 = null;
        org.jfree.chart.axis.ValueAxis valueAxis2 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer3 = null;
        org.jfree.chart.plot.XYPlot xYPlot4 = new org.jfree.chart.plot.XYPlot(xYDataset0, valueAxis1, valueAxis2, xYItemRenderer3);
        boolean boolean5 = xYPlot4.isDomainGridlinesVisible();
        org.jfree.chart.axis.ValueAxis valueAxis6 = null;
        int int7 = xYPlot4.getRangeAxisIndex(valueAxis6);
        xYPlot4.setDomainMinorGridlinesVisible(false);
        org.jfree.data.xy.XYDataset xYDataset10 = null;
        org.jfree.chart.axis.ValueAxis valueAxis11 = null;
        org.jfree.chart.axis.ValueAxis valueAxis12 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer13 = null;
        org.jfree.chart.plot.XYPlot xYPlot14 = new org.jfree.chart.plot.XYPlot(xYDataset10, valueAxis11, valueAxis12, xYItemRenderer13);
        org.jfree.chart.plot.Marker marker15 = null;
        boolean boolean16 = xYPlot14.removeDomainMarker(marker15);
        org.jfree.chart.axis.AxisLocation axisLocation18 = xYPlot14.getRangeAxisLocation((int) (byte) -1);
        int int19 = xYPlot14.getBackgroundImageAlignment();
        xYPlot14.setRangeMinorGridlinesVisible(true);
        org.jfree.data.xy.XYDataset xYDataset22 = null;
        org.jfree.chart.axis.ValueAxis valueAxis23 = null;
        org.jfree.chart.axis.ValueAxis valueAxis24 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer25 = null;
        org.jfree.chart.plot.XYPlot xYPlot26 = new org.jfree.chart.plot.XYPlot(xYDataset22, valueAxis23, valueAxis24, xYItemRenderer25);
        boolean boolean27 = xYPlot26.isDomainGridlinesVisible();
        org.jfree.chart.axis.ValueAxis valueAxis28 = null;
        int int29 = xYPlot26.getRangeAxisIndex(valueAxis28);
        java.awt.Stroke stroke30 = xYPlot26.getDomainGridlineStroke();
        xYPlot14.setDomainZeroBaselineStroke(stroke30);
        xYPlot4.setDomainZeroBaselineStroke(stroke30);
        xYPlot4.setRangePannable(true);
        java.awt.Font font35 = xYPlot4.getNoDataMessageFont();
        java.awt.Stroke stroke36 = xYPlot4.getDomainZeroBaselineStroke();
        org.jfree.chart.plot.PlotOrientation plotOrientation37 = xYPlot4.getOrientation();
        org.jfree.data.xy.XYDataset xYDataset38 = null;
        org.jfree.chart.axis.ValueAxis valueAxis39 = null;
        org.jfree.chart.axis.ValueAxis valueAxis40 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer41 = null;
        org.jfree.chart.plot.XYPlot xYPlot42 = new org.jfree.chart.plot.XYPlot(xYDataset38, valueAxis39, valueAxis40, xYItemRenderer41);
        org.jfree.chart.plot.Marker marker43 = null;
        boolean boolean44 = xYPlot42.removeDomainMarker(marker43);
        org.jfree.chart.axis.AxisLocation axisLocation46 = xYPlot42.getRangeAxisLocation((int) (byte) -1);
        int int47 = xYPlot42.getBackgroundImageAlignment();
        org.jfree.chart.axis.AxisLocation axisLocation49 = xYPlot42.getDomainAxisLocation(15);
        org.jfree.chart.util.RectangleEdge rectangleEdge51 = xYPlot42.getDomainAxisEdge(1);
        double double52 = xYPlot42.getRangeCrosshairValue();
        java.awt.Paint paint53 = xYPlot42.getBackgroundPaint();
        org.jfree.data.xy.XYDataset xYDataset54 = null;
        xYPlot42.setDataset(xYDataset54);
        java.awt.Paint paint56 = xYPlot42.getBackgroundPaint();
        xYPlot4.setRangeGridlinePaint(paint56);
        org.junit.Assert.assertTrue("Contract failed: equals-hashcode on xYPlot26 and xYPlot42", xYPlot26.equals(xYPlot42) ? xYPlot26.hashCode() == xYPlot42.hashCode() : true);
    }

    @Test
    public void test514() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest1.test514");
        org.jfree.data.xy.XYDataset xYDataset0 = null;
        org.jfree.chart.axis.ValueAxis valueAxis1 = null;
        org.jfree.chart.axis.ValueAxis valueAxis2 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer3 = null;
        org.jfree.chart.plot.XYPlot xYPlot4 = new org.jfree.chart.plot.XYPlot(xYDataset0, valueAxis1, valueAxis2, xYItemRenderer3);
        java.awt.Paint paint5 = xYPlot4.getRangeMinorGridlinePaint();
        org.jfree.chart.axis.ValueAxis valueAxis7 = null;
        xYPlot4.setRangeAxis((int) ' ', valueAxis7, false);
        xYPlot4.setRangeCrosshairVisible(false);
        org.jfree.data.xy.XYDataset xYDataset12 = null;
        org.jfree.chart.axis.ValueAxis valueAxis13 = null;
        org.jfree.chart.axis.ValueAxis valueAxis14 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer15 = null;
        org.jfree.chart.plot.XYPlot xYPlot16 = new org.jfree.chart.plot.XYPlot(xYDataset12, valueAxis13, valueAxis14, xYItemRenderer15);
        org.jfree.chart.plot.Marker marker17 = null;
        boolean boolean18 = xYPlot16.removeDomainMarker(marker17);
        org.jfree.chart.event.MarkerChangeEvent markerChangeEvent19 = null;
        xYPlot16.markerChanged(markerChangeEvent19);
        java.awt.Stroke stroke21 = xYPlot16.getDomainCrosshairStroke();
        xYPlot4.setDomainZeroBaselineStroke(stroke21);
        org.jfree.data.xy.XYDataset xYDataset23 = null;
        xYPlot4.setDataset(xYDataset23);
        org.jfree.data.xy.XYDataset xYDataset25 = null;
        org.jfree.chart.axis.ValueAxis valueAxis26 = null;
        org.jfree.chart.axis.ValueAxis valueAxis27 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer28 = null;
        org.jfree.chart.plot.XYPlot xYPlot29 = new org.jfree.chart.plot.XYPlot(xYDataset25, valueAxis26, valueAxis27, xYItemRenderer28);
        org.jfree.chart.plot.Marker marker30 = null;
        boolean boolean31 = xYPlot29.removeDomainMarker(marker30);
        org.jfree.chart.axis.AxisLocation axisLocation33 = xYPlot29.getRangeAxisLocation((int) (byte) -1);
        int int34 = xYPlot29.getBackgroundImageAlignment();
        xYPlot29.setRangeMinorGridlinesVisible(true);
        org.jfree.chart.renderer.xy.XYItemRenderer[] xYItemRendererArray37 = new org.jfree.chart.renderer.xy.XYItemRenderer[] {};
        xYPlot29.setRenderers(xYItemRendererArray37);
        org.jfree.chart.util.RectangleEdge rectangleEdge40 = xYPlot29.getDomainAxisEdge((int) (byte) 0);
        java.awt.Paint paint41 = xYPlot29.getRangeGridlinePaint();
        xYPlot4.setDomainCrosshairPaint(paint41);
        xYPlot4.setDomainCrosshairVisible(true);
        org.jfree.chart.axis.ValueAxis valueAxis46 = xYPlot4.getDomainAxisForDataset((int) (byte) 0);
        java.awt.Paint paint47 = xYPlot4.getRangeCrosshairPaint();
        org.jfree.data.xy.XYDataset xYDataset48 = null;
        org.jfree.chart.axis.ValueAxis valueAxis49 = null;
        org.jfree.chart.axis.ValueAxis valueAxis50 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer51 = null;
        org.jfree.chart.plot.XYPlot xYPlot52 = new org.jfree.chart.plot.XYPlot(xYDataset48, valueAxis49, valueAxis50, xYItemRenderer51);
        java.awt.geom.Point2D point2D53 = xYPlot52.getQuadrantOrigin();
        java.awt.Paint paint54 = xYPlot52.getOutlinePaint();
        java.awt.Graphics2D graphics2D55 = null;
        java.awt.geom.Rectangle2D rectangle2D56 = null;
        java.util.List list57 = null;
        xYPlot52.drawRangeGridlines(graphics2D55, rectangle2D56, list57);
        xYPlot4.setParent((org.jfree.chart.plot.Plot) xYPlot52);
        org.junit.Assert.assertTrue("Contract failed: equals-hashcode on xYPlot16 and xYPlot52", xYPlot16.equals(xYPlot52) ? xYPlot16.hashCode() == xYPlot52.hashCode() : true);
    }

    @Test
    public void test515() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest1.test515");
        org.jfree.data.xy.XYDataset xYDataset0 = null;
        org.jfree.chart.axis.ValueAxis valueAxis1 = null;
        org.jfree.chart.axis.ValueAxis valueAxis2 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer3 = null;
        org.jfree.chart.plot.XYPlot xYPlot4 = new org.jfree.chart.plot.XYPlot(xYDataset0, valueAxis1, valueAxis2, xYItemRenderer3);
        boolean boolean5 = xYPlot4.isDomainGridlinesVisible();
        org.jfree.chart.axis.ValueAxis valueAxis6 = null;
        int int7 = xYPlot4.getRangeAxisIndex(valueAxis6);
        xYPlot4.setDomainGridlinesVisible(false);
        boolean boolean10 = xYPlot4.isOutlineVisible();
        java.awt.Stroke stroke11 = xYPlot4.getDomainGridlineStroke();
        boolean boolean12 = xYPlot4.canSelectByPoint();
        org.jfree.chart.util.Layer layer14 = null;
        java.util.Collection collection15 = xYPlot4.getRangeMarkers((int) '4', layer14);
        org.jfree.chart.axis.ValueAxis valueAxis16 = null;
        org.jfree.data.Range range17 = xYPlot4.getDataRange(valueAxis16);
        org.jfree.data.xy.XYDataset xYDataset18 = null;
        org.jfree.chart.axis.ValueAxis valueAxis19 = null;
        org.jfree.chart.axis.ValueAxis valueAxis20 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer21 = null;
        org.jfree.chart.plot.XYPlot xYPlot22 = new org.jfree.chart.plot.XYPlot(xYDataset18, valueAxis19, valueAxis20, xYItemRenderer21);
        boolean boolean23 = xYPlot22.isDomainGridlinesVisible();
        java.awt.Stroke stroke24 = xYPlot22.getDomainCrosshairStroke();
        xYPlot22.clearDomainMarkers();
        java.awt.Stroke stroke26 = xYPlot22.getDomainZeroBaselineStroke();
        xYPlot4.setDomainZeroBaselineStroke(stroke26);
        xYPlot4.setOutlineVisible(true);
        java.awt.Graphics2D graphics2D30 = null;
        java.awt.geom.Rectangle2D rectangle2D31 = null;
        org.jfree.data.xy.XYDataset xYDataset32 = null;
        org.jfree.chart.axis.ValueAxis valueAxis33 = null;
        org.jfree.chart.axis.ValueAxis valueAxis34 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer35 = null;
        org.jfree.chart.plot.XYPlot xYPlot36 = new org.jfree.chart.plot.XYPlot(xYDataset32, valueAxis33, valueAxis34, xYItemRenderer35);
        boolean boolean37 = xYPlot36.isDomainGridlinesVisible();
        org.jfree.chart.axis.ValueAxis valueAxis38 = null;
        int int39 = xYPlot36.getRangeAxisIndex(valueAxis38);
        xYPlot36.setDomainGridlinesVisible(false);
        org.jfree.chart.plot.Marker marker43 = null;
        org.jfree.chart.util.Layer layer44 = null;
        boolean boolean45 = xYPlot36.removeDomainMarker((int) (short) -1, marker43, layer44);
        java.awt.Paint paint46 = xYPlot36.getDomainMinorGridlinePaint();
        org.jfree.chart.axis.ValueAxis valueAxis48 = null;
        xYPlot36.setDomainAxis((int) (short) 100, valueAxis48, false);
        java.util.List list51 = xYPlot36.getAnnotations();
        xYPlot4.drawRangeTickBands(graphics2D30, rectangle2D31, list51);
        org.junit.Assert.assertTrue("Contract failed: equals-hashcode on xYPlot4 and xYPlot36", xYPlot4.equals(xYPlot36) ? xYPlot4.hashCode() == xYPlot36.hashCode() : true);
    }

    @Test
    public void test516() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest1.test516");
        org.jfree.data.xy.XYDataset xYDataset0 = null;
        org.jfree.chart.axis.ValueAxis valueAxis1 = null;
        org.jfree.chart.axis.ValueAxis valueAxis2 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer3 = null;
        org.jfree.chart.plot.XYPlot xYPlot4 = new org.jfree.chart.plot.XYPlot(xYDataset0, valueAxis1, valueAxis2, xYItemRenderer3);
        boolean boolean5 = xYPlot4.isDomainGridlinesVisible();
        org.jfree.chart.axis.ValueAxis valueAxis6 = null;
        int int7 = xYPlot4.getRangeAxisIndex(valueAxis6);
        boolean boolean8 = xYPlot4.isOutlineVisible();
        org.jfree.data.xy.XYDataset xYDataset9 = null;
        org.jfree.chart.axis.ValueAxis valueAxis10 = null;
        org.jfree.chart.axis.ValueAxis valueAxis11 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer12 = null;
        org.jfree.chart.plot.XYPlot xYPlot13 = new org.jfree.chart.plot.XYPlot(xYDataset9, valueAxis10, valueAxis11, xYItemRenderer12);
        boolean boolean14 = xYPlot13.isDomainGridlinesVisible();
        org.jfree.chart.axis.ValueAxis valueAxis15 = null;
        xYPlot13.setRangeAxis(valueAxis15);
        org.jfree.chart.event.PlotChangeListener plotChangeListener17 = null;
        xYPlot13.addChangeListener(plotChangeListener17);
        org.jfree.chart.event.AxisChangeEvent axisChangeEvent19 = null;
        xYPlot13.axisChanged(axisChangeEvent19);
        org.jfree.chart.LegendItemCollection legendItemCollection21 = xYPlot13.getLegendItems();
        java.awt.Paint paint22 = xYPlot13.getDomainGridlinePaint();
        xYPlot4.setDomainTickBandPaint(paint22);
        boolean boolean24 = xYPlot4.canSelectByPoint();
        java.awt.Stroke stroke25 = xYPlot4.getDomainMinorGridlineStroke();
        org.jfree.chart.axis.AxisLocation axisLocation27 = xYPlot4.getRangeAxisLocation((int) (short) 1);
        org.jfree.data.xy.XYDataset xYDataset28 = null;
        org.jfree.chart.axis.ValueAxis valueAxis29 = null;
        org.jfree.chart.axis.ValueAxis valueAxis30 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer31 = null;
        org.jfree.chart.plot.XYPlot xYPlot32 = new org.jfree.chart.plot.XYPlot(xYDataset28, valueAxis29, valueAxis30, xYItemRenderer31);
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo34 = null;
        java.awt.geom.Point2D point2D35 = null;
        xYPlot32.zoomRangeAxes(0.0d, plotRenderingInfo34, point2D35, false);
        boolean boolean38 = xYPlot32.isDomainZoomable();
        boolean boolean39 = xYPlot32.canSelectByPoint();
        java.awt.Graphics2D graphics2D40 = null;
        java.awt.geom.Rectangle2D rectangle2D41 = null;
        java.util.List list42 = null;
        xYPlot32.drawDomainGridlines(graphics2D40, rectangle2D41, list42);
        org.jfree.chart.plot.PlotOrientation plotOrientation44 = xYPlot32.getOrientation();
        org.jfree.chart.util.RectangleEdge rectangleEdge45 = org.jfree.chart.plot.Plot.resolveDomainAxisLocation(axisLocation27, plotOrientation44);
        org.junit.Assert.assertTrue("Contract failed: equals-hashcode on xYPlot13 and xYPlot32", xYPlot13.equals(xYPlot32) ? xYPlot13.hashCode() == xYPlot32.hashCode() : true);
    }

    @Test
    public void test517() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest1.test517");
        org.jfree.data.xy.XYDataset xYDataset0 = null;
        org.jfree.chart.axis.ValueAxis valueAxis1 = null;
        org.jfree.chart.axis.ValueAxis valueAxis2 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer3 = null;
        org.jfree.chart.plot.XYPlot xYPlot4 = new org.jfree.chart.plot.XYPlot(xYDataset0, valueAxis1, valueAxis2, xYItemRenderer3);
        java.awt.Paint paint5 = xYPlot4.getRangeMinorGridlinePaint();
        org.jfree.chart.axis.ValueAxis valueAxis7 = null;
        xYPlot4.setRangeAxis((int) ' ', valueAxis7, false);
        xYPlot4.setRangeCrosshairVisible(false);
        org.jfree.data.xy.XYDataset xYDataset12 = null;
        org.jfree.chart.axis.ValueAxis valueAxis13 = null;
        org.jfree.chart.axis.ValueAxis valueAxis14 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer15 = null;
        org.jfree.chart.plot.XYPlot xYPlot16 = new org.jfree.chart.plot.XYPlot(xYDataset12, valueAxis13, valueAxis14, xYItemRenderer15);
        org.jfree.chart.plot.Marker marker17 = null;
        boolean boolean18 = xYPlot16.removeDomainMarker(marker17);
        org.jfree.chart.event.MarkerChangeEvent markerChangeEvent19 = null;
        xYPlot16.markerChanged(markerChangeEvent19);
        java.awt.Stroke stroke21 = xYPlot16.getDomainCrosshairStroke();
        xYPlot4.setDomainZeroBaselineStroke(stroke21);
        org.jfree.chart.plot.DrawingSupplier drawingSupplier23 = xYPlot4.getDrawingSupplier();
        xYPlot4.setDomainMinorGridlinesVisible(false);
        org.jfree.data.xy.XYDataset xYDataset26 = null;
        org.jfree.chart.axis.ValueAxis valueAxis27 = null;
        org.jfree.chart.axis.ValueAxis valueAxis28 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer29 = null;
        org.jfree.chart.plot.XYPlot xYPlot30 = new org.jfree.chart.plot.XYPlot(xYDataset26, valueAxis27, valueAxis28, xYItemRenderer29);
        java.awt.geom.Point2D point2D31 = xYPlot30.getQuadrantOrigin();
        java.awt.geom.GeneralPath generalPath32 = null;
        java.awt.geom.Rectangle2D rectangle2D33 = null;
        org.jfree.chart.RenderingSource renderingSource34 = null;
        xYPlot30.select(generalPath32, rectangle2D33, renderingSource34);
        org.jfree.data.xy.XYDataset xYDataset36 = null;
        org.jfree.chart.axis.ValueAxis valueAxis37 = null;
        org.jfree.chart.axis.ValueAxis valueAxis38 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer39 = null;
        org.jfree.chart.plot.XYPlot xYPlot40 = new org.jfree.chart.plot.XYPlot(xYDataset36, valueAxis37, valueAxis38, xYItemRenderer39);
        org.jfree.chart.axis.AxisLocation axisLocation41 = xYPlot40.getRangeAxisLocation();
        xYPlot40.setForegroundAlpha((-1.0f));
        org.jfree.chart.plot.Plot plot44 = xYPlot40.getParent();
        org.jfree.chart.axis.ValueAxis valueAxis45 = xYPlot40.getRangeAxis();
        org.jfree.chart.axis.AxisLocation axisLocation47 = xYPlot40.getDomainAxisLocation(15);
        xYPlot30.setDomainAxisLocation(axisLocation47, true);
        org.jfree.data.xy.XYDataset xYDataset50 = null;
        org.jfree.chart.axis.ValueAxis valueAxis51 = null;
        org.jfree.chart.axis.ValueAxis valueAxis52 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer53 = null;
        org.jfree.chart.plot.XYPlot xYPlot54 = new org.jfree.chart.plot.XYPlot(xYDataset50, valueAxis51, valueAxis52, xYItemRenderer53);
        org.jfree.chart.plot.PlotRenderingInfo plotRenderingInfo56 = null;
        java.awt.geom.Point2D point2D57 = null;
        xYPlot54.zoomRangeAxes(0.0d, plotRenderingInfo56, point2D57, false);
        xYPlot54.setDomainCrosshairValue((double) 10L);
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer62 = null;
        xYPlot54.setRenderer(xYItemRenderer62);
        int int64 = xYPlot54.getBackgroundImageAlignment();
        xYPlot54.setRangeMinorGridlinesVisible(true);
        java.awt.Stroke stroke67 = xYPlot54.getRangeMinorGridlineStroke();
        org.jfree.chart.plot.PlotOrientation plotOrientation68 = xYPlot54.getOrientation();
        org.jfree.chart.util.RectangleEdge rectangleEdge69 = org.jfree.chart.plot.Plot.resolveRangeAxisLocation(axisLocation47, plotOrientation68);
        xYPlot4.setOrientation(plotOrientation68);
        org.jfree.chart.LegendItemCollection legendItemCollection71 = xYPlot4.getFixedLegendItems();
        org.jfree.data.xy.XYDataset xYDataset72 = null;
        org.jfree.chart.axis.ValueAxis valueAxis73 = null;
        org.jfree.chart.axis.ValueAxis valueAxis74 = null;
        org.jfree.chart.renderer.xy.XYItemRenderer xYItemRenderer75 = null;
        org.jfree.chart.plot.XYPlot xYPlot76 = new org.jfree.chart.plot.XYPlot(xYDataset72, valueAxis73, valueAxis74, xYItemRenderer75);
        boolean boolean77 = xYPlot76.isDomainGridlinesVisible();
        org.jfree.chart.axis.ValueAxis valueAxis78 = null;
        int int79 = xYPlot76.getRangeAxisIndex(valueAxis78);
        boolean boolean80 = xYPlot76.isOutlineVisible();
        int int81 = xYPlot76.getBackgroundImageAlignment();
        xYPlot76.configureRangeAxes();
        org.jfree.chart.plot.Plot plot83 = xYPlot76.getRootPlot();
        float float84 = xYPlot76.getBackgroundImageAlpha();
        java.awt.Stroke stroke85 = xYPlot76.getRangeCrosshairStroke();
        xYPlot4.setOutlineStroke(stroke85);
        org.junit.Assert.assertTrue("Contract failed: equals-hashcode on xYPlot16 and xYPlot76", xYPlot16.equals(xYPlot76) ? xYPlot16.hashCode() == xYPlot76.hashCode() : true);
    }
}

