package org.mockito;

import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RegressionTest6 {

    public static boolean debug = false;

    public void assertBooleanArrayEquals(boolean[] expectedArray, boolean[] actualArray) {
        if (expectedArray.length != actualArray.length) {
            throw new AssertionError("Array lengths differ: " + expectedArray.length + " != " + actualArray.length);
        }
        for (int i = 0; i < expectedArray.length; i++) {
            if (expectedArray[i] != actualArray[i]) {
                throw new AssertionError("Arrays differ at index " + i + ": " + expectedArray[i] + " != " + actualArray[i]);
            }
        }
    }

    @Test
    public void test3001() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest6.test3001");
        java.util.Map map0 = org.mockito.Matchers.anyMap();
        java.util.Map map1 = org.mockito.Matchers.eq(map0);
        java.util.Map map2 = org.mockito.Matchers.same(map0);
        java.util.List list3 = org.mockito.Matchers.anyList();
        java.util.Collection collection4 = org.mockito.Matchers.eq((java.util.Collection) list3);
        java.lang.String[] strArray5 = null;
        java.util.List list6 = org.mockito.Matchers.refEq(list3, strArray5);
        java.util.List list8 = org.mockito.Matchers.anyList();
        java.lang.String[] strArray9 = null;
        java.util.Map map11 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray14 = new java.lang.String[] { "", "" };
        java.util.Map map15 = org.mockito.Matchers.refEq(map11, strArray14);
        java.lang.CharSequence charSequence16 = org.mockito.Matchers.refEq((java.lang.CharSequence) "", strArray14);
        java.lang.String[] strArray17 = org.mockito.Matchers.refEq(strArray9, strArray14);
        java.util.List list18 = org.mockito.Matchers.refEq(list8, strArray14);
        java.util.Set set19 = org.mockito.Matchers.anySet();
        java.util.Set set20 = org.mockito.Matchers.eq(set19);
        java.lang.Iterable iterable21 = org.mockito.Matchers.same((java.lang.Iterable) set19);
        java.util.List list22 = org.mockito.Matchers.anyList();
        java.lang.Class<?> wildcardClass23 = list22.getClass();
        java.lang.reflect.GenericDeclaration genericDeclaration24 = org.mockito.Matchers.same((java.lang.reflect.GenericDeclaration) wildcardClass23);
        java.lang.reflect.Type type25 = org.mockito.Matchers.same((java.lang.reflect.Type) wildcardClass23);
        java.lang.Object obj27 = new java.lang.Object();
        java.lang.Class<?> wildcardClass28 = obj27.getClass();
        java.util.Map map31 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray34 = new java.lang.String[] { "", "" };
        java.util.Map map35 = org.mockito.Matchers.refEq(map31, strArray34);
        java.lang.String str36 = org.mockito.Matchers.refEq("hi!", strArray34);
        java.lang.String[] strArray37 = null;
        java.util.Map map39 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray42 = new java.lang.String[] { "", "" };
        java.util.Map map43 = org.mockito.Matchers.refEq(map39, strArray42);
        java.lang.CharSequence charSequence44 = org.mockito.Matchers.refEq((java.lang.CharSequence) "", strArray42);
        java.lang.String[] strArray45 = org.mockito.Matchers.refEq(strArray37, strArray42);
        java.lang.String[] strArray46 = org.mockito.Matchers.refEq(strArray34, strArray42);
        java.lang.Object obj47 = org.mockito.Matchers.refEq((java.lang.Object) (short) 1, strArray34);
        java.io.Serializable serializable48 = org.mockito.Matchers.refEq((java.io.Serializable) wildcardClass28, strArray34);
        java.lang.String str49 = org.mockito.Matchers.refEq("", strArray34);
        java.lang.Class<?> wildcardClass50 = org.mockito.Matchers.refEq(wildcardClass23, strArray34);
        java.util.Set set51 = org.mockito.Matchers.refEq(set19, strArray34);
        java.util.Collection collection52 = org.mockito.Matchers.refEq((java.util.Collection) list8, strArray34);
        java.lang.Comparable<java.lang.String> strComparable53 = org.mockito.Matchers.refEq((java.lang.Comparable<java.lang.String>) "hi!", strArray34);
        java.util.List list54 = org.mockito.Matchers.refEq(list6, strArray34);
        java.util.Map map55 = org.mockito.Matchers.refEq(map0, strArray34);
        java.util.Map map56 = org.mockito.Matchers.same(map0);
        java.lang.Class<?> wildcardClass57 = map0.getClass();
        org.junit.Assert.assertNotNull(map0);
        org.junit.Assert.assertNull(map1);
        org.junit.Assert.assertNull(map2);
        org.junit.Assert.assertNotNull(list3);
        org.junit.Assert.assertNull(collection4);
        org.junit.Assert.assertNull(list6);
        org.junit.Assert.assertNotNull(list8);
        org.junit.Assert.assertNotNull(map11);
        org.junit.Assert.assertNotNull(strArray14);
        org.junit.Assert.assertArrayEquals(strArray14, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map15);
        org.junit.Assert.assertNull(charSequence16);
        org.junit.Assert.assertNull(strArray17);
        org.junit.Assert.assertNull(list18);
        org.junit.Assert.assertNotNull(set19);
        org.junit.Assert.assertNull(set20);
        org.junit.Assert.assertNull(iterable21);
        org.junit.Assert.assertNotNull(list22);
        org.junit.Assert.assertNotNull(wildcardClass23);
        org.junit.Assert.assertNull(genericDeclaration24);
        org.junit.Assert.assertNull(type25);
        org.junit.Assert.assertNotNull(wildcardClass28);
        org.junit.Assert.assertNotNull(map31);
        org.junit.Assert.assertNotNull(strArray34);
        org.junit.Assert.assertArrayEquals(strArray34, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map35);
        org.junit.Assert.assertNull(str36);
        org.junit.Assert.assertNotNull(map39);
        org.junit.Assert.assertNotNull(strArray42);
        org.junit.Assert.assertArrayEquals(strArray42, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map43);
        org.junit.Assert.assertNull(charSequence44);
        org.junit.Assert.assertNull(strArray45);
        org.junit.Assert.assertNull(strArray46);
        org.junit.Assert.assertNull(obj47);
        org.junit.Assert.assertNull(serializable48);
        org.junit.Assert.assertNull(str49);
        org.junit.Assert.assertNull(wildcardClass50);
        org.junit.Assert.assertNull(set51);
        org.junit.Assert.assertNull(collection52);
        org.junit.Assert.assertNull(strComparable53);
        org.junit.Assert.assertNull(list54);
        org.junit.Assert.assertNull(map55);
        org.junit.Assert.assertNull(map56);
        org.junit.Assert.assertNotNull(wildcardClass57);
    }

    @Test
    public void test3002() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest6.test3002");
        java.util.Map map2 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray5 = new java.lang.String[] { "", "" };
        java.util.Map map6 = org.mockito.Matchers.refEq(map2, strArray5);
        java.lang.CharSequence charSequence7 = org.mockito.Matchers.refEq((java.lang.CharSequence) "", strArray5);
        java.util.Set set8 = org.mockito.Matchers.anySet();
        java.util.Set set9 = org.mockito.Matchers.eq(set8);
        java.lang.Iterable iterable10 = org.mockito.Matchers.same((java.lang.Iterable) set8);
        java.util.List list11 = org.mockito.Matchers.anyList();
        java.lang.Class<?> wildcardClass12 = list11.getClass();
        java.lang.reflect.GenericDeclaration genericDeclaration13 = org.mockito.Matchers.same((java.lang.reflect.GenericDeclaration) wildcardClass12);
        java.util.Map map14 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray17 = new java.lang.String[] { "", "" };
        java.util.Map map18 = org.mockito.Matchers.refEq(map14, strArray17);
        java.lang.String[] strArray25 = new java.lang.String[] { "hi!", "hi!", "hi!", "hi!", "hi!", "" };
        java.util.Map map26 = org.mockito.Matchers.refEq(map14, strArray25);
        java.lang.reflect.AnnotatedElement annotatedElement27 = org.mockito.Matchers.refEq((java.lang.reflect.AnnotatedElement) wildcardClass12, strArray25);
        java.util.Collection collection28 = org.mockito.Matchers.refEq((java.util.Collection) set8, strArray25);
        java.util.Set set29 = org.mockito.Matchers.anySet();
        java.util.Set set30 = org.mockito.Matchers.eq(set29);
        java.util.Set set31 = org.mockito.Matchers.same(set29);
        java.util.Set set32 = org.mockito.Matchers.eq(set29);
        java.lang.String[] strArray36 = new java.lang.String[] { "hi!", "", "" };
        java.lang.Iterable iterable37 = org.mockito.Matchers.refEq((java.lang.Iterable) set29, strArray36);
        java.lang.String[] strArray38 = org.mockito.Matchers.same(strArray36);
        java.lang.Object obj39 = org.mockito.Matchers.refEq((java.lang.Object) strArray25, strArray38);
        java.lang.String[] strArray40 = org.mockito.Matchers.refEq(strArray5, strArray25);
        java.lang.String str41 = org.mockito.Matchers.refEq("hi!", strArray25);
        java.lang.Object obj42 = org.mockito.Matchers.same((java.lang.Object) strArray25);
        org.junit.Assert.assertNotNull(map2);
        org.junit.Assert.assertNotNull(strArray5);
        org.junit.Assert.assertArrayEquals(strArray5, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map6);
        org.junit.Assert.assertNull(charSequence7);
        org.junit.Assert.assertNotNull(set8);
        org.junit.Assert.assertNull(set9);
        org.junit.Assert.assertNull(iterable10);
        org.junit.Assert.assertNotNull(list11);
        org.junit.Assert.assertNotNull(wildcardClass12);
        org.junit.Assert.assertNull(genericDeclaration13);
        org.junit.Assert.assertNotNull(map14);
        org.junit.Assert.assertNotNull(strArray17);
        org.junit.Assert.assertArrayEquals(strArray17, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map18);
        org.junit.Assert.assertNotNull(strArray25);
        org.junit.Assert.assertArrayEquals(strArray25, new java.lang.String[] { "hi!", "hi!", "hi!", "hi!", "hi!", "" });
        org.junit.Assert.assertNull(map26);
        org.junit.Assert.assertNull(annotatedElement27);
        org.junit.Assert.assertNull(collection28);
        org.junit.Assert.assertNotNull(set29);
        org.junit.Assert.assertNull(set30);
        org.junit.Assert.assertNull(set31);
        org.junit.Assert.assertNull(set32);
        org.junit.Assert.assertNotNull(strArray36);
        org.junit.Assert.assertArrayEquals(strArray36, new java.lang.String[] { "hi!", "", "" });
        org.junit.Assert.assertNull(iterable37);
        org.junit.Assert.assertNull(strArray38);
        org.junit.Assert.assertNull(obj39);
        org.junit.Assert.assertNull(strArray40);
        org.junit.Assert.assertNull(str41);
        org.junit.Assert.assertNull(obj42);
    }

    @Test
    public void test3003() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest6.test3003");
        java.util.Collection collection0 = null;
        org.mockito.Matchers matchers1 = new org.mockito.Matchers();
        org.mockito.Matchers matchers2 = org.mockito.Matchers.same(matchers1);
        java.util.Map map3 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray6 = new java.lang.String[] { "", "" };
        java.util.Map map7 = org.mockito.Matchers.refEq(map3, strArray6);
        java.lang.String[] strArray14 = new java.lang.String[] { "hi!", "hi!", "hi!", "hi!", "hi!", "" };
        java.util.Map map15 = org.mockito.Matchers.refEq(map3, strArray14);
        org.mockito.Matchers matchers16 = org.mockito.Matchers.refEq(matchers1, strArray14);
        org.mockito.Matchers matchers17 = org.mockito.Matchers.eq(matchers1);
        java.lang.Object obj18 = new java.lang.Object();
        java.lang.Class<?> wildcardClass19 = obj18.getClass();
        java.lang.reflect.Type type20 = org.mockito.Matchers.eq((java.lang.reflect.Type) wildcardClass19);
        java.lang.reflect.GenericDeclaration genericDeclaration21 = org.mockito.Matchers.eq((java.lang.reflect.GenericDeclaration) wildcardClass19);
        org.mockito.Matchers matchers22 = new org.mockito.Matchers();
        java.util.Map map24 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray27 = new java.lang.String[] { "", "" };
        java.util.Map map28 = org.mockito.Matchers.refEq(map24, strArray27);
        java.lang.String str29 = org.mockito.Matchers.refEq("hi!", strArray27);
        org.mockito.Matchers matchers30 = org.mockito.Matchers.refEq(matchers22, strArray27);
        java.lang.Class<?> wildcardClass31 = strArray27.getClass();
        org.mockito.Matchers matchers32 = new org.mockito.Matchers();
        org.mockito.Matchers matchers33 = org.mockito.Matchers.same(matchers32);
        java.util.Map map34 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray37 = new java.lang.String[] { "", "" };
        java.util.Map map38 = org.mockito.Matchers.refEq(map34, strArray37);
        java.lang.String[] strArray45 = new java.lang.String[] { "hi!", "hi!", "hi!", "hi!", "hi!", "" };
        java.util.Map map46 = org.mockito.Matchers.refEq(map34, strArray45);
        org.mockito.Matchers matchers47 = org.mockito.Matchers.refEq(matchers32, strArray45);
        java.lang.reflect.AnnotatedElement annotatedElement48 = org.mockito.Matchers.refEq((java.lang.reflect.AnnotatedElement) wildcardClass31, strArray45);
        java.lang.Class<?> wildcardClass49 = org.mockito.Matchers.refEq(wildcardClass19, strArray45);
        java.util.List list51 = org.mockito.Matchers.anyList();
        java.util.List list52 = org.mockito.Matchers.same(list51);
        java.util.List list53 = org.mockito.Matchers.eq(list51);
        java.util.List list54 = org.mockito.Matchers.eq(list51);
        java.util.Map map56 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray59 = new java.lang.String[] { "", "" };
        java.util.Map map60 = org.mockito.Matchers.refEq(map56, strArray59);
        java.lang.String str61 = org.mockito.Matchers.refEq("hi!", strArray59);
        java.lang.String[] strArray62 = null;
        java.util.Map map64 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray67 = new java.lang.String[] { "", "" };
        java.util.Map map68 = org.mockito.Matchers.refEq(map64, strArray67);
        java.lang.CharSequence charSequence69 = org.mockito.Matchers.refEq((java.lang.CharSequence) "", strArray67);
        java.lang.String[] strArray70 = org.mockito.Matchers.refEq(strArray62, strArray67);
        java.lang.String[] strArray71 = org.mockito.Matchers.refEq(strArray59, strArray67);
        java.util.List list72 = org.mockito.Matchers.refEq(list54, strArray59);
        java.lang.String str73 = org.mockito.Matchers.refEq("hi!", strArray59);
        java.lang.String[] strArray74 = org.mockito.Matchers.refEq(strArray45, strArray59);
        org.mockito.Matchers matchers75 = org.mockito.Matchers.refEq(matchers17, strArray45);
        java.lang.String[] strArray76 = org.mockito.Matchers.eq(strArray45);
        java.lang.String[] strArray84 = new java.lang.String[] { "hi!", "hi!", "hi!", "", "" };
        java.lang.CharSequence charSequence85 = org.mockito.Matchers.refEq((java.lang.CharSequence) "hi!", strArray84);
        java.lang.CharSequence charSequence86 = org.mockito.Matchers.refEq((java.lang.CharSequence) "hi!", strArray84);
        java.lang.String[] strArray87 = org.mockito.Matchers.refEq(strArray45, strArray84);
        java.lang.String[] strArray88 = org.mockito.Matchers.eq(strArray45);
        java.util.Collection collection89 = org.mockito.Matchers.refEq(collection0, strArray88);
        org.junit.Assert.assertNull(matchers2);
        org.junit.Assert.assertNotNull(map3);
        org.junit.Assert.assertNotNull(strArray6);
        org.junit.Assert.assertArrayEquals(strArray6, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map7);
        org.junit.Assert.assertNotNull(strArray14);
        org.junit.Assert.assertArrayEquals(strArray14, new java.lang.String[] { "hi!", "hi!", "hi!", "hi!", "hi!", "" });
        org.junit.Assert.assertNull(map15);
        org.junit.Assert.assertNull(matchers16);
        org.junit.Assert.assertNull(matchers17);
        org.junit.Assert.assertNotNull(wildcardClass19);
        org.junit.Assert.assertNull(type20);
        org.junit.Assert.assertNull(genericDeclaration21);
        org.junit.Assert.assertNotNull(map24);
        org.junit.Assert.assertNotNull(strArray27);
        org.junit.Assert.assertArrayEquals(strArray27, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map28);
        org.junit.Assert.assertNull(str29);
        org.junit.Assert.assertNull(matchers30);
        org.junit.Assert.assertNotNull(wildcardClass31);
        org.junit.Assert.assertNull(matchers33);
        org.junit.Assert.assertNotNull(map34);
        org.junit.Assert.assertNotNull(strArray37);
        org.junit.Assert.assertArrayEquals(strArray37, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map38);
        org.junit.Assert.assertNotNull(strArray45);
        org.junit.Assert.assertArrayEquals(strArray45, new java.lang.String[] { "hi!", "hi!", "hi!", "hi!", "hi!", "" });
        org.junit.Assert.assertNull(map46);
        org.junit.Assert.assertNull(matchers47);
        org.junit.Assert.assertNull(annotatedElement48);
        org.junit.Assert.assertNull(wildcardClass49);
        org.junit.Assert.assertNotNull(list51);
        org.junit.Assert.assertNull(list52);
        org.junit.Assert.assertNull(list53);
        org.junit.Assert.assertNull(list54);
        org.junit.Assert.assertNotNull(map56);
        org.junit.Assert.assertNotNull(strArray59);
        org.junit.Assert.assertArrayEquals(strArray59, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map60);
        org.junit.Assert.assertNull(str61);
        org.junit.Assert.assertNotNull(map64);
        org.junit.Assert.assertNotNull(strArray67);
        org.junit.Assert.assertArrayEquals(strArray67, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map68);
        org.junit.Assert.assertNull(charSequence69);
        org.junit.Assert.assertNull(strArray70);
        org.junit.Assert.assertNull(strArray71);
        org.junit.Assert.assertNull(list72);
        org.junit.Assert.assertNull(str73);
        org.junit.Assert.assertNull(strArray74);
        org.junit.Assert.assertNull(matchers75);
        org.junit.Assert.assertNull(strArray76);
        org.junit.Assert.assertNotNull(strArray84);
        org.junit.Assert.assertArrayEquals(strArray84, new java.lang.String[] { "hi!", "hi!", "hi!", "", "" });
        org.junit.Assert.assertNull(charSequence85);
        org.junit.Assert.assertNull(charSequence86);
        org.junit.Assert.assertNull(strArray87);
        org.junit.Assert.assertNull(strArray88);
        org.junit.Assert.assertNull(collection89);
    }

    @Test
    public void test3004() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest6.test3004");
        java.lang.String[] strArray4 = new java.lang.String[] { "", "hi!", "" };
        java.lang.String str5 = org.mockito.Matchers.refEq("hi!", strArray4);
        java.util.Set set7 = org.mockito.Matchers.anySet();
        java.util.Set set8 = org.mockito.Matchers.eq(set7);
        java.lang.Iterable iterable9 = org.mockito.Matchers.same((java.lang.Iterable) set7);
        java.util.List list10 = org.mockito.Matchers.anyList();
        java.lang.Class<?> wildcardClass11 = list10.getClass();
        java.lang.reflect.GenericDeclaration genericDeclaration12 = org.mockito.Matchers.same((java.lang.reflect.GenericDeclaration) wildcardClass11);
        java.lang.reflect.Type type13 = org.mockito.Matchers.same((java.lang.reflect.Type) wildcardClass11);
        java.lang.Object obj15 = new java.lang.Object();
        java.lang.Class<?> wildcardClass16 = obj15.getClass();
        java.util.Map map19 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray22 = new java.lang.String[] { "", "" };
        java.util.Map map23 = org.mockito.Matchers.refEq(map19, strArray22);
        java.lang.String str24 = org.mockito.Matchers.refEq("hi!", strArray22);
        java.lang.String[] strArray25 = null;
        java.util.Map map27 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray30 = new java.lang.String[] { "", "" };
        java.util.Map map31 = org.mockito.Matchers.refEq(map27, strArray30);
        java.lang.CharSequence charSequence32 = org.mockito.Matchers.refEq((java.lang.CharSequence) "", strArray30);
        java.lang.String[] strArray33 = org.mockito.Matchers.refEq(strArray25, strArray30);
        java.lang.String[] strArray34 = org.mockito.Matchers.refEq(strArray22, strArray30);
        java.lang.Object obj35 = org.mockito.Matchers.refEq((java.lang.Object) (short) 1, strArray22);
        java.io.Serializable serializable36 = org.mockito.Matchers.refEq((java.io.Serializable) wildcardClass16, strArray22);
        java.lang.String str37 = org.mockito.Matchers.refEq("", strArray22);
        java.lang.Class<?> wildcardClass38 = org.mockito.Matchers.refEq(wildcardClass11, strArray22);
        java.util.Set set39 = org.mockito.Matchers.refEq(set7, strArray22);
        java.util.List list41 = org.mockito.Matchers.anyList();
        java.lang.Class<?> wildcardClass42 = list41.getClass();
        java.lang.reflect.GenericDeclaration genericDeclaration43 = org.mockito.Matchers.same((java.lang.reflect.GenericDeclaration) wildcardClass42);
        java.lang.String[] strArray50 = new java.lang.String[] { "hi!", "", "", "", "", "hi!" };
        java.lang.String[] strArray51 = org.mockito.Matchers.same(strArray50);
        java.io.Serializable serializable52 = org.mockito.Matchers.refEq((java.io.Serializable) wildcardClass42, strArray50);
        java.lang.Object obj53 = org.mockito.Matchers.refEq((java.lang.Object) false, strArray50);
        java.util.Set set54 = org.mockito.Matchers.refEq(set7, strArray50);
        java.lang.Comparable<java.lang.String> strComparable55 = org.mockito.Matchers.refEq((java.lang.Comparable<java.lang.String>) "hi!", strArray50);
        java.lang.Object obj56 = org.mockito.Matchers.refEq((java.lang.Object) str5, strArray50);
        org.mockito.Matchers matchers58 = new org.mockito.Matchers();
        org.mockito.Matchers matchers59 = org.mockito.Matchers.eq(matchers58);
        java.util.Map map60 = org.mockito.Matchers.anyMap();
        java.lang.Class<?> wildcardClass61 = map60.getClass();
        java.util.List list62 = org.mockito.Matchers.anyList();
        java.lang.Class<?> wildcardClass63 = list62.getClass();
        java.lang.reflect.GenericDeclaration genericDeclaration64 = org.mockito.Matchers.same((java.lang.reflect.GenericDeclaration) wildcardClass63);
        java.util.Map map65 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray68 = new java.lang.String[] { "", "" };
        java.util.Map map69 = org.mockito.Matchers.refEq(map65, strArray68);
        java.lang.String[] strArray76 = new java.lang.String[] { "hi!", "hi!", "hi!", "hi!", "hi!", "" };
        java.util.Map map77 = org.mockito.Matchers.refEq(map65, strArray76);
        java.lang.reflect.AnnotatedElement annotatedElement78 = org.mockito.Matchers.refEq((java.lang.reflect.AnnotatedElement) wildcardClass63, strArray76);
        java.lang.reflect.GenericDeclaration genericDeclaration79 = org.mockito.Matchers.refEq((java.lang.reflect.GenericDeclaration) wildcardClass61, strArray76);
        org.mockito.Matchers matchers80 = org.mockito.Matchers.refEq(matchers59, strArray76);
        java.lang.Comparable<java.lang.String> strComparable81 = org.mockito.Matchers.refEq((java.lang.Comparable<java.lang.String>) "hi!", strArray76);
        java.lang.String[] strArray82 = org.mockito.Matchers.refEq(strArray50, strArray76);
        java.io.Serializable serializable83 = org.mockito.Matchers.eq((java.io.Serializable) strArray76);
        org.junit.Assert.assertNotNull(strArray4);
        org.junit.Assert.assertArrayEquals(strArray4, new java.lang.String[] { "", "hi!", "" });
        org.junit.Assert.assertNull(str5);
        org.junit.Assert.assertNotNull(set7);
        org.junit.Assert.assertNull(set8);
        org.junit.Assert.assertNull(iterable9);
        org.junit.Assert.assertNotNull(list10);
        org.junit.Assert.assertNotNull(wildcardClass11);
        org.junit.Assert.assertNull(genericDeclaration12);
        org.junit.Assert.assertNull(type13);
        org.junit.Assert.assertNotNull(wildcardClass16);
        org.junit.Assert.assertNotNull(map19);
        org.junit.Assert.assertNotNull(strArray22);
        org.junit.Assert.assertArrayEquals(strArray22, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map23);
        org.junit.Assert.assertNull(str24);
        org.junit.Assert.assertNotNull(map27);
        org.junit.Assert.assertNotNull(strArray30);
        org.junit.Assert.assertArrayEquals(strArray30, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map31);
        org.junit.Assert.assertNull(charSequence32);
        org.junit.Assert.assertNull(strArray33);
        org.junit.Assert.assertNull(strArray34);
        org.junit.Assert.assertNull(obj35);
        org.junit.Assert.assertNull(serializable36);
        org.junit.Assert.assertNull(str37);
        org.junit.Assert.assertNull(wildcardClass38);
        org.junit.Assert.assertNull(set39);
        org.junit.Assert.assertNotNull(list41);
        org.junit.Assert.assertNotNull(wildcardClass42);
        org.junit.Assert.assertNull(genericDeclaration43);
        org.junit.Assert.assertNotNull(strArray50);
        org.junit.Assert.assertArrayEquals(strArray50, new java.lang.String[] { "hi!", "", "", "", "", "hi!" });
        org.junit.Assert.assertNull(strArray51);
        org.junit.Assert.assertNull(serializable52);
        org.junit.Assert.assertNull(obj53);
        org.junit.Assert.assertNull(set54);
        org.junit.Assert.assertNull(strComparable55);
        org.junit.Assert.assertNull(obj56);
        org.junit.Assert.assertNull(matchers59);
        org.junit.Assert.assertNotNull(map60);
        org.junit.Assert.assertNotNull(wildcardClass61);
        org.junit.Assert.assertNotNull(list62);
        org.junit.Assert.assertNotNull(wildcardClass63);
        org.junit.Assert.assertNull(genericDeclaration64);
        org.junit.Assert.assertNotNull(map65);
        org.junit.Assert.assertNotNull(strArray68);
        org.junit.Assert.assertArrayEquals(strArray68, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map69);
        org.junit.Assert.assertNotNull(strArray76);
        org.junit.Assert.assertArrayEquals(strArray76, new java.lang.String[] { "hi!", "hi!", "hi!", "hi!", "hi!", "" });
        org.junit.Assert.assertNull(map77);
        org.junit.Assert.assertNull(annotatedElement78);
        org.junit.Assert.assertNull(genericDeclaration79);
        org.junit.Assert.assertNull(matchers80);
        org.junit.Assert.assertNull(strComparable81);
        org.junit.Assert.assertNull(strArray82);
        org.junit.Assert.assertNull(serializable83);
    }

    @Test
    public void test3005() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest6.test3005");
        java.util.Map map0 = org.mockito.Matchers.anyMap();
        java.util.Map map1 = org.mockito.Matchers.eq(map0);
        java.util.Map map2 = org.mockito.Matchers.anyMap();
        java.util.Map map4 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray7 = new java.lang.String[] { "", "" };
        java.util.Map map8 = org.mockito.Matchers.refEq(map4, strArray7);
        java.lang.String str9 = org.mockito.Matchers.refEq("hi!", strArray7);
        java.lang.String[] strArray10 = null;
        java.util.Map map12 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray15 = new java.lang.String[] { "", "" };
        java.util.Map map16 = org.mockito.Matchers.refEq(map12, strArray15);
        java.lang.CharSequence charSequence17 = org.mockito.Matchers.refEq((java.lang.CharSequence) "", strArray15);
        java.lang.String[] strArray18 = org.mockito.Matchers.refEq(strArray10, strArray15);
        java.lang.String[] strArray19 = org.mockito.Matchers.refEq(strArray7, strArray15);
        java.util.Map map20 = org.mockito.Matchers.refEq(map2, strArray7);
        java.lang.Object obj21 = new java.lang.Object();
        java.lang.Class<?> wildcardClass22 = obj21.getClass();
        java.util.Map map25 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray28 = new java.lang.String[] { "", "" };
        java.util.Map map29 = org.mockito.Matchers.refEq(map25, strArray28);
        java.lang.String str30 = org.mockito.Matchers.refEq("hi!", strArray28);
        java.lang.String[] strArray31 = null;
        java.util.Map map33 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray36 = new java.lang.String[] { "", "" };
        java.util.Map map37 = org.mockito.Matchers.refEq(map33, strArray36);
        java.lang.CharSequence charSequence38 = org.mockito.Matchers.refEq((java.lang.CharSequence) "", strArray36);
        java.lang.String[] strArray39 = org.mockito.Matchers.refEq(strArray31, strArray36);
        java.lang.String[] strArray40 = org.mockito.Matchers.refEq(strArray28, strArray36);
        java.lang.Object obj41 = org.mockito.Matchers.refEq((java.lang.Object) (short) 1, strArray28);
        java.io.Serializable serializable42 = org.mockito.Matchers.refEq((java.io.Serializable) wildcardClass22, strArray28);
        java.util.Map map43 = org.mockito.Matchers.refEq(map20, strArray28);
        java.util.Map map44 = org.mockito.Matchers.refEq(map0, strArray28);
        java.util.Map map45 = org.mockito.Matchers.eq(map0);
        java.util.Map map46 = org.mockito.Matchers.eq(map45);
        org.junit.Assert.assertNotNull(map0);
        org.junit.Assert.assertNull(map1);
        org.junit.Assert.assertNotNull(map2);
        org.junit.Assert.assertNotNull(map4);
        org.junit.Assert.assertNotNull(strArray7);
        org.junit.Assert.assertArrayEquals(strArray7, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map8);
        org.junit.Assert.assertNull(str9);
        org.junit.Assert.assertNotNull(map12);
        org.junit.Assert.assertNotNull(strArray15);
        org.junit.Assert.assertArrayEquals(strArray15, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map16);
        org.junit.Assert.assertNull(charSequence17);
        org.junit.Assert.assertNull(strArray18);
        org.junit.Assert.assertNull(strArray19);
        org.junit.Assert.assertNull(map20);
        org.junit.Assert.assertNotNull(wildcardClass22);
        org.junit.Assert.assertNotNull(map25);
        org.junit.Assert.assertNotNull(strArray28);
        org.junit.Assert.assertArrayEquals(strArray28, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map29);
        org.junit.Assert.assertNull(str30);
        org.junit.Assert.assertNotNull(map33);
        org.junit.Assert.assertNotNull(strArray36);
        org.junit.Assert.assertArrayEquals(strArray36, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map37);
        org.junit.Assert.assertNull(charSequence38);
        org.junit.Assert.assertNull(strArray39);
        org.junit.Assert.assertNull(strArray40);
        org.junit.Assert.assertNull(obj41);
        org.junit.Assert.assertNull(serializable42);
        org.junit.Assert.assertNull(map43);
        org.junit.Assert.assertNull(map44);
        org.junit.Assert.assertNull(map45);
        org.junit.Assert.assertNull(map46);
    }

    @Test
    public void test3006() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest6.test3006");
        java.util.Set set0 = org.mockito.Matchers.anySet();
        java.util.Set set1 = org.mockito.Matchers.eq(set0);
        java.util.Set set2 = org.mockito.Matchers.same(set0);
        java.util.Set set3 = org.mockito.Matchers.eq(set0);
        java.lang.String[] strArray7 = new java.lang.String[] { "hi!", "", "" };
        java.lang.Iterable iterable8 = org.mockito.Matchers.refEq((java.lang.Iterable) set0, strArray7);
        java.util.Collection collection9 = org.mockito.Matchers.same((java.util.Collection) set0);
        java.lang.Iterable iterable10 = org.mockito.Matchers.eq((java.lang.Iterable) set0);
        java.util.List list11 = org.mockito.Matchers.anyList();
        java.util.Collection collection12 = org.mockito.Matchers.eq((java.util.Collection) list11);
        java.lang.String[] strArray13 = null;
        java.util.List list14 = org.mockito.Matchers.refEq(list11, strArray13);
        java.util.List list16 = org.mockito.Matchers.anyList();
        java.lang.String[] strArray17 = null;
        java.util.Map map19 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray22 = new java.lang.String[] { "", "" };
        java.util.Map map23 = org.mockito.Matchers.refEq(map19, strArray22);
        java.lang.CharSequence charSequence24 = org.mockito.Matchers.refEq((java.lang.CharSequence) "", strArray22);
        java.lang.String[] strArray25 = org.mockito.Matchers.refEq(strArray17, strArray22);
        java.util.List list26 = org.mockito.Matchers.refEq(list16, strArray22);
        java.util.Set set27 = org.mockito.Matchers.anySet();
        java.util.Set set28 = org.mockito.Matchers.eq(set27);
        java.lang.Iterable iterable29 = org.mockito.Matchers.same((java.lang.Iterable) set27);
        java.util.List list30 = org.mockito.Matchers.anyList();
        java.lang.Class<?> wildcardClass31 = list30.getClass();
        java.lang.reflect.GenericDeclaration genericDeclaration32 = org.mockito.Matchers.same((java.lang.reflect.GenericDeclaration) wildcardClass31);
        java.lang.reflect.Type type33 = org.mockito.Matchers.same((java.lang.reflect.Type) wildcardClass31);
        java.lang.Object obj35 = new java.lang.Object();
        java.lang.Class<?> wildcardClass36 = obj35.getClass();
        java.util.Map map39 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray42 = new java.lang.String[] { "", "" };
        java.util.Map map43 = org.mockito.Matchers.refEq(map39, strArray42);
        java.lang.String str44 = org.mockito.Matchers.refEq("hi!", strArray42);
        java.lang.String[] strArray45 = null;
        java.util.Map map47 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray50 = new java.lang.String[] { "", "" };
        java.util.Map map51 = org.mockito.Matchers.refEq(map47, strArray50);
        java.lang.CharSequence charSequence52 = org.mockito.Matchers.refEq((java.lang.CharSequence) "", strArray50);
        java.lang.String[] strArray53 = org.mockito.Matchers.refEq(strArray45, strArray50);
        java.lang.String[] strArray54 = org.mockito.Matchers.refEq(strArray42, strArray50);
        java.lang.Object obj55 = org.mockito.Matchers.refEq((java.lang.Object) (short) 1, strArray42);
        java.io.Serializable serializable56 = org.mockito.Matchers.refEq((java.io.Serializable) wildcardClass36, strArray42);
        java.lang.String str57 = org.mockito.Matchers.refEq("", strArray42);
        java.lang.Class<?> wildcardClass58 = org.mockito.Matchers.refEq(wildcardClass31, strArray42);
        java.util.Set set59 = org.mockito.Matchers.refEq(set27, strArray42);
        java.util.Collection collection60 = org.mockito.Matchers.refEq((java.util.Collection) list16, strArray42);
        java.lang.Comparable<java.lang.String> strComparable61 = org.mockito.Matchers.refEq((java.lang.Comparable<java.lang.String>) "hi!", strArray42);
        java.util.List list62 = org.mockito.Matchers.refEq(list14, strArray42);
        java.util.Collection collection63 = org.mockito.Matchers.refEq((java.util.Collection) set0, strArray42);
        java.util.Set set64 = org.mockito.Matchers.eq(set0);
        java.lang.Class<?> wildcardClass65 = set0.getClass();
        org.junit.Assert.assertNotNull(set0);
        org.junit.Assert.assertNull(set1);
        org.junit.Assert.assertNull(set2);
        org.junit.Assert.assertNull(set3);
        org.junit.Assert.assertNotNull(strArray7);
        org.junit.Assert.assertArrayEquals(strArray7, new java.lang.String[] { "hi!", "", "" });
        org.junit.Assert.assertNull(iterable8);
        org.junit.Assert.assertNull(collection9);
        org.junit.Assert.assertNull(iterable10);
        org.junit.Assert.assertNotNull(list11);
        org.junit.Assert.assertNull(collection12);
        org.junit.Assert.assertNull(list14);
        org.junit.Assert.assertNotNull(list16);
        org.junit.Assert.assertNotNull(map19);
        org.junit.Assert.assertNotNull(strArray22);
        org.junit.Assert.assertArrayEquals(strArray22, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map23);
        org.junit.Assert.assertNull(charSequence24);
        org.junit.Assert.assertNull(strArray25);
        org.junit.Assert.assertNull(list26);
        org.junit.Assert.assertNotNull(set27);
        org.junit.Assert.assertNull(set28);
        org.junit.Assert.assertNull(iterable29);
        org.junit.Assert.assertNotNull(list30);
        org.junit.Assert.assertNotNull(wildcardClass31);
        org.junit.Assert.assertNull(genericDeclaration32);
        org.junit.Assert.assertNull(type33);
        org.junit.Assert.assertNotNull(wildcardClass36);
        org.junit.Assert.assertNotNull(map39);
        org.junit.Assert.assertNotNull(strArray42);
        org.junit.Assert.assertArrayEquals(strArray42, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map43);
        org.junit.Assert.assertNull(str44);
        org.junit.Assert.assertNotNull(map47);
        org.junit.Assert.assertNotNull(strArray50);
        org.junit.Assert.assertArrayEquals(strArray50, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map51);
        org.junit.Assert.assertNull(charSequence52);
        org.junit.Assert.assertNull(strArray53);
        org.junit.Assert.assertNull(strArray54);
        org.junit.Assert.assertNull(obj55);
        org.junit.Assert.assertNull(serializable56);
        org.junit.Assert.assertNull(str57);
        org.junit.Assert.assertNull(wildcardClass58);
        org.junit.Assert.assertNull(set59);
        org.junit.Assert.assertNull(collection60);
        org.junit.Assert.assertNull(strComparable61);
        org.junit.Assert.assertNull(list62);
        org.junit.Assert.assertNull(collection63);
        org.junit.Assert.assertNull(set64);
        org.junit.Assert.assertNotNull(wildcardClass65);
    }

    @Test
    public void test3007() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest6.test3007");
        java.util.List list0 = org.mockito.Matchers.anyList();
        java.lang.Class<?> wildcardClass1 = list0.getClass();
        java.lang.reflect.GenericDeclaration genericDeclaration2 = org.mockito.Matchers.same((java.lang.reflect.GenericDeclaration) wildcardClass1);
        java.lang.reflect.Type type3 = org.mockito.Matchers.same((java.lang.reflect.Type) wildcardClass1);
        java.lang.Class<?> wildcardClass4 = org.mockito.Matchers.eq(wildcardClass1);
        java.lang.reflect.GenericDeclaration genericDeclaration5 = org.mockito.Matchers.same((java.lang.reflect.GenericDeclaration) wildcardClass1);
        java.util.List list6 = org.mockito.Matchers.anyList();
        java.util.Collection collection7 = org.mockito.Matchers.eq((java.util.Collection) list6);
        java.lang.Class<?> wildcardClass8 = list6.getClass();
        java.util.List list9 = org.mockito.Matchers.anyList();
        java.lang.Class<?> wildcardClass10 = list9.getClass();
        java.lang.reflect.GenericDeclaration genericDeclaration11 = org.mockito.Matchers.same((java.lang.reflect.GenericDeclaration) wildcardClass10);
        java.lang.String[] strArray18 = new java.lang.String[] { "hi!", "", "", "", "", "hi!" };
        java.lang.String[] strArray19 = org.mockito.Matchers.same(strArray18);
        java.io.Serializable serializable20 = org.mockito.Matchers.refEq((java.io.Serializable) wildcardClass10, strArray18);
        java.lang.Class<?> wildcardClass21 = org.mockito.Matchers.refEq(wildcardClass8, strArray18);
        java.lang.Class<?> wildcardClass22 = strArray18.getClass();
        java.util.List list23 = org.mockito.Matchers.anyList();
        java.util.Collection collection24 = org.mockito.Matchers.eq((java.util.Collection) list23);
        java.lang.Iterable iterable25 = org.mockito.Matchers.same((java.lang.Iterable) list23);
        java.util.Map map26 = org.mockito.Matchers.anyMap();
        java.lang.Class<?> wildcardClass27 = map26.getClass();
        java.util.List list28 = org.mockito.Matchers.anyList();
        java.lang.Class<?> wildcardClass29 = list28.getClass();
        java.lang.reflect.GenericDeclaration genericDeclaration30 = org.mockito.Matchers.same((java.lang.reflect.GenericDeclaration) wildcardClass29);
        java.util.Map map31 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray34 = new java.lang.String[] { "", "" };
        java.util.Map map35 = org.mockito.Matchers.refEq(map31, strArray34);
        java.lang.String[] strArray42 = new java.lang.String[] { "hi!", "hi!", "hi!", "hi!", "hi!", "" };
        java.util.Map map43 = org.mockito.Matchers.refEq(map31, strArray42);
        java.lang.reflect.AnnotatedElement annotatedElement44 = org.mockito.Matchers.refEq((java.lang.reflect.AnnotatedElement) wildcardClass29, strArray42);
        java.lang.reflect.GenericDeclaration genericDeclaration45 = org.mockito.Matchers.refEq((java.lang.reflect.GenericDeclaration) wildcardClass27, strArray42);
        java.lang.String[] strArray46 = org.mockito.Matchers.eq(strArray42);
        java.util.List list47 = org.mockito.Matchers.refEq(list23, strArray46);
        java.util.Map map48 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray51 = new java.lang.String[] { "", "" };
        java.util.Map map52 = org.mockito.Matchers.refEq(map48, strArray51);
        java.lang.String[] strArray59 = new java.lang.String[] { "hi!", "hi!", "hi!", "hi!", "hi!", "" };
        java.util.Map map60 = org.mockito.Matchers.refEq(map48, strArray59);
        java.util.Collection collection61 = org.mockito.Matchers.refEq((java.util.Collection) list47, strArray59);
        java.lang.Object obj62 = org.mockito.Matchers.refEq((java.lang.Object) wildcardClass22, strArray59);
        java.util.Collection collection63 = org.mockito.Matchers.anyCollection();
        java.lang.Iterable iterable64 = org.mockito.Matchers.eq((java.lang.Iterable) collection63);
        java.util.List list65 = org.mockito.Matchers.anyList();
        java.util.Collection collection66 = org.mockito.Matchers.eq((java.util.Collection) list65);
        java.lang.Class<?> wildcardClass67 = list65.getClass();
        java.lang.Class<?> wildcardClass68 = org.mockito.Matchers.same(wildcardClass67);
        java.lang.reflect.GenericDeclaration genericDeclaration69 = org.mockito.Matchers.eq((java.lang.reflect.GenericDeclaration) wildcardClass67);
        java.util.Set set70 = org.mockito.Matchers.anySet();
        java.util.Set set71 = org.mockito.Matchers.eq(set70);
        java.lang.Iterable iterable72 = org.mockito.Matchers.same((java.lang.Iterable) set70);
        java.util.List list73 = org.mockito.Matchers.anyList();
        java.lang.Class<?> wildcardClass74 = list73.getClass();
        java.lang.reflect.GenericDeclaration genericDeclaration75 = org.mockito.Matchers.same((java.lang.reflect.GenericDeclaration) wildcardClass74);
        java.util.Map map76 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray79 = new java.lang.String[] { "", "" };
        java.util.Map map80 = org.mockito.Matchers.refEq(map76, strArray79);
        java.lang.String[] strArray87 = new java.lang.String[] { "hi!", "hi!", "hi!", "hi!", "hi!", "" };
        java.util.Map map88 = org.mockito.Matchers.refEq(map76, strArray87);
        java.lang.reflect.AnnotatedElement annotatedElement89 = org.mockito.Matchers.refEq((java.lang.reflect.AnnotatedElement) wildcardClass74, strArray87);
        java.util.Collection collection90 = org.mockito.Matchers.refEq((java.util.Collection) set70, strArray87);
        java.io.Serializable serializable91 = org.mockito.Matchers.same((java.io.Serializable) strArray87);
        java.lang.Class<?> wildcardClass92 = org.mockito.Matchers.refEq(wildcardClass67, strArray87);
        java.util.Collection collection93 = org.mockito.Matchers.refEq(collection63, strArray87);
        java.io.Serializable serializable94 = org.mockito.Matchers.refEq((java.io.Serializable) strArray59, strArray87);
        java.lang.reflect.GenericDeclaration genericDeclaration95 = org.mockito.Matchers.refEq((java.lang.reflect.GenericDeclaration) wildcardClass1, strArray59);
        org.junit.Assert.assertNotNull(list0);
        org.junit.Assert.assertNotNull(wildcardClass1);
        org.junit.Assert.assertNull(genericDeclaration2);
        org.junit.Assert.assertNull(type3);
        org.junit.Assert.assertNull(wildcardClass4);
        org.junit.Assert.assertNull(genericDeclaration5);
        org.junit.Assert.assertNotNull(list6);
        org.junit.Assert.assertNull(collection7);
        org.junit.Assert.assertNotNull(wildcardClass8);
        org.junit.Assert.assertNotNull(list9);
        org.junit.Assert.assertNotNull(wildcardClass10);
        org.junit.Assert.assertNull(genericDeclaration11);
        org.junit.Assert.assertNotNull(strArray18);
        org.junit.Assert.assertArrayEquals(strArray18, new java.lang.String[] { "hi!", "", "", "", "", "hi!" });
        org.junit.Assert.assertNull(strArray19);
        org.junit.Assert.assertNull(serializable20);
        org.junit.Assert.assertNull(wildcardClass21);
        org.junit.Assert.assertNotNull(wildcardClass22);
        org.junit.Assert.assertNotNull(list23);
        org.junit.Assert.assertNull(collection24);
        org.junit.Assert.assertNull(iterable25);
        org.junit.Assert.assertNotNull(map26);
        org.junit.Assert.assertNotNull(wildcardClass27);
        org.junit.Assert.assertNotNull(list28);
        org.junit.Assert.assertNotNull(wildcardClass29);
        org.junit.Assert.assertNull(genericDeclaration30);
        org.junit.Assert.assertNotNull(map31);
        org.junit.Assert.assertNotNull(strArray34);
        org.junit.Assert.assertArrayEquals(strArray34, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map35);
        org.junit.Assert.assertNotNull(strArray42);
        org.junit.Assert.assertArrayEquals(strArray42, new java.lang.String[] { "hi!", "hi!", "hi!", "hi!", "hi!", "" });
        org.junit.Assert.assertNull(map43);
        org.junit.Assert.assertNull(annotatedElement44);
        org.junit.Assert.assertNull(genericDeclaration45);
        org.junit.Assert.assertNull(strArray46);
        org.junit.Assert.assertNull(list47);
        org.junit.Assert.assertNotNull(map48);
        org.junit.Assert.assertNotNull(strArray51);
        org.junit.Assert.assertArrayEquals(strArray51, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map52);
        org.junit.Assert.assertNotNull(strArray59);
        org.junit.Assert.assertArrayEquals(strArray59, new java.lang.String[] { "hi!", "hi!", "hi!", "hi!", "hi!", "" });
        org.junit.Assert.assertNull(map60);
        org.junit.Assert.assertNull(collection61);
        org.junit.Assert.assertNull(obj62);
        org.junit.Assert.assertNotNull(collection63);
        org.junit.Assert.assertNull(iterable64);
        org.junit.Assert.assertNotNull(list65);
        org.junit.Assert.assertNull(collection66);
        org.junit.Assert.assertNotNull(wildcardClass67);
        org.junit.Assert.assertNull(wildcardClass68);
        org.junit.Assert.assertNull(genericDeclaration69);
        org.junit.Assert.assertNotNull(set70);
        org.junit.Assert.assertNull(set71);
        org.junit.Assert.assertNull(iterable72);
        org.junit.Assert.assertNotNull(list73);
        org.junit.Assert.assertNotNull(wildcardClass74);
        org.junit.Assert.assertNull(genericDeclaration75);
        org.junit.Assert.assertNotNull(map76);
        org.junit.Assert.assertNotNull(strArray79);
        org.junit.Assert.assertArrayEquals(strArray79, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map80);
        org.junit.Assert.assertNotNull(strArray87);
        org.junit.Assert.assertArrayEquals(strArray87, new java.lang.String[] { "hi!", "hi!", "hi!", "hi!", "hi!", "" });
        org.junit.Assert.assertNull(map88);
        org.junit.Assert.assertNull(annotatedElement89);
        org.junit.Assert.assertNull(collection90);
        org.junit.Assert.assertNull(serializable91);
        org.junit.Assert.assertNull(wildcardClass92);
        org.junit.Assert.assertNull(collection93);
        org.junit.Assert.assertNull(serializable94);
        org.junit.Assert.assertNull(genericDeclaration95);
    }

    @Test
    public void test3008() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest6.test3008");
        java.util.List list0 = org.mockito.Matchers.anyList();
        java.util.List list1 = org.mockito.Matchers.same(list0);
        java.util.List list2 = org.mockito.Matchers.eq(list0);
        java.util.List list3 = org.mockito.Matchers.eq(list0);
        java.lang.Iterable iterable4 = org.mockito.Matchers.eq((java.lang.Iterable) list0);
        java.lang.Iterable iterable5 = org.mockito.Matchers.same((java.lang.Iterable) list0);
        java.util.List list6 = org.mockito.Matchers.same(list0);
        java.util.List list7 = org.mockito.Matchers.eq(list6);
        org.junit.Assert.assertNotNull(list0);
        org.junit.Assert.assertNull(list1);
        org.junit.Assert.assertNull(list2);
        org.junit.Assert.assertNull(list3);
        org.junit.Assert.assertNull(iterable4);
        org.junit.Assert.assertNull(iterable5);
        org.junit.Assert.assertNull(list6);
        org.junit.Assert.assertNull(list7);
    }

    @Test
    public void test3009() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest6.test3009");
        java.util.Set set0 = org.mockito.Matchers.anySet();
        java.util.Set set1 = org.mockito.Matchers.eq(set0);
        java.util.Set set2 = org.mockito.Matchers.same(set0);
        java.util.Set set3 = org.mockito.Matchers.eq(set0);
        java.lang.String[] strArray7 = new java.lang.String[] { "hi!", "", "" };
        java.lang.Iterable iterable8 = org.mockito.Matchers.refEq((java.lang.Iterable) set0, strArray7);
        java.lang.String[] strArray9 = org.mockito.Matchers.same(strArray7);
        java.lang.Class<?> wildcardClass10 = strArray7.getClass();
        java.lang.reflect.GenericDeclaration genericDeclaration11 = org.mockito.Matchers.eq((java.lang.reflect.GenericDeclaration) wildcardClass10);
        org.junit.Assert.assertNotNull(set0);
        org.junit.Assert.assertNull(set1);
        org.junit.Assert.assertNull(set2);
        org.junit.Assert.assertNull(set3);
        org.junit.Assert.assertNotNull(strArray7);
        org.junit.Assert.assertArrayEquals(strArray7, new java.lang.String[] { "hi!", "", "" });
        org.junit.Assert.assertNull(iterable8);
        org.junit.Assert.assertNull(strArray9);
        org.junit.Assert.assertNotNull(wildcardClass10);
        org.junit.Assert.assertNull(genericDeclaration11);
    }

    @Test
    public void test3010() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest6.test3010");
        java.util.List list0 = org.mockito.Matchers.anyList();
        java.util.List list1 = org.mockito.Matchers.same(list0);
        java.util.List list2 = org.mockito.Matchers.eq(list0);
        java.util.List list3 = org.mockito.Matchers.eq(list0);
        java.lang.String[] strArray4 = null;
        java.lang.Iterable iterable5 = org.mockito.Matchers.refEq((java.lang.Iterable) list0, strArray4);
        org.junit.Assert.assertNotNull(list0);
        org.junit.Assert.assertNull(list1);
        org.junit.Assert.assertNull(list2);
        org.junit.Assert.assertNull(list3);
        org.junit.Assert.assertNull(iterable5);
    }

    @Test
    public void test3011() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest6.test3011");
        java.util.Set set0 = org.mockito.Matchers.anySet();
        java.util.Set set1 = org.mockito.Matchers.same(set0);
        java.lang.Object obj2 = org.mockito.Matchers.eq((java.lang.Object) set0);
        java.lang.Iterable iterable3 = org.mockito.Matchers.same((java.lang.Iterable) set0);
        java.util.Collection collection4 = org.mockito.Matchers.eq((java.util.Collection) set0);
        org.junit.Assert.assertNotNull(set0);
        org.junit.Assert.assertNull(set1);
        org.junit.Assert.assertNull(obj2);
        org.junit.Assert.assertNull(iterable3);
        org.junit.Assert.assertNull(collection4);
    }

    @Test
    public void test3012() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest6.test3012");
        org.mockito.Matchers matchers1 = new org.mockito.Matchers();
        java.lang.Class<?> wildcardClass2 = matchers1.getClass();
        java.lang.Object obj3 = org.mockito.Matchers.eq((java.lang.Object) wildcardClass2);
        java.lang.reflect.Type type4 = org.mockito.Matchers.same((java.lang.reflect.Type) wildcardClass2);
        java.lang.Class<?> wildcardClass5 = org.mockito.Matchers.eq(wildcardClass2);
        java.util.Map map7 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray10 = new java.lang.String[] { "", "" };
        java.util.Map map11 = org.mockito.Matchers.refEq(map7, strArray10);
        java.lang.String str12 = org.mockito.Matchers.refEq("hi!", strArray10);
        java.lang.String[] strArray13 = null;
        java.util.Map map15 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray18 = new java.lang.String[] { "", "" };
        java.util.Map map19 = org.mockito.Matchers.refEq(map15, strArray18);
        java.lang.CharSequence charSequence20 = org.mockito.Matchers.refEq((java.lang.CharSequence) "", strArray18);
        java.lang.String[] strArray21 = org.mockito.Matchers.refEq(strArray13, strArray18);
        java.lang.String[] strArray22 = org.mockito.Matchers.refEq(strArray10, strArray18);
        java.lang.Class<?> wildcardClass23 = strArray18.getClass();
        java.util.Map map24 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray27 = new java.lang.String[] { "", "" };
        java.util.Map map28 = org.mockito.Matchers.refEq(map24, strArray27);
        java.lang.String[] strArray35 = new java.lang.String[] { "hi!", "hi!", "hi!", "hi!", "hi!", "" };
        java.util.Map map36 = org.mockito.Matchers.refEq(map24, strArray35);
        java.lang.reflect.GenericDeclaration genericDeclaration37 = org.mockito.Matchers.refEq((java.lang.reflect.GenericDeclaration) wildcardClass23, strArray35);
        java.util.Set set38 = org.mockito.Matchers.anySet();
        java.util.Set set39 = org.mockito.Matchers.eq(set38);
        java.util.Set set40 = org.mockito.Matchers.same(set38);
        java.util.Set set41 = org.mockito.Matchers.eq(set38);
        java.lang.String[] strArray45 = new java.lang.String[] { "hi!", "", "" };
        java.lang.Iterable iterable46 = org.mockito.Matchers.refEq((java.lang.Iterable) set38, strArray45);
        java.lang.Class<?> wildcardClass47 = org.mockito.Matchers.refEq(wildcardClass23, strArray45);
        java.lang.Class<?> wildcardClass48 = org.mockito.Matchers.refEq(wildcardClass2, strArray45);
        org.mockito.Matchers matchers49 = new org.mockito.Matchers();
        org.mockito.Matchers matchers50 = org.mockito.Matchers.eq(matchers49);
        java.util.Map map51 = org.mockito.Matchers.anyMap();
        java.lang.Class<?> wildcardClass52 = map51.getClass();
        java.util.List list53 = org.mockito.Matchers.anyList();
        java.lang.Class<?> wildcardClass54 = list53.getClass();
        java.lang.reflect.GenericDeclaration genericDeclaration55 = org.mockito.Matchers.same((java.lang.reflect.GenericDeclaration) wildcardClass54);
        java.util.Map map56 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray59 = new java.lang.String[] { "", "" };
        java.util.Map map60 = org.mockito.Matchers.refEq(map56, strArray59);
        java.lang.String[] strArray67 = new java.lang.String[] { "hi!", "hi!", "hi!", "hi!", "hi!", "" };
        java.util.Map map68 = org.mockito.Matchers.refEq(map56, strArray67);
        java.lang.reflect.AnnotatedElement annotatedElement69 = org.mockito.Matchers.refEq((java.lang.reflect.AnnotatedElement) wildcardClass54, strArray67);
        java.lang.reflect.GenericDeclaration genericDeclaration70 = org.mockito.Matchers.refEq((java.lang.reflect.GenericDeclaration) wildcardClass52, strArray67);
        org.mockito.Matchers matchers71 = org.mockito.Matchers.refEq(matchers50, strArray67);
        java.lang.Object obj72 = org.mockito.Matchers.refEq((java.lang.Object) wildcardClass48, strArray67);
        java.lang.String str73 = org.mockito.Matchers.refEq("", strArray67);
        org.junit.Assert.assertNotNull(wildcardClass2);
        org.junit.Assert.assertNull(obj3);
        org.junit.Assert.assertNull(type4);
        org.junit.Assert.assertNull(wildcardClass5);
        org.junit.Assert.assertNotNull(map7);
        org.junit.Assert.assertNotNull(strArray10);
        org.junit.Assert.assertArrayEquals(strArray10, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map11);
        org.junit.Assert.assertNull(str12);
        org.junit.Assert.assertNotNull(map15);
        org.junit.Assert.assertNotNull(strArray18);
        org.junit.Assert.assertArrayEquals(strArray18, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map19);
        org.junit.Assert.assertNull(charSequence20);
        org.junit.Assert.assertNull(strArray21);
        org.junit.Assert.assertNull(strArray22);
        org.junit.Assert.assertNotNull(wildcardClass23);
        org.junit.Assert.assertNotNull(map24);
        org.junit.Assert.assertNotNull(strArray27);
        org.junit.Assert.assertArrayEquals(strArray27, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map28);
        org.junit.Assert.assertNotNull(strArray35);
        org.junit.Assert.assertArrayEquals(strArray35, new java.lang.String[] { "hi!", "hi!", "hi!", "hi!", "hi!", "" });
        org.junit.Assert.assertNull(map36);
        org.junit.Assert.assertNull(genericDeclaration37);
        org.junit.Assert.assertNotNull(set38);
        org.junit.Assert.assertNull(set39);
        org.junit.Assert.assertNull(set40);
        org.junit.Assert.assertNull(set41);
        org.junit.Assert.assertNotNull(strArray45);
        org.junit.Assert.assertArrayEquals(strArray45, new java.lang.String[] { "hi!", "", "" });
        org.junit.Assert.assertNull(iterable46);
        org.junit.Assert.assertNull(wildcardClass47);
        org.junit.Assert.assertNull(wildcardClass48);
        org.junit.Assert.assertNull(matchers50);
        org.junit.Assert.assertNotNull(map51);
        org.junit.Assert.assertNotNull(wildcardClass52);
        org.junit.Assert.assertNotNull(list53);
        org.junit.Assert.assertNotNull(wildcardClass54);
        org.junit.Assert.assertNull(genericDeclaration55);
        org.junit.Assert.assertNotNull(map56);
        org.junit.Assert.assertNotNull(strArray59);
        org.junit.Assert.assertArrayEquals(strArray59, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map60);
        org.junit.Assert.assertNotNull(strArray67);
        org.junit.Assert.assertArrayEquals(strArray67, new java.lang.String[] { "hi!", "hi!", "hi!", "hi!", "hi!", "" });
        org.junit.Assert.assertNull(map68);
        org.junit.Assert.assertNull(annotatedElement69);
        org.junit.Assert.assertNull(genericDeclaration70);
        org.junit.Assert.assertNull(matchers71);
        org.junit.Assert.assertNull(obj72);
        org.junit.Assert.assertNull(str73);
    }

    @Test
    public void test3013() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest6.test3013");
        java.lang.reflect.AnnotatedElement annotatedElement1 = null;
        org.mockito.Matchers matchers2 = new org.mockito.Matchers();
        org.mockito.Matchers matchers3 = org.mockito.Matchers.same(matchers2);
        java.util.Map map4 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray7 = new java.lang.String[] { "", "" };
        java.util.Map map8 = org.mockito.Matchers.refEq(map4, strArray7);
        java.lang.String[] strArray15 = new java.lang.String[] { "hi!", "hi!", "hi!", "hi!", "hi!", "" };
        java.util.Map map16 = org.mockito.Matchers.refEq(map4, strArray15);
        org.mockito.Matchers matchers17 = org.mockito.Matchers.refEq(matchers2, strArray15);
        org.mockito.Matchers matchers18 = org.mockito.Matchers.eq(matchers2);
        java.lang.String[] strArray23 = new java.lang.String[] { "", "hi!", "" };
        java.lang.String str24 = org.mockito.Matchers.refEq("hi!", strArray23);
        java.util.List list25 = org.mockito.Matchers.anyList();
        java.lang.Iterable iterable26 = org.mockito.Matchers.eq((java.lang.Iterable) list25);
        java.util.List list27 = org.mockito.Matchers.anyList();
        java.lang.Class<?> wildcardClass28 = list27.getClass();
        java.lang.reflect.GenericDeclaration genericDeclaration29 = org.mockito.Matchers.same((java.lang.reflect.GenericDeclaration) wildcardClass28);
        java.lang.reflect.Type type30 = org.mockito.Matchers.same((java.lang.reflect.Type) wildcardClass28);
        java.lang.Object obj32 = new java.lang.Object();
        java.lang.Class<?> wildcardClass33 = obj32.getClass();
        java.util.Map map36 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray39 = new java.lang.String[] { "", "" };
        java.util.Map map40 = org.mockito.Matchers.refEq(map36, strArray39);
        java.lang.String str41 = org.mockito.Matchers.refEq("hi!", strArray39);
        java.lang.String[] strArray42 = null;
        java.util.Map map44 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray47 = new java.lang.String[] { "", "" };
        java.util.Map map48 = org.mockito.Matchers.refEq(map44, strArray47);
        java.lang.CharSequence charSequence49 = org.mockito.Matchers.refEq((java.lang.CharSequence) "", strArray47);
        java.lang.String[] strArray50 = org.mockito.Matchers.refEq(strArray42, strArray47);
        java.lang.String[] strArray51 = org.mockito.Matchers.refEq(strArray39, strArray47);
        java.lang.Object obj52 = org.mockito.Matchers.refEq((java.lang.Object) (short) 1, strArray39);
        java.io.Serializable serializable53 = org.mockito.Matchers.refEq((java.io.Serializable) wildcardClass33, strArray39);
        java.lang.String str54 = org.mockito.Matchers.refEq("", strArray39);
        java.lang.Class<?> wildcardClass55 = org.mockito.Matchers.refEq(wildcardClass28, strArray39);
        java.lang.Iterable iterable56 = org.mockito.Matchers.refEq(iterable26, strArray39);
        java.lang.String[] strArray57 = org.mockito.Matchers.eq(strArray39);
        java.lang.String[] strArray58 = org.mockito.Matchers.refEq(strArray23, strArray39);
        org.mockito.Matchers matchers59 = org.mockito.Matchers.refEq(matchers2, strArray23);
        java.lang.reflect.AnnotatedElement annotatedElement60 = org.mockito.Matchers.refEq(annotatedElement1, strArray23);
        java.lang.String str61 = org.mockito.Matchers.refEq("", strArray23);
        java.lang.Class<?> wildcardClass62 = strArray23.getClass();
        org.junit.Assert.assertNull(matchers3);
        org.junit.Assert.assertNotNull(map4);
        org.junit.Assert.assertNotNull(strArray7);
        org.junit.Assert.assertArrayEquals(strArray7, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map8);
        org.junit.Assert.assertNotNull(strArray15);
        org.junit.Assert.assertArrayEquals(strArray15, new java.lang.String[] { "hi!", "hi!", "hi!", "hi!", "hi!", "" });
        org.junit.Assert.assertNull(map16);
        org.junit.Assert.assertNull(matchers17);
        org.junit.Assert.assertNull(matchers18);
        org.junit.Assert.assertNotNull(strArray23);
        org.junit.Assert.assertArrayEquals(strArray23, new java.lang.String[] { "", "hi!", "" });
        org.junit.Assert.assertNull(str24);
        org.junit.Assert.assertNotNull(list25);
        org.junit.Assert.assertNull(iterable26);
        org.junit.Assert.assertNotNull(list27);
        org.junit.Assert.assertNotNull(wildcardClass28);
        org.junit.Assert.assertNull(genericDeclaration29);
        org.junit.Assert.assertNull(type30);
        org.junit.Assert.assertNotNull(wildcardClass33);
        org.junit.Assert.assertNotNull(map36);
        org.junit.Assert.assertNotNull(strArray39);
        org.junit.Assert.assertArrayEquals(strArray39, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map40);
        org.junit.Assert.assertNull(str41);
        org.junit.Assert.assertNotNull(map44);
        org.junit.Assert.assertNotNull(strArray47);
        org.junit.Assert.assertArrayEquals(strArray47, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map48);
        org.junit.Assert.assertNull(charSequence49);
        org.junit.Assert.assertNull(strArray50);
        org.junit.Assert.assertNull(strArray51);
        org.junit.Assert.assertNull(obj52);
        org.junit.Assert.assertNull(serializable53);
        org.junit.Assert.assertNull(str54);
        org.junit.Assert.assertNull(wildcardClass55);
        org.junit.Assert.assertNull(iterable56);
        org.junit.Assert.assertNull(strArray57);
        org.junit.Assert.assertNull(strArray58);
        org.junit.Assert.assertNull(matchers59);
        org.junit.Assert.assertNull(annotatedElement60);
        org.junit.Assert.assertNull(str61);
        org.junit.Assert.assertNotNull(wildcardClass62);
    }

    @Test
    public void test3014() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest6.test3014");
        java.util.List list0 = org.mockito.Matchers.anyList();
        java.lang.Iterable iterable1 = org.mockito.Matchers.eq((java.lang.Iterable) list0);
        java.util.List list2 = org.mockito.Matchers.eq(list0);
        java.util.List list3 = org.mockito.Matchers.same(list0);
        java.util.List list4 = org.mockito.Matchers.anyList();
        java.lang.Class<?> wildcardClass5 = list4.getClass();
        java.lang.reflect.GenericDeclaration genericDeclaration6 = org.mockito.Matchers.same((java.lang.reflect.GenericDeclaration) wildcardClass5);
        org.mockito.Matchers matchers7 = new org.mockito.Matchers();
        java.util.Map map9 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray12 = new java.lang.String[] { "", "" };
        java.util.Map map13 = org.mockito.Matchers.refEq(map9, strArray12);
        java.lang.String str14 = org.mockito.Matchers.refEq("hi!", strArray12);
        org.mockito.Matchers matchers15 = org.mockito.Matchers.refEq(matchers7, strArray12);
        java.lang.reflect.GenericDeclaration genericDeclaration16 = org.mockito.Matchers.refEq(genericDeclaration6, strArray12);
        java.util.Map map18 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray21 = new java.lang.String[] { "", "" };
        java.util.Map map22 = org.mockito.Matchers.refEq(map18, strArray21);
        java.lang.CharSequence charSequence23 = org.mockito.Matchers.refEq((java.lang.CharSequence) "", strArray21);
        java.io.Serializable serializable24 = org.mockito.Matchers.refEq((java.io.Serializable) strArray12, strArray21);
        java.util.List list25 = org.mockito.Matchers.refEq(list0, strArray21);
        java.lang.Iterable iterable26 = org.mockito.Matchers.eq((java.lang.Iterable) list0);
        java.util.List list27 = org.mockito.Matchers.anyList();
        java.lang.Iterable iterable28 = org.mockito.Matchers.eq((java.lang.Iterable) list27);
        java.util.List list29 = org.mockito.Matchers.anyList();
        java.lang.Class<?> wildcardClass30 = list29.getClass();
        java.lang.reflect.GenericDeclaration genericDeclaration31 = org.mockito.Matchers.same((java.lang.reflect.GenericDeclaration) wildcardClass30);
        java.lang.reflect.Type type32 = org.mockito.Matchers.same((java.lang.reflect.Type) wildcardClass30);
        java.lang.Object obj34 = new java.lang.Object();
        java.lang.Class<?> wildcardClass35 = obj34.getClass();
        java.util.Map map38 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray41 = new java.lang.String[] { "", "" };
        java.util.Map map42 = org.mockito.Matchers.refEq(map38, strArray41);
        java.lang.String str43 = org.mockito.Matchers.refEq("hi!", strArray41);
        java.lang.String[] strArray44 = null;
        java.util.Map map46 = org.mockito.Matchers.anyMap();
        java.lang.String[] strArray49 = new java.lang.String[] { "", "" };
        java.util.Map map50 = org.mockito.Matchers.refEq(map46, strArray49);
        java.lang.CharSequence charSequence51 = org.mockito.Matchers.refEq((java.lang.CharSequence) "", strArray49);
        java.lang.String[] strArray52 = org.mockito.Matchers.refEq(strArray44, strArray49);
        java.lang.String[] strArray53 = org.mockito.Matchers.refEq(strArray41, strArray49);
        java.lang.Object obj54 = org.mockito.Matchers.refEq((java.lang.Object) (short) 1, strArray41);
        java.io.Serializable serializable55 = org.mockito.Matchers.refEq((java.io.Serializable) wildcardClass35, strArray41);
        java.lang.String str56 = org.mockito.Matchers.refEq("", strArray41);
        java.lang.Class<?> wildcardClass57 = org.mockito.Matchers.refEq(wildcardClass30, strArray41);
        java.lang.Iterable iterable58 = org.mockito.Matchers.refEq(iterable28, strArray41);
        java.lang.String[] strArray59 = org.mockito.Matchers.eq(strArray41);
        java.util.Collection collection60 = org.mockito.Matchers.refEq((java.util.Collection) list0, strArray41);
        java.util.List list61 = org.mockito.Matchers.same(list0);
        java.lang.Iterable iterable62 = org.mockito.Matchers.same((java.lang.Iterable) list0);
        org.junit.Assert.assertNotNull(list0);
        org.junit.Assert.assertNull(iterable1);
        org.junit.Assert.assertNull(list2);
        org.junit.Assert.assertNull(list3);
        org.junit.Assert.assertNotNull(list4);
        org.junit.Assert.assertNotNull(wildcardClass5);
        org.junit.Assert.assertNull(genericDeclaration6);
        org.junit.Assert.assertNotNull(map9);
        org.junit.Assert.assertNotNull(strArray12);
        org.junit.Assert.assertArrayEquals(strArray12, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map13);
        org.junit.Assert.assertNull(str14);
        org.junit.Assert.assertNull(matchers15);
        org.junit.Assert.assertNull(genericDeclaration16);
        org.junit.Assert.assertNotNull(map18);
        org.junit.Assert.assertNotNull(strArray21);
        org.junit.Assert.assertArrayEquals(strArray21, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map22);
        org.junit.Assert.assertNull(charSequence23);
        org.junit.Assert.assertNull(serializable24);
        org.junit.Assert.assertNull(list25);
        org.junit.Assert.assertNull(iterable26);
        org.junit.Assert.assertNotNull(list27);
        org.junit.Assert.assertNull(iterable28);
        org.junit.Assert.assertNotNull(list29);
        org.junit.Assert.assertNotNull(wildcardClass30);
        org.junit.Assert.assertNull(genericDeclaration31);
        org.junit.Assert.assertNull(type32);
        org.junit.Assert.assertNotNull(wildcardClass35);
        org.junit.Assert.assertNotNull(map38);
        org.junit.Assert.assertNotNull(strArray41);
        org.junit.Assert.assertArrayEquals(strArray41, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map42);
        org.junit.Assert.assertNull(str43);
        org.junit.Assert.assertNotNull(map46);
        org.junit.Assert.assertNotNull(strArray49);
        org.junit.Assert.assertArrayEquals(strArray49, new java.lang.String[] { "", "" });
        org.junit.Assert.assertNull(map50);
        org.junit.Assert.assertNull(charSequence51);
        org.junit.Assert.assertNull(strArray52);
        org.junit.Assert.assertNull(strArray53);
        org.junit.Assert.assertNull(obj54);
        org.junit.Assert.assertNull(serializable55);
        org.junit.Assert.assertNull(str56);
        org.junit.Assert.assertNull(wildcardClass57);
        org.junit.Assert.assertNull(iterable58);
        org.junit.Assert.assertNull(strArray59);
        org.junit.Assert.assertNull(collection60);
        org.junit.Assert.assertNull(list61);
        org.junit.Assert.assertNull(iterable62);
    }

    @Test
    public void test3015() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest6.test3015");
        java.util.Set set0 = org.mockito.Matchers.anySet();
        java.util.Set set1 = org.mockito.Matchers.eq(set0);
        java.lang.Iterable iterable2 = org.mockito.Matchers.same((java.lang.Iterable) set0);
        java.lang.Iterable iterable3 = org.mockito.Matchers.same((java.lang.Iterable) set0);
        java.lang.Iterable iterable4 = org.mockito.Matchers.same(iterable3);
        org.junit.Assert.assertNotNull(set0);
        org.junit.Assert.assertNull(set1);
        org.junit.Assert.assertNull(iterable2);
        org.junit.Assert.assertNull(iterable3);
        org.junit.Assert.assertNull(iterable4);
    }
}

